//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class AKTS_Gruplar
    {
        public byte IptDrm { get; set; }
        public string Kodu { get; set; }
        public string Tanimi { get; set; }
        public string Muduru { get; set; }
        public Nullable<double> Primi { get; set; }
        public Nullable<double> MaxPrim { get; set; }
    }
}
