//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class AKTS_SatisTipleri
    {
        public byte IptDrm { get; set; }
        public string Kodu { get; set; }
        public string Tanimi { get; set; }
        public Nullable<double> Pesinat { get; set; }
        public Nullable<short> SenetSayisi { get; set; }
        public Nullable<double> SatisTutari { get; set; }
        public Nullable<double> Toplam { get; set; }
    }
}
