//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class AKTS_Stok_Parca_Karti
    {
        public string Stok_Kodu { get; set; }
        public string Parca_Stok_Kodu { get; set; }
        public string Parca_Stok_Adi { get; set; }
        public Nullable<int> Degisim_Sure_Tipi { get; set; }
        public Nullable<double> Degisim_Suresi { get; set; }
    }
}
