//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class AKTS_Urun_Parca_Degisim
    {
        public byte Fis_Durum { get; set; }
        public byte SatisTipi { get; set; }
        public short SatisYili { get; set; }
        public short SatisAyi { get; set; }
        public int SatisNo { get; set; }
        public int SatisSiraNo { get; set; }
        public string Parca_Stok_Kodu { get; set; }
        public Nullable<System.DateTime> Degisim_Tarihi { get; set; }
    }
}
