//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class AKTS_Prim
    {
        public byte Fis_Durum { get; set; }
        public byte SatisTipi { get; set; }
        public short SatisYili { get; set; }
        public short SatisAyi { get; set; }
        public int SatisNo { get; set; }
        public short SiraNo { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public Nullable<double> Taksit { get; set; }
        public Nullable<double> Prim { get; set; }
        public Nullable<double> MaxPrim { get; set; }
        public string Para_Birimi { get; set; }
    }
}
