//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class AKTS_Satis_Urunler
    {
        public byte Fis_Durum { get; set; }
        public byte SatisTipi { get; set; }
        public short SatisYili { get; set; }
        public short SatisAyi { get; set; }
        public int SatisNo { get; set; }
        public int SatisSiraNo { get; set; }
        public string StokKodu { get; set; }
        public string CihazSeriNo { get; set; }
        public Nullable<System.DateTime> TeslimTarihi { get; set; }
        public Nullable<System.DateTime> MontajTarihi { get; set; }
        public string MusteriAdi { get; set; }
        public string MusteriSoyadi { get; set; }
        public string Adresi { get; set; }
        public string CepTelNo { get; set; }
        public string EMailAdresi { get; set; }
        public Nullable<byte> MusteriBildirim { get; set; }
        public Nullable<int> HarFisNo { get; set; }
        public Nullable<int> HarKlmFisNo { get; set; }
    }
}
