//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class AKTS_Satis
    {
        public byte Fis_Durum { get; set; }
        public byte SatisTipi { get; set; }
        public short SatisYili { get; set; }
        public short SatisAyi { get; set; }
        public int SatisNo { get; set; }
        public string MusteriAdi { get; set; }
        public string MusteriSoyadi { get; set; }
        public string Meslegi { get; set; }
        public string MusteriAdresi { get; set; }
        public string MusteriIlceIl { get; set; }
        public string MusteriTelefon { get; set; }
        public string MusteriTelefon2 { get; set; }
        public string MusteriCepTel { get; set; }
        public Nullable<System.DateTime> SatisTarihi { get; set; }
        public string FaturaUnvani { get; set; }
        public string FaturaAdresi { get; set; }
        public string FaturaIlceIl { get; set; }
        public string VergiDaire { get; set; }
        public string VergiNo { get; set; }
        public string SaticiKodu { get; set; }
        public string GrupKodu { get; set; }
        public string SatisSekli { get; set; }
        public string Para_Birimi { get; set; }
        public string PPara_Birimi { get; set; }
        public Nullable<double> Pesinat { get; set; }
        public Nullable<byte> VadeSayisi { get; set; }
        public Nullable<double> VadeTutari { get; set; }
        public Nullable<double> SatisTutari { get; set; }
        public Nullable<System.DateTime> IlkSenetTar { get; set; }
        public Nullable<int> Stok_No { get; set; }
        public string CihazStokNo { get; set; }
        public string CihazSeriNo { get; set; }
        public string Aciklama { get; set; }
        public string KefilAdiSoyadi1 { get; set; }
        public string KefilMeslegi1 { get; set; }
        public string KefilAdresi1 { get; set; }
        public string KefilIlceIl1 { get; set; }
        public string KefilTelefon1 { get; set; }
        public string KefilTelefon12 { get; set; }
        public string KefilAdiSoyadi2 { get; set; }
        public string KefilMeslegi2 { get; set; }
        public string KefilAdresi2 { get; set; }
        public string KefilIlceIl2 { get; set; }
        public string KefilTelefon2 { get; set; }
        public string KefilTelefon22 { get; set; }
        public Nullable<short> Cari_No { get; set; }
        public Nullable<byte> Iade_Tipi { get; set; }
        public Nullable<int> Iade_Kasa_FisNo { get; set; }
        public Nullable<int> Iade_Senet_FisNo { get; set; }
        public Nullable<int> Iade_Cari_FisNo { get; set; }
        public string Aktarim_Kodu { get; set; }
        public Nullable<byte> Cihaz_Satis_Tipi { get; set; }
        public Nullable<byte> OOdm_Tipi { get; set; }
        public string OOdm_Kasa_Kodu { get; set; }
        public Nullable<int> OOdm_Kasa_FisNo { get; set; }
        public Nullable<System.DateTime> OOdm_Fis_Tarihi { get; set; }
        public Nullable<int> OOdm_Senet_FisNo { get; set; }
        public Nullable<int> OOdm_Cari_FisNo { get; set; }
        public Nullable<double> OOdm_Indirim { get; set; }
        public Nullable<double> OOdm_Arttirim { get; set; }
        public Nullable<double> OOdm_Tutar { get; set; }
        public Nullable<int> Fat_Fis_No { get; set; }
        public Nullable<int> SatisNo2 { get; set; }
        public string eMail_Adresi { get; set; }
        public Nullable<int> SatisNo3 { get; set; }
        public Nullable<int> Must_No { get; set; }
        public string ElemanKodu { get; set; }
        public Nullable<System.DateTime> MontajTarihi { get; set; }
        public Nullable<System.DateTime> TeslimTarihi { get; set; }
        public string Satis_Ref { get; set; }
        public string Promosyon_Kodu { get; set; }
        public Nullable<byte> Prim_Kapali { get; set; }
        public string Acilis_User { get; set; }
        public string Update_User { get; set; }
        public string Iptal_User { get; set; }
        public Nullable<System.DateTime> Acilis_Zaman { get; set; }
        public Nullable<System.DateTime> Update_Zaman { get; set; }
        public Nullable<System.DateTime> Iptal_Zaman { get; set; }
        public string AciklamaIslem { get; set; }
        public string DemoBankKodu { get; set; }
        public string TC_Kimlik_No { get; set; }
        public Nullable<byte> MusteriBildirim { get; set; }
        public Nullable<byte> SatisBicimi { get; set; }
        public string eMail_Adresi_Islem { get; set; }
        public Nullable<System.DateTime> FiltreTarihi { get; set; }
    }
}
