//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class AKTS_YP_Servis
    {
        public byte Fis_Durum { get; set; }
        public int Fis_No { get; set; }
        public int Fis_No_Kalem { get; set; }
        public Nullable<byte> SatisTipi { get; set; }
        public Nullable<short> SatisYili { get; set; }
        public Nullable<short> SatisAyi { get; set; }
        public Nullable<int> SatisNo { get; set; }
        public Nullable<int> SatisNo3 { get; set; }
        public Nullable<byte> IslemTipi { get; set; }
        public Nullable<int> Stok_No { get; set; }
        public Nullable<System.DateTime> IslemTarihi { get; set; }
        public string ElemaniKodu { get; set; }
        public string Aciklama { get; set; }
        public string Stok_Kodu { get; set; }
        public Nullable<int> SatisSiraNo { get; set; }
    }
}
