//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class AKTS_Servis_Fis_Baslik
    {
        public short Isyeri_Kodu { get; set; }
        public short Fis_Tipi { get; set; }
        public int Fis_No { get; set; }
        public Nullable<byte> Fis_Durum { get; set; }
        public Nullable<System.DateTime> Fis_Tarihi { get; set; }
        public Nullable<byte> SatisTipi { get; set; }
        public Nullable<short> SatisYili { get; set; }
        public Nullable<short> SatisAyi { get; set; }
        public Nullable<int> SatisNo { get; set; }
        public Nullable<System.DateTime> SatisTarihi { get; set; }
        public string MusteriAdi { get; set; }
        public string MusteriSoyadi { get; set; }
        public string MusteriAdresi { get; set; }
        public string MusteriIlceIl { get; set; }
        public string MusteriTelefon { get; set; }
        public string MusteriTelefon2 { get; set; }
        public string MusteriCepTel { get; set; }
        public string CihazRBNo { get; set; }
        public string CihazPNNo { get; set; }
        public string CihazAMateNo { get; set; }
        public string CihazRMNo { get; set; }
        public string Aparatlar { get; set; }
        public Nullable<byte> Garanti { get; set; }
        public string TeslimEden { get; set; }
        public string IrtibatTelefon { get; set; }
        public string Sikayeti { get; set; }
        public string Aciklama { get; set; }
        public string Teknisyen { get; set; }
        public string Tesbit { get; set; }
        public string Yapilan { get; set; }
        public Nullable<double> Malz_Tutari { get; set; }
        public Nullable<double> Servis_Ucreti { get; set; }
        public Nullable<double> Toplam_Ucret { get; set; }
        public Nullable<System.DateTime> Teslim_Tarihi { get; set; }
        public string Acilis_User { get; set; }
        public string Update_User { get; set; }
        public string Iptal_User { get; set; }
        public Nullable<System.DateTime> Acilis_Zaman { get; set; }
        public Nullable<System.DateTime> Update_Zaman { get; set; }
        public Nullable<System.DateTime> Iptal_Zaman { get; set; }
    }
}
