//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class AKTS_DemoMusteri_Karti
    {
        public int SiraNo { get; set; }
        public string Musteri_Kodu { get; set; }
        public string Referansi { get; set; }
        public string Musteri_Tipi { get; set; }
        public string Referans_Tipi { get; set; }
        public string Pazarlamaci { get; set; }
        public string Mudur { get; set; }
        public string DemoBank_Kodu { get; set; }
        public Nullable<System.DateTime> Demo_Tarihi { get; set; }
        public Nullable<byte> Tanitima_Gidildi { get; set; }
        public string Aciklama { get; set; }
        public string Yorum { get; set; }
    }
}
