//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class AKTS_Stok_Karti
    {
        public string Stok_Kodu { get; set; }
        public byte Tipi { get; set; }
        public string Stok_Adi { get; set; }
        public string Birimi { get; set; }
        public Nullable<byte> Filtre_Tipi { get; set; }
        public string Ana_Stok_Kodu { get; set; }
        public Nullable<int> Degisim_Suresi { get; set; }
        public Nullable<byte> Promosyon { get; set; }
    }
}
