//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class AKTS_Stok_Hareket
    {
        public short Fis_Tipi { get; set; }
        public int Fis_No { get; set; }
        public int Fis_No_Kalem { get; set; }
        public string Stok_Kodu { get; set; }
        public Nullable<System.DateTime> Fis_Tarihi { get; set; }
        public Nullable<int> Belge_No { get; set; }
        public Nullable<int> SatisNo { get; set; }
        public string Aciklama { get; set; }
        public Nullable<double> Giren { get; set; }
        public Nullable<double> Cikan { get; set; }
    }
}
