//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class AKTS_Satc_Kalem
    {
        public string Kodu { get; set; }
        public byte Fis_Durum { get; set; }
        public byte SatisTipi { get; set; }
        public short SatisYili { get; set; }
        public short SatisAyi { get; set; }
        public int SatisNo { get; set; }
        public System.DateTime Tarih { get; set; }
        public byte IslemTipi { get; set; }
        public Nullable<double> Borc { get; set; }
        public Nullable<double> Alacak { get; set; }
        public string Aciklama { get; set; }
        public Nullable<System.DateTime> Senet_Tarihi { get; set; }
        public string Acilis_User { get; set; }
        public string Update_User { get; set; }
        public string Iptal_User { get; set; }
        public Nullable<System.DateTime> Acilis_Zaman { get; set; }
        public Nullable<System.DateTime> Update_Zaman { get; set; }
        public Nullable<System.DateTime> Iptal_Zaman { get; set; }
        public string Para_Birimi { get; set; }
    }
}
