//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANK_Karti
    {
        public string Banka_Kodu { get; set; }
        public string Banka_TCMB_Kodu { get; set; }
        public string Banka_Adi_Subesi { get; set; }
        public string Banka_Hesap_No { get; set; }
        public string Hesap_ParaBirimi { get; set; }
        public string Musteri_Nosu { get; set; }
        public Nullable<short> Hesap_Tipi { get; set; }
        public Nullable<short> Hesap_Cinsi { get; set; }
        public string Banka_Adres { get; set; }
        public string Banka_TelNo1 { get; set; }
        public string Banka_TelNo2 { get; set; }
        public string Banka_Fax { get; set; }
        public Nullable<short> Isyeri_Kodu { get; set; }
        public string Ozel_Kodu { get; set; }
        public string Yetki_Kodu { get; set; }
        public string Muh_Kodu1 { get; set; }
        public string Muh_Kodu2 { get; set; }
        public Nullable<byte> Havale { get; set; }
        public Nullable<int> Son_Cek_No { get; set; }
        public string Acilis_User { get; set; }
        public string Update_User { get; set; }
        public Nullable<System.DateTime> Acilis_Zaman { get; set; }
        public Nullable<System.DateTime> Update_Zaman { get; set; }
        public string Muh_Kodu3 { get; set; }
        public string Muh_Kodu4 { get; set; }
        public string Muh_Kodu5 { get; set; }
        public string Banka_Adi { get; set; }
        public string Banka_Subesi { get; set; }
        public Nullable<double> Limit_Tutari { get; set; }
        public string IBAN_No { get; set; }
        public Nullable<int> KK_Hs_Gunu { get; set; }
        public Nullable<double> KK_Kmsyn_Oran { get; set; }
        public string KK_Masraf_Kodu { get; set; }
    }
}
