//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class Belge_Karti
    {
        public string Kodu { get; set; }
        public string Adi { get; set; }
        public Nullable<byte> Tipi { get; set; }
        public Nullable<short> Tipi2 { get; set; }
        public Nullable<short> Tipi3 { get; set; }
    }
}
