//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class BRD_FesihKodlari
    {
        public string Bolum { get; set; }
        public string Kodu { get; set; }
        public string Aciklama1 { get; set; }
        public string Aciklama2 { get; set; }
    }
}
