//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class BRD_VergiIadesi
    {
        public string Kodu { get; set; }
        public string Yili { get; set; }
        public Nullable<double> VerMat { get; set; }
        public Nullable<double> GelVer { get; set; }
        public Nullable<double> VerInd { get; set; }
        public Nullable<double> OzlGid { get; set; }
        public Nullable<double> IndKis { get; set; }
        public Nullable<double> IndTut { get; set; }
        public Nullable<double> KalVer { get; set; }
        public Nullable<double> GelVera { get; set; }
        public Nullable<double> GelVerb { get; set; }
        public Nullable<double> Tutar01 { get; set; }
        public Nullable<double> Tutar02 { get; set; }
        public Nullable<double> Tutar03 { get; set; }
        public Nullable<double> Tutar04 { get; set; }
        public Nullable<double> Tutar05 { get; set; }
        public Nullable<double> Tutar06 { get; set; }
        public Nullable<double> Tutar07 { get; set; }
        public Nullable<double> Tutar08 { get; set; }
        public Nullable<double> Tutar09 { get; set; }
        public Nullable<double> Tutar10 { get; set; }
        public Nullable<double> Tutar11 { get; set; }
        public Nullable<double> Tutar12 { get; set; }
    }
}
