//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class BRD_SigortaBilgileri
    {
        public string Kodu { get; set; }
        public string Yil { get; set; }
        public string Ay { get; set; }
        public string Grup { get; set; }
        public string PerGrup { get; set; }
        public Nullable<byte> VerGun { get; set; }
        public Nullable<byte> SskGun { get; set; }
        public Nullable<byte> IznGun { get; set; }
        public Nullable<double> IznTop { get; set; }
        public Nullable<double> VerMat { get; set; }
        public Nullable<double> SigEsasKaz { get; set; }
        public Nullable<double> GelVer { get; set; }
        public Nullable<double> SigMat { get; set; }
        public Nullable<double> SPrmIsKazaIsc { get; set; }
        public Nullable<double> SPrmIsKazaIsv { get; set; }
        public Nullable<double> SPrmAnalikIsc { get; set; }
        public Nullable<double> SPrmAnalikIsv { get; set; }
        public Nullable<double> SPrmHastalikIsc { get; set; }
        public Nullable<double> SPrmHastalikIsv { get; set; }
        public Nullable<double> SPrmKVSKPIsc { get; set; }
        public Nullable<double> SPrmKVSKPIsv { get; set; }
        public Nullable<double> SPrmMalulIsc { get; set; }
        public Nullable<double> SPrmMalulIsv { get; set; }
        public Nullable<double> SPrmGSSPIsc { get; set; }
        public Nullable<double> SPrmGSSPIsv { get; set; }
        public Nullable<double> SPrmSsdfIsc { get; set; }
        public Nullable<double> SPrmSsdfIsv { get; set; }
        public Nullable<double> SPrmItibariIsc { get; set; }
        public Nullable<double> SPrmItibariIsv { get; set; }
        public Nullable<double> SPrmYabanciIsc { get; set; }
        public Nullable<double> SPrmYabanciIsv { get; set; }
        public Nullable<double> SigPrmIsc { get; set; }
        public Nullable<double> SigPrmIsv { get; set; }
        public Nullable<double> SigPrmIscMF { get; set; }
        public Nullable<double> IszIsciMF { get; set; }
        public Nullable<double> TahTop { get; set; }
        public Nullable<double> IhbarTaz { get; set; }
        public Nullable<double> IszIsciSig { get; set; }
        public Nullable<double> IszIsvSig { get; set; }
        public Nullable<double> DamVer { get; set; }
        public Nullable<double> OzSigInd { get; set; }
        public string Bolum { get; set; }
        public Nullable<double> IsvSigIstisna1 { get; set; }
        public Nullable<double> IsvSigIstisna2 { get; set; }
    }
}
