//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class BRD_ViziteBilgileri
    {
        public int Tipi { get; set; }
        public string Kodu { get; set; }
        public double Tarih { get; set; }
        public short Sira { get; set; }
        public Nullable<double> VizTarihi { get; set; }
        public string Aciklama1 { get; set; }
        public string Aciklama2 { get; set; }
        public string Aciklama3 { get; set; }
        public string Aciklama4 { get; set; }
        public string Aciklama5 { get; set; }
        public string Aciklama6 { get; set; }
        public string Aciklama7 { get; set; }
        public string Aciklama8 { get; set; }
        public string Aciklama9 { get; set; }
        public string Aciklama10 { get; set; }
        public string Aciklama11 { get; set; }
        public string Aciklama12 { get; set; }
        public string Aciklama13 { get; set; }
        public string Aciklama14 { get; set; }
        public string Aciklama15 { get; set; }
        public string prsAd { get; set; }
        public string prsSoyad { get; set; }
    }
}
