//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class BRD_OzelKesinti_Bildirim
    {
        public string Kodu { get; set; }
        public byte Tipi { get; set; }
        public System.DateTime Tarihi { get; set; }
        public Nullable<double> Tutari { get; set; }
        public Nullable<double> AyIslem { get; set; }
    }
}
