//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class BRD_GelirKesintiIndirim
    {
        public string Tipi { get; set; }
        public short Sira { get; set; }
        public string Aciklama { get; set; }
        public Nullable<int> Sigorta { get; set; }
        public Nullable<int> Gelir { get; set; }
        public Nullable<int> Damga { get; set; }
        public string Durum { get; set; }
        public Nullable<double> Tutar { get; set; }
    }
}
