//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class BRD_DonemKanuniParametresi
    {
        public string Yil { get; set; }
        public string Ay { get; set; }
        public string Grup { get; set; }
        public string Adi { get; set; }
        public Nullable<double> Sig_Tavani { get; set; }
        public Nullable<double> Sig_Tabani { get; set; }
        public Nullable<float> Sig_Yabanci { get; set; }
        public Nullable<float> Ssd_Orani { get; set; }
        public Nullable<byte> Sak_Ind1 { get; set; }
        public Nullable<byte> Sak_Ind2 { get; set; }
        public Nullable<byte> Sak_Ind3 { get; set; }
        public Nullable<float> Dam_Vergisi { get; set; }
        public Nullable<double> Asgari_Ucret { get; set; }
        public Nullable<double> Gel_Mat1 { get; set; }
        public Nullable<double> Gel_Mat2 { get; set; }
        public Nullable<double> Gel_Mat3 { get; set; }
        public Nullable<double> Gel_Mat4 { get; set; }
        public Nullable<double> Gel_Mat5 { get; set; }
        public Nullable<double> Gel_Mat6 { get; set; }
        public Nullable<double> Gel_Mat7 { get; set; }
        public Nullable<double> Gel_Mat8 { get; set; }
        public Nullable<float> Gel_Orn1 { get; set; }
        public Nullable<float> Gel_Orn2 { get; set; }
        public Nullable<float> Gel_Orn3 { get; set; }
        public Nullable<float> Gel_Orn4 { get; set; }
        public Nullable<float> Gel_Orn5 { get; set; }
        public Nullable<float> Gel_Orn6 { get; set; }
        public Nullable<float> Gel_Orn7 { get; set; }
        public Nullable<float> Gel_Orn8 { get; set; }
        public Nullable<double> Kid_Taz_Tav { get; set; }
        public Nullable<float> IssizIsci { get; set; }
        public Nullable<float> IssizIsv { get; set; }
        public Nullable<float> IssizDevlet { get; set; }
        public Nullable<double> Sak_IndTut1 { get; set; }
        public Nullable<double> Sak_IndTut2 { get; set; }
        public Nullable<double> Sak_IndTut3 { get; set; }
        public Nullable<double> Max_AGITut { get; set; }
    }
}
