//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class BRD_PuantajBilgileri
    {
        public string Kodu { get; set; }
        public string Yil { get; set; }
        public string Ay { get; set; }
        public string Grup { get; set; }
        public Nullable<double> Ucret { get; set; }
        public Nullable<float> NormalGun { get; set; }
        public Nullable<float> HaftatGun { get; set; }
        public Nullable<float> BayramGun { get; set; }
        public Nullable<float> IzinGun { get; set; }
        public Nullable<float> RaporGun { get; set; }
        public Nullable<float> YemekGun { get; set; }
        public Nullable<float> IkramGun { get; set; }
        public Nullable<float> UcIznGun { get; set; }
        public Nullable<float> NormalSaat { get; set; }
        public Nullable<float> HaftatSaat { get; set; }
        public Nullable<float> BayramSaat { get; set; }
        public Nullable<float> IzinSaat { get; set; }
        public Nullable<float> IkramSaat { get; set; }
        public Nullable<float> Mes1 { get; set; }
        public Nullable<float> Mes2 { get; set; }
        public Nullable<float> Mes3 { get; set; }
        public Nullable<float> Mes4 { get; set; }
        public Nullable<float> PazMesGun { get; set; }
        public Nullable<float> BayMesGun { get; set; }
        public Nullable<float> GecZam1 { get; set; }
        public Nullable<float> GecZam2 { get; set; }
        public string IzinKul { get; set; }
        public string EkGunNdn { get; set; }
        public Nullable<float> KmSaat { get; set; }
        public Nullable<float> Vardiye { get; set; }
        public Nullable<float> DirGun { get; set; }
        public Nullable<double> DirTutar { get; set; }
        public Nullable<float> YipOrn { get; set; }
        public Nullable<float> YipGun { get; set; }
        public Nullable<double> YipTutar { get; set; }
        public Nullable<byte> VerGrb { get; set; }
        public Nullable<byte> SigGrb { get; set; }
        public Nullable<byte> CocSys { get; set; }
        public Nullable<byte> CocGelir { get; set; }
        public Nullable<byte> CocDamga { get; set; }
        public Nullable<float> ArzGun { get; set; }
        public Nullable<double> ArzTutar { get; set; }
        public Nullable<float> ArzOrn { get; set; }
        public Nullable<double> Sorumluluk { get; set; }
        public Nullable<byte> Yatili { get; set; }
        public Nullable<float> HarGun { get; set; }
        public string Bolum { get; set; }
        public Nullable<byte> Sube_Giris { get; set; }
        public Nullable<byte> Sube_Cikis { get; set; }
        public Nullable<float> SihhatGun { get; set; }
        public Nullable<float> SihhatSaat { get; set; }
        public Nullable<float> UcrIznGun { get; set; }
        public Nullable<float> UcrIznSaat { get; set; }
        public Nullable<float> VerAvans { get; set; }
    }
}
