//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class BRD_AylikSigortaParametresi
    {
        public string Bolum { get; set; }
        public string Yil { get; set; }
        public string Ay { get; set; }
        public string AdSoyad { get; set; }
        public string Unvani { get; set; }
        public string Adres1 { get; set; }
        public string Adres2 { get; set; }
        public string TasAdSoy { get; set; }
        public string TasAdr1 { get; set; }
        public string TasAdr2 { get; set; }
        public string IsYapEsIs { get; set; }
        public string TehDer { get; set; }
        public string Ust { get; set; }
        public string Alt { get; set; }
        public string Normal { get; set; }
        public string Iptal { get; set; }
        public string Asil { get; set; }
        public string Ek { get; set; }
        public string IsSigNo { get; set; }
        public string BolCalNo { get; set; }
        public string VergiD { get; set; }
        public string VergiN { get; set; }
        public string BankaSubeAdi { get; set; }
        public string BankaAdi { get; set; }
        public string SSKIsKodu { get; set; }
        public string SSKMeslek { get; set; }
        public string SSKIsKolu { get; set; }
        public string SSKSube { get; set; }
        public string SSKSiraNo { get; set; }
        public string SSKil { get; set; }
        public string SSKilce { get; set; }
        public string BolSinif { get; set; }
        public string BolMeslek { get; set; }
        public string BolSube { get; set; }
        public string BolDosya { get; set; }
        public string Bolil { get; set; }
        public string Bolilce { get; set; }
        public string KNNo { get; set; }
        public string AraciKodu { get; set; }
        public string DuzAdi { get; set; }
        public string MuhAdi { get; set; }
        public string OdaSicilNo { get; set; }
        public string Banka { get; set; }
        public Nullable<short> IsciSys { get; set; }
        public Nullable<short> KadinSys { get; set; }
        public Nullable<short> IzinKul { get; set; }
        public Nullable<short> EmekliSys { get; set; }
        public Nullable<short> YabSys { get; set; }
        public Nullable<short> CirakSys { get; set; }
        public string Mersis_No { get; set; }
    }
}
