//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class BRD_Es_Cocuklar
    {
        public string Kodu { get; set; }
        public byte Sira { get; set; }
        public string Adi { get; set; }
        public string Soyadi { get; set; }
        public Nullable<byte> Tipi { get; set; }
        public Nullable<byte> Cinsiyet { get; set; }
        public string TCKimlikNo { get; set; }
        public string SigSicilNo { get; set; }
        public string BagSicNo { get; set; }
        public Nullable<byte> Tahsil { get; set; }
        public Nullable<byte> VerInd { get; set; }
    }
}
