//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class BRD_DonemBolumParametresi
    {
        public string Yil { get; set; }
        public string Ay { get; set; }
        public string Grup { get; set; }
        public string Bolum { get; set; }
        public Nullable<float> Calisma_Saati { get; set; }
        public Nullable<float> Yev_Orani { get; set; }
        public Nullable<float> Sen_Orani { get; set; }
        public Nullable<float> Day_Orani { get; set; }
        public Nullable<double> Gun_Indirim { get; set; }
        public Nullable<double> Cocuk_Parasi { get; set; }
        public Nullable<double> Cocuk_Okumayan { get; set; }
        public Nullable<double> Cocuk_Ilk { get; set; }
        public Nullable<double> Cocuk_Orta { get; set; }
        public Nullable<double> Cocuk_Yuksek { get; set; }
        public Nullable<double> Yem_Parasi { get; set; }
        public Nullable<double> Yip_Parasi { get; set; }
        public Nullable<double> Direksiyon { get; set; }
        public Nullable<double> Yuvarlama { get; set; }
        public Nullable<float> Ver_IOrani { get; set; }
        public Nullable<double> Indirim { get; set; }
        public Nullable<byte> Sig_Gun { get; set; }
        public string VIade { get; set; }
        public Nullable<float> Mes_Orn1 { get; set; }
        public Nullable<float> Mes_Orn2 { get; set; }
        public Nullable<float> Mes_Orn3 { get; set; }
        public Nullable<float> Mes_Orn4 { get; set; }
        public Nullable<float> Gun_Mes1 { get; set; }
        public Nullable<float> Gun_Mes2 { get; set; }
        public Nullable<float> Gun_Mes3 { get; set; }
        public Nullable<float> Gece_Zam1 { get; set; }
        public Nullable<float> Gece_Zam2 { get; set; }
        public Nullable<float> Sigorta_Emekli { get; set; }
        public Nullable<float> Sigorta_Isci { get; set; }
        public Nullable<float> Sigorta_IsKazasi { get; set; }
        public Nullable<float> Sigorta_Analik { get; set; }
        public Nullable<float> Sigorta_Hastalik { get; set; }
        public Nullable<float> Sigorta_KVSKP { get; set; }
        public Nullable<float> Sigorta_Malul { get; set; }
        public Nullable<float> Sigorta_GSSP { get; set; }
        public Nullable<float> Sigorta_Itibari { get; set; }
        public Nullable<float> IsKazasi_Isci { get; set; }
        public Nullable<float> IsKazasi_Isveren { get; set; }
        public Nullable<float> Analik_Isci { get; set; }
        public Nullable<float> Analik_Isveren { get; set; }
        public Nullable<float> Hastalik_Isci { get; set; }
        public Nullable<float> Hastalik_Isveren { get; set; }
        public Nullable<float> KVSKP_Isci { get; set; }
        public Nullable<float> KVSKP_Isveren { get; set; }
        public Nullable<float> Malul_Isci { get; set; }
        public Nullable<float> Malul_Isveren { get; set; }
        public Nullable<float> GSSP_Isci { get; set; }
        public Nullable<float> GSSP_Isveren { get; set; }
        public Nullable<float> Itibari_Isci { get; set; }
        public Nullable<float> Itibari_Isveren { get; set; }
        public Nullable<double> Emekli_Isveren { get; set; }
        public string Rapor_Tipi { get; set; }
        public Nullable<double> IsMakinasi1 { get; set; }
        public Nullable<double> IsMakinasi2 { get; set; }
        public Nullable<double> IsMakinasi3 { get; set; }
        public Nullable<double> IsMakinasi4 { get; set; }
        public Nullable<double> IsMakinasi5 { get; set; }
        public Nullable<double> IsMakinasi6 { get; set; }
        public Nullable<double> IsMakinasi7 { get; set; }
        public Nullable<byte> Gelir { get; set; }
        public Nullable<double> Yatili { get; set; }
    }
}
