//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class BRD_Puantaj_Cetveli
    {
        public string Kodu { get; set; }
        public string Yili { get; set; }
        public string Ayi { get; set; }
        public string Grup { get; set; }
        public Nullable<double> Ucret { get; set; }
        public string Gun1 { get; set; }
        public string Gun2 { get; set; }
        public string Gun3 { get; set; }
        public string Gun4 { get; set; }
        public string Gun5 { get; set; }
        public string Gun6 { get; set; }
        public string Gun7 { get; set; }
        public string Gun8 { get; set; }
        public string Gun9 { get; set; }
        public string Gun10 { get; set; }
        public string Gun11 { get; set; }
        public string Gun12 { get; set; }
        public string Gun13 { get; set; }
        public string Gun14 { get; set; }
        public string Gun15 { get; set; }
        public string Gun16 { get; set; }
        public string Gun17 { get; set; }
        public string Gun18 { get; set; }
        public string Gun19 { get; set; }
        public string Gun20 { get; set; }
        public string Gun21 { get; set; }
        public string Gun22 { get; set; }
        public string Gun23 { get; set; }
        public string Gun24 { get; set; }
        public string Gun25 { get; set; }
        public string Gun26 { get; set; }
        public string Gun27 { get; set; }
        public string Gun28 { get; set; }
        public string Gun29 { get; set; }
        public string Gun30 { get; set; }
        public string Gun31 { get; set; }
        public byte ToplamGun { get; set; }
    }
}
