//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class BRD_PersonelBilgileri
    {
        public string Kodu { get; set; }
        public string Adi { get; set; }
        public string Soyadi { get; set; }
        public string SigSicilNo { get; set; }
        public string Resim { get; set; }
        public string TasNo { get; set; }
        public string BagSicNo { get; set; }
        public Nullable<byte> Cinsiyet { get; set; }
        public Nullable<byte> Tahsil { get; set; }
        public Nullable<byte> Medeni { get; set; }
        public string Askerlik { get; set; }
        public Nullable<byte> SozTipi { get; set; }
        public Nullable<byte> SakHuk { get; set; }
        public Nullable<byte> VerGrb { get; set; }
        public Nullable<byte> SigGrb { get; set; }
        public string EmkSicNo { get; set; }
        public Nullable<byte> Tasarruf { get; set; }
        public string Unvani { get; set; }
        public string Bolum { get; set; }
        public string PerGrup { get; set; }
        public Nullable<double> GirTarihi { get; set; }
        public Nullable<double> Ucret { get; set; }
        public Nullable<byte> UcNevi { get; set; }
        public Nullable<byte> CalSek { get; set; }
        public Nullable<byte> DrkEnd { get; set; }
        public Nullable<byte> Sendika { get; set; }
        public Nullable<double> SenTarihi { get; set; }
        public Nullable<byte> OdmKod { get; set; }
        public string BnkHesNo { get; set; }
        public string BnkSube { get; set; }
        public Nullable<byte> CosSayisi { get; set; }
        public Nullable<byte> CosGelir { get; set; }
        public Nullable<byte> CosDamga { get; set; }
        public Nullable<byte> CosOkOn { get; set; }
        public Nullable<byte> CosIlk { get; set; }
        public Nullable<byte> CosOrta { get; set; }
        public Nullable<byte> CosYuksek { get; set; }
        public Nullable<byte> GrvKodu { get; set; }
        public Nullable<byte> SosGuvKodu { get; set; }
        public string SeriNo { get; set; }
        public string CuzdanNo { get; set; }
        public string TCKimlikNo { get; set; }
        public string BabaAdi { get; set; }
        public Nullable<double> DogTarihi { get; set; }
        public string DogYeri { get; set; }
        public string AnaAdi { get; set; }
        public string EsininAdi { get; set; }
        public string Dini { get; set; }
        public string KanGrubu { get; set; }
        public string Il { get; set; }
        public string Ilce { get; set; }
        public string Mahalle { get; set; }
        public string CiltNo { get; set; }
        public string AileSiraNo { get; set; }
        public string SiraNo { get; set; }
        public string VerNufDa { get; set; }
        public string VerNedeni { get; set; }
        public string KayitNo { get; set; }
        public Nullable<double> VerTarihi { get; set; }
        public string KizlikSoy { get; set; }
        public Nullable<double> CikTarihi { get; set; }
        public string FesihKodu { get; set; }
        public string CikAck1 { get; set; }
        public string CikAck2 { get; set; }
        public string CikAck3 { get; set; }
        public Nullable<double> Sorumluluk { get; set; }
        public Nullable<int> YipOrn { get; set; }
        public Nullable<byte> KidYili { get; set; }
        public Nullable<byte> AracNo { get; set; }
        public string Eili { get; set; }
        public string EUnvan { get; set; }
        public string ECUnvan { get; set; }
        public string EAdres { get; set; }
        public string Adres1 { get; set; }
        public string Adres2 { get; set; }
        public string Adres3 { get; set; }
        public string EvTel { get; set; }
        public string CepTel { get; set; }
        public string VerKimNo { get; set; }
        public string VergiDairesi { get; set; }
        public string AsCuzNo { get; set; }
        public string CikNedeni { get; set; }
        public Nullable<double> AclTarih { get; set; }
        public string Uyrugu { get; set; }
        public string EMail { get; set; }
        public Nullable<int> prsDurum { get; set; }
        public string FesihKodu2 { get; set; }
        public Nullable<double> AGI_Oran { get; set; }
        public Nullable<double> AyIkrOrani { get; set; }
        public Nullable<double> AUcret { get; set; }
        public Nullable<short> Isyeri_Kodu { get; set; }
        public string BnkAdi { get; set; }
        public string Ehliyet { get; set; }
        public Nullable<byte> CocSayisi { get; set; }
        public Nullable<double> BankTrnTutari { get; set; }
        public Nullable<double> GunlukCalismaSaati { get; set; }
        public Nullable<int> HaftalikIzinGunu { get; set; }
        public string Muh_Kodu1 { get; set; }
        public string Muh_Kodu2 { get; set; }
        public Nullable<double> AGI_Tutari { get; set; }
        public string Kanun_No { get; set; }
        public string Meslek_Tecrubesi { get; set; }
        public string Oturma_Bolgesi { get; set; }
        public string CalismaYeri { get; set; }
        public string Masraf_Yeri { get; set; }
        public string Meslek_Kodu { get; set; }
        public Nullable<byte> IsvSakIndOrn { get; set; }
        public Nullable<byte> SakHukIndVar { get; set; }
        public Nullable<int> PdksID { get; set; }
    }
}
