//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class BRD_PuantajGelKesIndBilgileri
    {
        public string Kodu { get; set; }
        public string Yil { get; set; }
        public string Ay { get; set; }
        public string Grup { get; set; }
        public string Bolum { get; set; }
        public string Tipi { get; set; }
        public short Sira { get; set; }
        public Nullable<double> Tutar { get; set; }
        public Nullable<double> BTutar { get; set; }
    }
}
