//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class BRD_TahakkukBilgileri
    {
        public string Kodu { get; set; }
        public string Yil { get; set; }
        public string Ay { get; set; }
        public string Grup { get; set; }
        public string PerGrup { get; set; }
        public Nullable<byte> CalGun { get; set; }
        public Nullable<byte> SigGun { get; set; }
        public Nullable<byte> IznGun { get; set; }
        public Nullable<double> NorCalTut { get; set; }
        public Nullable<double> HafTatTut { get; set; }
        public Nullable<double> BayTatTut { get; set; }
        public Nullable<double> YilIzin { get; set; }
        public Nullable<double> IkramTut { get; set; }
        public Nullable<double> RaporTut { get; set; }
        public Nullable<double> AsgUcTut { get; set; }
        public Nullable<double> Kaztut { get; set; }
        public Nullable<double> FMS1 { get; set; }
        public Nullable<double> FMS2 { get; set; }
        public Nullable<double> FMS3 { get; set; }
        public Nullable<double> FMS4 { get; set; }
        public Nullable<double> PazarMes { get; set; }
        public Nullable<double> BayramMes { get; set; }
        public Nullable<double> GeceZam1 { get; set; }
        public Nullable<double> GeceZam2 { get; set; }
        public Nullable<double> FazMesTop { get; set; }
        public Nullable<double> Cocuk { get; set; }
        public Nullable<double> CocukVer { get; set; }
        public Nullable<double> CocukDam { get; set; }
        public Nullable<double> CocukOnce { get; set; }
        public Nullable<double> CocukIlk { get; set; }
        public Nullable<double> CocukOrta { get; set; }
        public Nullable<double> CocukYuksek { get; set; }
        public Nullable<double> CocukOkul { get; set; }
        public Nullable<double> CocukToplam { get; set; }
        public Nullable<double> YemekTut { get; set; }
        public Nullable<double> Direksiyon { get; set; }
        public Nullable<double> Yipranma { get; set; }
        public Nullable<double> Arazi { get; set; }
        public Nullable<double> Sorumluluk { get; set; }
        public Nullable<double> SosKaz { get; set; }
        public Nullable<double> DigerKaz { get; set; }
        public Nullable<double> SigEsasKaz { get; set; }
        public Nullable<double> SigMat { get; set; }
        public Nullable<double> VerMat { get; set; }
        public Nullable<double> DamMat { get; set; }
        public Nullable<double> SPrmIsKazaIsc { get; set; }
        public Nullable<double> SPrmIsKazaIsv { get; set; }
        public Nullable<double> SPrmAnalikIsc { get; set; }
        public Nullable<double> SPrmAnalikIsv { get; set; }
        public Nullable<double> SPrmHastalikIsc { get; set; }
        public Nullable<double> SPrmHastalikIsv { get; set; }
        public Nullable<double> SPrmKVSKPIsc { get; set; }
        public Nullable<double> SPrmKVSKPIsv { get; set; }
        public Nullable<double> SPrmMalulIsc { get; set; }
        public Nullable<double> SPrmMalulIsv { get; set; }
        public Nullable<double> SPrmGSSPIsc { get; set; }
        public Nullable<double> SPrmGSSPIsv { get; set; }
        public Nullable<double> SPrmSsdfIsc { get; set; }
        public Nullable<double> SPrmSsdfIsv { get; set; }
        public Nullable<double> SPrmItibariIsc { get; set; }
        public Nullable<double> SPrmItibariIsv { get; set; }
        public Nullable<double> SPrmYabanciIsc { get; set; }
        public Nullable<double> SPrmYabanciIsv { get; set; }
        public Nullable<double> IszIsci { get; set; }
        public Nullable<double> IszIsv { get; set; }
        public Nullable<double> SigPrm { get; set; }
        public Nullable<double> IsvHis { get; set; }
        public Nullable<double> VerInd { get; set; }
        public Nullable<double> SakInd { get; set; }
        public Nullable<double> GelVer { get; set; }
        public Nullable<double> DamVer { get; set; }
        public Nullable<double> IznHis { get; set; }
        public Nullable<double> SigPrmIscMF { get; set; }
        public Nullable<double> IszIsciMF { get; set; }
        public Nullable<double> Sendika { get; set; }
        public Nullable<double> Ssdf { get; set; }
        public Nullable<double> Dayanisma { get; set; }
        public Nullable<double> YasalKes { get; set; }
        public Nullable<double> OzelKes { get; set; }
        public Nullable<double> DigerKes { get; set; }
        public Nullable<double> Yatili { get; set; }
        public Nullable<double> Tahakkuk { get; set; }
        public Nullable<double> Kesinti { get; set; }
        public Nullable<double> Odenen { get; set; }
        public Nullable<double> VIadeTutar { get; set; }
        public string Viad { get; set; }
        public string AsgUcret { get; set; }
        public Nullable<short> RapGun { get; set; }
        public Nullable<double> RapTut1 { get; set; }
        public Nullable<double> RapTut2 { get; set; }
        public Nullable<double> AGI_Oran { get; set; }
        public Nullable<double> AGI_Tutar { get; set; }
        public Nullable<short> Isyeri_Kodu { get; set; }
        public string Bolum { get; set; }
        public Nullable<double> IsvSigIstisna1 { get; set; }
        public Nullable<double> IsvSigIstisna2 { get; set; }
        public Nullable<double> VerAvans { get; set; }
        public Nullable<double> DDes_Tutar { get; set; }
    }
}
