//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class BTC_Parametre
    {
        public int Butce_Par_No { get; set; }
        public string Butce_Par_Kodu { get; set; }
        public string Butce_Par_Adi { get; set; }
        public Nullable<int> IptDrm { get; set; }
        public string Para_Kodu_Is { get; set; }
        public string Para_Kodu_Butce { get; set; }
        public Nullable<double> TL_USD_Ocak { get; set; }
        public Nullable<double> TL_USD_Subat { get; set; }
        public Nullable<double> TL_USD_Mart { get; set; }
        public Nullable<double> TL_USD_Nisan { get; set; }
        public Nullable<double> TL_USD_Mayis { get; set; }
        public Nullable<double> TL_USD_Haziran { get; set; }
        public Nullable<double> TL_USD_Temmuz { get; set; }
        public Nullable<double> TL_USD_Agustos { get; set; }
        public Nullable<double> TL_USD_Eylul { get; set; }
        public Nullable<double> TL_USD_Ekim { get; set; }
        public Nullable<double> TL_USD_Kasim { get; set; }
        public Nullable<double> TL_USD_Aralik { get; set; }
        public Nullable<int> Kisa_Vad_TL_Kredi_Yillik { get; set; }
        public Nullable<int> Kisa_Vad_TL_Kredi_AOP { get; set; }
        public Nullable<int> Kisa_Vad_TL_Kredi_FOP { get; set; }
        public Nullable<int> Orta_Vad_TL_Kredi_Yillik1 { get; set; }
        public Nullable<int> Orta_Vad_TL_Kredi_AOP { get; set; }
        public Nullable<int> Orta_Vad_TL_Kredi_FOP { get; set; }
        public Nullable<int> Kisa_Vad_US_Kredi_Yillik { get; set; }
        public Nullable<int> Kisa_Vad_US_Kredi_AOP { get; set; }
        public Nullable<int> Kisa_Vad_US_Kredi_FOP { get; set; }
        public Nullable<int> Orta_Vad_US_Kredi_Yillik { get; set; }
        public Nullable<int> Orta_Vad_US_Kredi_AOP { get; set; }
        public Nullable<int> Orta_Vad_US_Kredi_FOP { get; set; }
        public Nullable<int> Kisa_Vad_PreFi_Kredi_Yillik { get; set; }
        public Nullable<int> Kisa_Vad_PreFi_Kredi_AOP { get; set; }
        public Nullable<int> Kisa_Vad_PreFi_Kredi_FOP { get; set; }
        public Nullable<int> Orta_Vad_PreFi_Kredi_Yillik { get; set; }
        public Nullable<int> Orta_Vad_PreFi_Kredi_AOP { get; set; }
        public Nullable<int> Orta_Vad_PreFi_Kredi_FOP { get; set; }
        public Nullable<int> Tah_Fin_Bon_Yillik { get; set; }
        public Nullable<int> Tah_Fin_Bon_AOP { get; set; }
        public Nullable<int> Tah_Fin_Bon_FOP { get; set; }
        public Nullable<int> TL_Aylik_Rep { get; set; }
        public Nullable<double> TL_Repo_Lim { get; set; }
        public Nullable<double> TL_Kasa_Limiti { get; set; }
        public Nullable<int> Kurum_Ver { get; set; }
        public Nullable<int> KDV { get; set; }
        public Nullable<int> Gecici_Ver { get; set; }
        public Nullable<int> Temettu { get; set; }
        public Nullable<int> NCS_Ocak { get; set; }
        public Nullable<int> NCS_Subat { get; set; }
        public Nullable<int> NCS_Mart { get; set; }
        public Nullable<int> NCS_Nisan { get; set; }
        public Nullable<int> NCS_Mayis { get; set; }
        public Nullable<int> NCS_Haziran { get; set; }
        public Nullable<int> NCS_Temmuz { get; set; }
        public Nullable<int> NCS_Agustos { get; set; }
        public Nullable<int> NCS_Eylul { get; set; }
        public Nullable<int> NCS_Ekim { get; set; }
        public Nullable<int> NCS_Kasim { get; set; }
        public Nullable<int> NCS_Aralik { get; set; }
        public Nullable<double> Kid_Taz_Lim { get; set; }
        public Nullable<double> SSK_Pir_Lim { get; set; }
        public Nullable<double> Damga_Pulu { get; set; }
        public Nullable<double> SSK_Pir_Isci_Pay { get; set; }
        public Nullable<double> ISS_Pir_Isci_Pay { get; set; }
        public Nullable<double> SSK_Pir_Isveren_Pay { get; set; }
        public Nullable<double> ISS_Pir_Isveren_Pay { get; set; }
        public Nullable<double> Asgari_Gec_Ind { get; set; }
        public Nullable<double> Fazla_Calisma_Kat { get; set; }
        public Nullable<double> Ih_Taz_Orani { get; set; }
        public Nullable<double> Brut_Uc_Artisi1 { get; set; }
        public Nullable<double> Brut_Uc_Artisi2 { get; set; }
        public Nullable<double> Saat_Uc_Artisi1 { get; set; }
        public Nullable<double> Saat_Uc_Artisi2 { get; set; }
        public Nullable<double> SSK_Tav_Artisi1 { get; set; }
        public Nullable<double> SSK_Tav_Artisi2 { get; set; }
        public Nullable<double> KTaz_Tav_Artisi1 { get; set; }
        public Nullable<double> KTaz_Tav_Artisi2 { get; set; }
        public Nullable<double> Yem_Yar_Artisi1 { get; set; }
        public Nullable<double> Yem_Yar_Artisi2 { get; set; }
        public Nullable<double> Tas_Yar_Artisi1 { get; set; }
        public Nullable<double> Tas_Yar_Artisi2 { get; set; }
        public Nullable<double> San_Taz_Artisi1 { get; set; }
        public Nullable<double> San_Taz_Artisi2 { get; set; }
        public Nullable<double> Sem_Eg_Artisi1 { get; set; }
        public Nullable<double> Sem_Eg_Artisi2 { get; set; }
        public Nullable<double> EDO_Yar_Artisi1 { get; set; }
        public Nullable<double> EDO_Yar_Artisi2 { get; set; }
        public Nullable<double> Yak_Yar_Artisi1 { get; set; }
        public Nullable<double> Yak_Yar_Artisi2 { get; set; }
        public Nullable<double> Coc_Yar_Artisi1 { get; set; }
        public Nullable<double> Coc_Yar_Artisi2 { get; set; }
        public Nullable<double> Giy_Kor_Artisi1 { get; set; }
        public Nullable<double> Giy_Kor_Artisi2 { get; set; }
        public Nullable<double> Diger_Yar_Artisi1 { get; set; }
        public Nullable<double> Diger_Yar_Artisi2 { get; set; }
        public Nullable<double> Sta_Uc_Artisi1 { get; set; }
        public Nullable<double> Sta_Uc_Artisi2 { get; set; }
        public Nullable<double> Ikramiye_Artisi1 { get; set; }
        public Nullable<double> Ikramiye_Artisi2 { get; set; }
        public Nullable<double> Brut_Uc_Pes { get; set; }
        public Nullable<double> Brut_Uc_1AyVade { get; set; }
        public Nullable<double> Brut_Uc_2AyVade { get; set; }
        public Nullable<double> Brut_Uc_3AyVade { get; set; }
        public Nullable<double> Saat_Uc_Pes { get; set; }
        public Nullable<double> Saat_Uc_1AyVade { get; set; }
        public Nullable<double> Saat_Uc_2AyVade { get; set; }
        public Nullable<double> Saat_Uc_3AyVade { get; set; }
        public Nullable<double> SSK_IsverPay_Pes { get; set; }
        public Nullable<double> SSK_IsverPay_1AyVade { get; set; }
        public Nullable<double> SSK_IsverPay_2AyVade { get; set; }
        public Nullable<double> SSK_IsverPay_3AyVade { get; set; }
        public Nullable<double> Kid_Taz_Pes { get; set; }
        public Nullable<double> Kid_Taz_1AyVade { get; set; }
        public Nullable<double> Kid_Taz_2AyVade { get; set; }
        public Nullable<double> Kid_Taz_3AyVade { get; set; }
        public Nullable<double> Yemek_Yar_Pes { get; set; }
        public Nullable<double> Yemek_Yar_1AyVade { get; set; }
        public Nullable<double> Yemek_Yar_2AyVade { get; set; }
        public Nullable<double> Yemek_Yar_3AyVade { get; set; }
        public Nullable<double> Tas_Yar_Pes { get; set; }
        public Nullable<double> Tas_Yar_1AyVade { get; set; }
        public Nullable<double> Tas_Yar_2AyVade { get; set; }
        public Nullable<double> Tas_Yar_3AyVade { get; set; }
        public Nullable<double> San_Taz_Pes { get; set; }
        public Nullable<double> San_Taz_1AyVade { get; set; }
        public Nullable<double> San_Taz_2AyVade { get; set; }
        public Nullable<double> San_Taz_3AyVade { get; set; }
        public Nullable<double> Sem_Eg_Gideri_Pes { get; set; }
        public Nullable<double> Sem_Eg_Gideri_1AyVade { get; set; }
        public Nullable<double> Sem_Eg_Gideri_2AyVade { get; set; }
        public Nullable<double> Sem_Eg_Gideri_3AyVade { get; set; }
        public Nullable<double> EDO_Pes { get; set; }
        public Nullable<double> EDO_1AyVade { get; set; }
        public Nullable<double> EDO_2AyVade { get; set; }
        public Nullable<double> EDo_3AyVade { get; set; }
        public Nullable<double> Yak_Yar_Pes { get; set; }
        public Nullable<double> Yak_Yar_1AyVade { get; set; }
        public Nullable<double> Yak_Yar_2AyVade { get; set; }
        public Nullable<double> Yak_Yar_3AyVade { get; set; }
        public Nullable<double> Coc_Yar_Pes { get; set; }
        public Nullable<double> Coc_Yar_1AyVade { get; set; }
        public Nullable<double> Coc_Yar_2AyVade { get; set; }
        public Nullable<double> Coc_Yar_3AyVade { get; set; }
        public Nullable<double> Giy_Kor_Yar_Pes { get; set; }
        public Nullable<double> Giy_Kor_Yar_1AyVade { get; set; }
        public Nullable<double> Giy_Kor_Yar_2AyVade { get; set; }
        public Nullable<double> Giy_Kor_Yar_3AyVade { get; set; }
        public Nullable<double> Diger_Yar_Pes { get; set; }
        public Nullable<double> Diger_Yar_1AyVade { get; set; }
        public Nullable<double> Diger_Yar_2AyVade { get; set; }
        public Nullable<double> Diger_Yar_3AyVade { get; set; }
        public Nullable<double> Sta_Uc_Pes { get; set; }
        public Nullable<double> Sta_Uc_1AyVade { get; set; }
        public Nullable<double> Sta_Uc_2AyVade { get; set; }
        public Nullable<double> Sta_Uc_3AyVade { get; set; }
        public Nullable<double> Ikramiye_Pes { get; set; }
        public Nullable<double> Ikramiye_1AyVade { get; set; }
        public Nullable<double> Ikramiye_2AyVade { get; set; }
        public Nullable<double> Ikramiye_3AyVade { get; set; }
    }
}
