//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class BTC_Karti
    {
        public int Butce_No { get; set; }
        public Nullable<int> Butce_Yili { get; set; }
        public string Aciklama { get; set; }
        public string Planlama { get; set; }
        public string MaliIsveButceleme { get; set; }
        public string Butce_Yonetim { get; set; }
        public string Butce_Par_Kodu { get; set; }
        public string Butce_ParaBirim { get; set; }
        public Nullable<int> Butce_Mali_Olcek { get; set; }
        public Nullable<System.DateTime> Bas_Tarih { get; set; }
        public Nullable<System.DateTime> Bit_Tarih { get; set; }
        public Nullable<System.DateTime> Fin_Gel_Bit_Tarih { get; set; }
        public int IptDrm { get; set; }
        public string Acilis_User { get; set; }
        public string Update_User { get; set; }
        public Nullable<System.DateTime> Acilis_Zaman { get; set; }
        public Nullable<System.DateTime> Update_Zaman { get; set; }
    }
}
