//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class BTC_Gider_Parametre
    {
        public int Butce_Par_No { get; set; }
        public string Hesap_Kodu { get; set; }
        public string Adi { get; set; }
        public Nullable<double> Yillik_Artis { get; set; }
        public Nullable<int> Bas_Ay { get; set; }
        public Nullable<int> Peryod { get; set; }
        public string Odemesi { get; set; }
        public Nullable<int> Gider_Tipi { get; set; }
        public Nullable<int> IptDrm { get; set; }
    }
}
