//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class BTC_Uret_Recete_Detay
    {
        public int IptDrm { get; set; }
        public string Recete_Kodu { get; set; }
        public int Sira { get; set; }
        public string Kalem_Tipi { get; set; }
        public string Stok_Masraf_Kodu { get; set; }
        public string Stok_Masraf_Adi { get; set; }
        public string Birimi { get; set; }
        public Nullable<double> Miktar { get; set; }
    }
}
