//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class BTC_Uret_Recete
    {
        public int IptDrm { get; set; }
        public string Recete_Kodu { get; set; }
        public Nullable<int> Stok_No { get; set; }
        public string Stok_Kodu { get; set; }
        public string Tanimi { get; set; }
        public Nullable<double> Miktari { get; set; }
        public string Birimi { get; set; }
    }
}
