//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class BTC_Satis_Sartlari
    {
        public int IptDrm { get; set; }
        public int Butce_No { get; set; }
        public int Stok_No { get; set; }
        public string Stok_Kodu { get; set; }
        public Nullable<double> KDV { get; set; }
        public Nullable<double> Isk { get; set; }
        public string Odemesi { get; set; }
        public string Kdv_Odemesi { get; set; }
        public Nullable<double> Artis { get; set; }
        public Nullable<int> Peryod { get; set; }
        public Nullable<double> Fiyat_Artis { get; set; }
        public Nullable<double> Acilis_fiyat { get; set; }
        public Nullable<int> Kdv_Tah1 { get; set; }
        public Nullable<int> Kdv_Tah2 { get; set; }
        public Nullable<int> Kdv_Tah3 { get; set; }
        public Nullable<int> Kdv_Tah4 { get; set; }
        public Nullable<int> Kdv_Tah5 { get; set; }
        public Nullable<int> Tah1 { get; set; }
        public Nullable<int> Tah2 { get; set; }
        public Nullable<int> Tah3 { get; set; }
        public Nullable<int> Tah4 { get; set; }
        public Nullable<int> Tah5 { get; set; }
    }
}
