//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class BTC_Personel_Giderleri
    {
        public int Butce_No { get; set; }
        public Nullable<double> Ay_Brut_Uc { get; set; }
        public Nullable<double> Saat_Uc { get; set; }
        public Nullable<double> Ay_Yem_Yar { get; set; }
        public Nullable<double> Ay_Tas_Yar { get; set; }
        public Nullable<double> Ay_San_Taz { get; set; }
        public Nullable<double> Yillik_Sem_Eg { get; set; }
        public Nullable<double> Yillik_EDO { get; set; }
        public Nullable<double> Yillik_Yak_Yar { get; set; }
        public Nullable<double> Ay_Coc_Yar { get; set; }
        public Nullable<double> Yillik_Giy_Kor_Yar { get; set; }
        public Nullable<double> Ay_Diger_Yar { get; set; }
        public Nullable<double> Sta_Uc { get; set; }
        public Nullable<double> Ikramiye { get; set; }
        public Nullable<double> Per_Say_Ocak { get; set; }
        public Nullable<double> Per_Say_Subat { get; set; }
        public Nullable<double> Per_Say_Mart { get; set; }
        public Nullable<double> Per_Say_Nisan { get; set; }
        public Nullable<double> Per_Say_Mayis { get; set; }
        public Nullable<double> Per_Say_Haziran { get; set; }
        public Nullable<double> Per_Say_Temmuz { get; set; }
        public Nullable<double> Per_Say_Agustos { get; set; }
        public Nullable<double> Per_Say_Eylul { get; set; }
        public Nullable<double> Per_Say_Ekim { get; set; }
        public Nullable<double> Per_Say_Kasim { get; set; }
        public Nullable<double> Per_Say_Aralik { get; set; }
        public int Gider_Tipi { get; set; }
        public int IptDrm { get; set; }
    }
}
