//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARI_Islemler
    {
        public int Cari_No { get; set; }
        public System.DateTime Islem_Zamani { get; set; }
        public string Aciklama { get; set; }
        public string Iliskili_Dosya_Tipi { get; set; }
        public string Iliskili_Dosya_Adi { get; set; }
    }
}
