//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARI_Stok_Tedarik
    {
        public int Cari_No { get; set; }
        public int Sira { get; set; }
        public Nullable<int> Stok_No { get; set; }
        public Nullable<int> Gun { get; set; }
        public Nullable<System.DateTime> SonZiyaret { get; set; }
        public Nullable<double> SonMiktar { get; set; }
        public Nullable<double> SonFiyat { get; set; }
    }
}
