//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARI_Fisler
    {
        public short Isyeri_Kodu { get; set; }
        public short Fis_Tipi { get; set; }
        public int Fis_No { get; set; }
        public short B_Isyeri_Kodu { get; set; }
        public short B_Fis_Tipi { get; set; }
        public int B_Fis_No { get; set; }
        public Nullable<byte> Fis_Durum { get; set; }
        public Nullable<byte> Kilit { get; set; }
        public Nullable<int> Cari_No { get; set; }
        public string Aciklama { get; set; }
        public Nullable<System.DateTime> Fis_Tarihi { get; set; }
        public string Belge_Tipi { get; set; }
        public string Belge_No { get; set; }
        public string Para_Birimi { get; set; }
        public string Acilis_User { get; set; }
        public string Update_User { get; set; }
        public string Iptal_User { get; set; }
        public Nullable<System.DateTime> Acilis_Zaman { get; set; }
        public Nullable<System.DateTime> Update_Zaman { get; set; }
        public Nullable<System.DateTime> Iptal_Zaman { get; set; }
    }
}
