//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARI_Bankalar
    {
        public int Cari_No { get; set; }
        public short Banka_SiraNo { get; set; }
        public string Banka_TCMB_Kodu { get; set; }
        public string Banka_Adi { get; set; }
        public string Banka_Subesi { get; set; }
        public string Banka_il { get; set; }
        public string Banka_ilce { get; set; }
        public string Banka_Hesap_No { get; set; }
        public string Hesap_ParaBirimi { get; set; }
        public Nullable<byte> Havale { get; set; }
        public string Banka_Kodu { get; set; }
        public string Banka_Sube_Kodu { get; set; }
        public string IBAN_No { get; set; }
    }
}
