//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARI_Toplam
    {
        public int Cari_No { get; set; }
        public short Yil { get; set; }
        public short Ay { get; set; }
        public string ParaBirim { get; set; }
        public Nullable<double> TBorc { get; set; }
        public Nullable<double> TAlacak { get; set; }
    }
}
