//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARI_Adresler
    {
        public int Cari_No { get; set; }
        public int Adres_SiraNo { get; set; }
        public string Yetkilisi { get; set; }
        public string Adresi { get; set; }
        public string Posta_Kodu { get; set; }
        public string Sehir { get; set; }
        public string Ulke { get; set; }
        public string Tel_Ulke_Kodu { get; set; }
        public string Tel_Bolge_Kodu { get; set; }
        public string Telefon1 { get; set; }
        public string Telefon2 { get; set; }
        public string Fax { get; set; }
        public string Modem { get; set; }
        public string E_Posta { get; set; }
        public Nullable<byte> Sevk_Adresi { get; set; }
        public Nullable<byte> Fat_Adresi { get; set; }
        public string Telefon3 { get; set; }
        public string Telefon4 { get; set; }
        public string Fax2 { get; set; }
        public Nullable<int> Fihr_KayitNo { get; set; }
    }
}
