//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARI_Yetkililer
    {
        public int Cari_No { get; set; }
        public short Yetkili_SiraNo { get; set; }
        public string AdiSoyadi { get; set; }
        public string Unvani { get; set; }
        public Nullable<short> Cinsiyeti { get; set; }
        public Nullable<short> Adres_SiraNo { get; set; }
        public string Dahili_Tel { get; set; }
        public string E_Posta { get; set; }
        public string Cep_Tel { get; set; }
        public string Web_Adresi { get; set; }
    }
}
