//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARI_Karti
    {
        public short IptDrm { get; set; }
        public int Cari_No { get; set; }
        public string Cari_Kodu { get; set; }
        public string Unvani { get; set; }
        public string Unvani2 { get; set; }
        public string VDaire { get; set; }
        public string VergiNo { get; set; }
        public Nullable<short> Durum { get; set; }
        public string Ana_Cari_No { get; set; }
        public string Temsilci_Kodu { get; set; }
        public string Grup_Kodu { get; set; }
        public string Ozel_Kodu { get; set; }
        public Nullable<short> Cari_Tipi { get; set; }
        public string Sektor_Kodu { get; set; }
        public string Bolge_Kodu { get; set; }
        public Nullable<short> Bolge_Sira { get; set; }
        public string ParaBirimi { get; set; }
        public Nullable<short> Kur_Hesaplama { get; set; }
        public string E_Posta_Adresi { get; set; }
        public string Internet_Adresi { get; set; }
        public Nullable<short> Kdv_Tipi { get; set; }
        public string Fiyat_Tipi { get; set; }
        public string Odm_Plan_No { get; set; }
        public Nullable<double> Iskonto_Orani { get; set; }
        public Nullable<double> VadeFarki_Orani { get; set; }
        public Nullable<short> Hesap_Kesim_Tipi { get; set; }
        public Nullable<short> Hesap_Kesim_Gunu { get; set; }
        public Nullable<System.DateTime> Son_Hesap_Kesim_Tarihi { get; set; }
        public Nullable<short> Siparis_Aralik_Tipi { get; set; }
        public Nullable<short> Siparis_Aralik_Gunu { get; set; }
        public Nullable<System.DateTime> Son_Siparis_Aralik_Tarihi { get; set; }
        public Nullable<short> Sirkuler_Islemi { get; set; }
        public string Muh_Kodu1 { get; set; }
        public string Muh_Kodu2 { get; set; }
        public Nullable<double> Kredi_Limiti { get; set; }
        public Nullable<double> Risk_Limiti { get; set; }
        public Nullable<double> Teminat_Tutari { get; set; }
        public string Yetki_Kodu { get; set; }
        public Nullable<double> Acik_Teminat { get; set; }
        public Nullable<double> Banka_Teminati { get; set; }
        public Nullable<double> Ipotek_Teminati { get; set; }
        public Nullable<double> Teminat_Ceki { get; set; }
        public Nullable<double> Teminat_Senedi { get; set; }
        public Nullable<double> Diger_Teminatlar { get; set; }
        public string Notlar { get; set; }
        public string Acilis_User { get; set; }
        public string Update_User { get; set; }
        public string Iptal_User { get; set; }
        public Nullable<System.DateTime> Acilis_Zaman { get; set; }
        public Nullable<System.DateTime> Update_Zaman { get; set; }
        public Nullable<System.DateTime> Iptal_Zaman { get; set; }
        public string Satc_Kodu { get; set; }
        public Nullable<double> Isk1 { get; set; }
        public Nullable<double> Isk2 { get; set; }
        public Nullable<double> Isk3 { get; set; }
        public Nullable<int> Vade_Gun { get; set; }
        public Nullable<System.DateTime> Vade_Tarih { get; set; }
        public string Satc_Kodu2 { get; set; }
        public Nullable<double> Isk4 { get; set; }
        public Nullable<double> Isk5 { get; set; }
        public Nullable<double> Isk6 { get; set; }
        public Nullable<double> Iskonto_OraniD { get; set; }
        public Nullable<System.DateTime> Vade_Tarihi2 { get; set; }
        public string Referanslar { get; set; }
        public string Web_Adresi { get; set; }
        public string Mail_Adresi { get; set; }
        public string Firma_SirkuNo { get; set; }
        public string Uretim_Konusu { get; set; }
        public string Calisma_Alani { get; set; }
        public string Odeme_Bilgisi { get; set; }
        public Nullable<System.DateTime> Mut_Tarihi { get; set; }
        public string Mut_Kisi { get; set; }
        public string Mut_Bilgi { get; set; }
        public string Mut_TutBilgi { get; set; }
        public Nullable<byte> Hesap_Tipi { get; set; }
        public Nullable<double> Iskonto_OraniE { get; set; }
        public Nullable<double> Iskonto_OraniB { get; set; }
        public Nullable<double> Isk7 { get; set; }
        public Nullable<double> Isk8 { get; set; }
        public Nullable<double> Isk9 { get; set; }
        public string Muh_Kodu3 { get; set; }
        public string Muh_Kodu4 { get; set; }
        public string Muh_Dvz1 { get; set; }
        public string Muh_Dvz2 { get; set; }
        public string Muh_Dvz3 { get; set; }
        public string Muh_Dvz4 { get; set; }
        public Nullable<short> DepoNo { get; set; }
        public Nullable<byte> Kilit { get; set; }
        public Nullable<byte> Kdv_TipiS { get; set; }
        public string Ozel_Kodu1 { get; set; }
        public string Ozel_Kodu2 { get; set; }
        public string Ozel_Kodu3 { get; set; }
        public string Ozel_Kodu4 { get; set; }
        public string Ozel_Kodu5 { get; set; }
        public string Ozel_Kodu6 { get; set; }
        public string Ozel_Kodu7 { get; set; }
        public string Ozel_Kodu8 { get; set; }
        public string Ozel_Kodu9 { get; set; }
        public string Ozel_Kodu10 { get; set; }
        public Nullable<System.DateTime> Periyod_BasTar { get; set; }
        public Nullable<int> Sipr_Periyodu { get; set; }
        public Nullable<byte> E_Fatura { get; set; }
        public Nullable<System.DateTime> E_Fat_BasTar { get; set; }
        public Nullable<byte> FF_Tipi { get; set; }
        public string Sube_Kodu { get; set; }
        public string Sube_Adi { get; set; }
        public Nullable<byte> Kdv_Kapsami { get; set; }
        public Nullable<byte> E_Irsaliye { get; set; }
        public string EIrsaliye_Pk_Mail { get; set; }
        public string EIrsaliye_Gb_Mail { get; set; }
        public Nullable<byte> E_Mutabakat { get; set; }
        public Nullable<byte> FF_Tipi2 { get; set; }
    }
}
