//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARI_Kimlik
    {
        public int Cari_No { get; set; }
        public byte IptDrm { get; set; }
        public string Seri_No { get; set; }
        public Nullable<System.DateTime> Dogum_Tarihi { get; set; }
        public string Baba_Adi { get; set; }
        public string Ana_Adi { get; set; }
        public string Dogum_Yeri { get; set; }
        public string il { get; set; }
        public string ilce { get; set; }
        public string Mahalle { get; set; }
        public string Koy { get; set; }
        public string Cilt_No { get; set; }
        public string Aile_No { get; set; }
        public string Sira_no { get; set; }
        public string TC_No { get; set; }
        public string SGK_No { get; set; }
        public string Adi { get; set; }
        public string Soyadi { get; set; }
        public Nullable<byte> Tevkifat { get; set; }
    }
}
