//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARI_Teminatlar
    {
        public int Cari_No { get; set; }
        public Nullable<double> Acik_Teminat { get; set; }
        public Nullable<double> Banka_Teminati { get; set; }
        public Nullable<double> Ipotek_Teminati { get; set; }
        public Nullable<double> Teminat_Ceki { get; set; }
        public Nullable<double> Teminat_Senedi { get; set; }
        public Nullable<double> Diger_Teminatlar { get; set; }
    }
}
