//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class CKSN_Pozisyon
    {
        public short CS_Tipi { get; set; }
        public short Poz_No { get; set; }
        public string Pozisyon_Adi { get; set; }
        public string Pozisyon_KAdi { get; set; }
        public Nullable<short> Kayit_Yonu { get; set; }
        public string Muh_Kodu { get; set; }
        public string Muh_Kodu1 { get; set; }
        public Nullable<byte> CB_Kayit { get; set; }
        public Nullable<byte> CB_Islem_Tipi { get; set; }
        public Nullable<byte> Muh_Kayit { get; set; }
        public Nullable<byte> Son_Tipi { get; set; }
        public Nullable<byte> Islem_Poz { get; set; }
    }
}
