//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class CKSN_Fis_Kalem
    {
        public short Fis_Durum { get; set; }
        public short Fis_Tipi { get; set; }
        public int Fis_No { get; set; }
        public int Fis_Portfoy { get; set; }
        public short Isyeri_Kodu { get; set; }
        public Nullable<int> Cari_No { get; set; }
        public Nullable<System.DateTime> Bordro_Tarihi { get; set; }
        public Nullable<System.DateTime> Giris_Tarihi { get; set; }
        public Nullable<System.DateTime> Vade_Tarihi { get; set; }
        public Nullable<short> Kendi_Ciro { get; set; }
        public string Sahibi { get; set; }
        public string Banka_Kodu { get; set; }
        public string CS_No { get; set; }
        public string Aciklama { get; set; }
        public string Para_Birimi { get; set; }
        public Nullable<double> Tutari { get; set; }
        public Nullable<double> Pul_Degeri { get; set; }
        public Nullable<double> Kur_Degeri { get; set; }
        public Nullable<double> Tutari1 { get; set; }
        public Nullable<double> Tutari2 { get; set; }
        public Nullable<short> Gun_Farki { get; set; }
        public Nullable<double> Adat_Degeri { get; set; }
        public Nullable<double> Faiz_Orani { get; set; }
        public string Satici_Kodu { get; set; }
        public Nullable<short> Son_Poz_Kodu { get; set; }
        public Nullable<System.DateTime> Son_Isl_Tarih { get; set; }
        public Nullable<int> Son_Fis_No { get; set; }
        public Nullable<short> Son_CB_Tipi { get; set; }
        public string Son_CB_Kodu { get; set; }
        public Nullable<byte> Sonuc_Onay { get; set; }
        public Nullable<double> POdenen { get; set; }
        public Nullable<double> POdenen1 { get; set; }
        public Nullable<double> POdenen2 { get; set; }
        public string VergiTc_No { get; set; }
    }
}
