//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class CKSN_Parcali
    {
        public short CS_Durum { get; set; }
        public short CS_Tipi { get; set; }
        public int CS_Fis_Sira { get; set; }
        public int CS_Portfoy { get; set; }
        public short Isyeri_Kodu { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public string Aciklama { get; set; }
        public string Para_Birimi { get; set; }
        public Nullable<double> Tutari { get; set; }
        public Nullable<double> Tutari1 { get; set; }
        public Nullable<double> Tutari2 { get; set; }
        public Nullable<double> Kur_Degeri1 { get; set; }
        public Nullable<double> Kur_Degeri2 { get; set; }
        public Nullable<int> Kasa_FisNo { get; set; }
        public string Kasa_Kodu { get; set; }
    }
}
