//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class CKSN_Fis_Kalem_Senet
    {
        public short Fis_Durum { get; set; }
        public short Fis_Tipi { get; set; }
        public int Fis_No { get; set; }
        public int Fis_Portfoy { get; set; }
        public short Isyeri_Kodu { get; set; }
        public string Asil_Adresi { get; set; }
        public string Asil_Tel_No { get; set; }
        public string Kefil_Adi { get; set; }
        public string Kefil_Adresi { get; set; }
        public string Kefil_Tel_No { get; set; }
    }
}
