//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class CKSN_Har_Kalem
    {
        public short Fis_Durum { get; set; }
        public short Fis_Tipi { get; set; }
        public int Fis_No { get; set; }
        public int Fis_Portfoy { get; set; }
        public short Isyeri_Kodu { get; set; }
        public string Aciklama { get; set; }
        public string Para_Birimi { get; set; }
        public Nullable<double> MasTutari { get; set; }
        public Nullable<double> Kur_Degeri { get; set; }
        public Nullable<double> MasTutari1 { get; set; }
        public Nullable<double> MasTutari2 { get; set; }
        public Nullable<short> Gun_Farki { get; set; }
        public Nullable<double> Adat_Degeri { get; set; }
        public Nullable<double> Faiz_Orani { get; set; }
        public Nullable<short> Onc_Poz_Kodu { get; set; }
        public Nullable<System.DateTime> Onc_Isl_Tarih { get; set; }
        public Nullable<int> Onc_Fis_No { get; set; }
        public Nullable<short> Onc_CB_Tipi { get; set; }
        public string Onc_CB_Kodu { get; set; }
        public Nullable<byte> Knt { get; set; }
    }
}
