//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class DGER_Fis_Kalem
    {
        public short Fis_Durum { get; set; }
        public short Fis_Tipi { get; set; }
        public int Fis_No { get; set; }
        public int Fis_Sira { get; set; }
        public short Isyeri_Kodu { get; set; }
        public Nullable<System.DateTime> Fis_Tarihi { get; set; }
        public Nullable<short> Kalem_Tipi { get; set; }
        public string Kodu { get; set; }
        public Nullable<double> Miktari { get; set; }
        public string Fiyat_Tipi { get; set; }
        public string Para_Birimi { get; set; }
        public Nullable<double> Kur_Degeri1 { get; set; }
        public Nullable<double> Kur_Degeri2 { get; set; }
        public Nullable<double> Birim_Fiyati { get; set; }
        public Nullable<short> KDV_Tipi { get; set; }
        public Nullable<short> Kdv_Orani { get; set; }
        public Nullable<double> IskOrani1 { get; set; }
        public Nullable<double> IskOrani2 { get; set; }
        public Nullable<double> IskOrani3 { get; set; }
        public Nullable<double> Tutari { get; set; }
        public Nullable<double> Tutari1 { get; set; }
        public Nullable<double> Tutari2 { get; set; }
        public Nullable<double> IskTutari { get; set; }
        public Nullable<double> IskTutari1 { get; set; }
        public Nullable<double> IskTutari2 { get; set; }
        public Nullable<double> KdvTutari { get; set; }
        public Nullable<double> Kom_Oran { get; set; }
        public string Siparis_Fis_No { get; set; }
        public string Referans_No { get; set; }
        public string Aciklama { get; set; }
        public string Ent_Kodu1 { get; set; }
    }
}
