//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENT_Kodlari
    {
        public short Ent_No { get; set; }
        public byte Ent_Tipi { get; set; }
        public string Ent_Adi { get; set; }
        public string Muh_Kodu { get; set; }
    }
}
