//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class Etiket_Basim
    {
        public int Isyeri_Kodu { get; set; }
        public int Fis_Tipi { get; set; }
        public int Fis_No { get; set; }
        public int Fis_Sira { get; set; }
        public int Stok_No { get; set; }
        public string Stok_Adi { get; set; }
        public Nullable<int> Miktar { get; set; }
        public Nullable<double> Fiyat { get; set; }
        public string Barkod { get; set; }
        public Nullable<System.DateTime> Fis_Tarihi { get; set; }
    }
}
