//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fason_Islemler
    {
        public byte Isyeri_Kodu { get; set; }
        public byte Fis_Tipi { get; set; }
        public int Fis_No { get; set; }
        public int Fis_Sira { get; set; }
        public byte Fis_Durum { get; set; }
        public byte Fis_Sira1 { get; set; }
        public Nullable<int> Cari_No { get; set; }
        public Nullable<int> FS_C_Isyeri { get; set; }
        public Nullable<int> FS_C_Fis_No { get; set; }
        public string FS_C_Parti_No { get; set; }
        public Nullable<System.DateTime> Must_Termin { get; set; }
        public Nullable<System.DateTime> Fason_Termin { get; set; }
        public Nullable<double> Olcu1 { get; set; }
        public Nullable<double> Olcu2 { get; set; }
        public Nullable<double> Olcu3 { get; set; }
        public Nullable<double> Gramaj1 { get; set; }
        public Nullable<double> Gramaj2 { get; set; }
        public string Renk_Kodu { get; set; }
        public Nullable<double> Must_Miktar { get; set; }
        public Nullable<double> Acilan_Miktar { get; set; }
        public Nullable<byte> Tmm_Islem_No { get; set; }
        public Nullable<int> FS_G_Isyeri { get; set; }
        public Nullable<int> FS_G_Fis_No { get; set; }
        public Nullable<double> Gelen_Miktar { get; set; }
        public Nullable<double> K2_Miktar { get; set; }
        public Nullable<double> K3_Miktar { get; set; }
        public Nullable<double> Fire_Miktar { get; set; }
    }
}
