//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class FATR_Irsaliye
    {
        public short Fat_Fis_Tipi { get; set; }
        public int Fat_Fis_No { get; set; }
        public short Isyeri_Kodu { get; set; }
        public short Irs_Fis_Tipi { get; set; }
        public int Irs_Fis_No { get; set; }
        public short Irs_Sira_No { get; set; }
        public Nullable<double> Irs_Kul_Miktar { get; set; }
        public Nullable<byte> Fis_Durum { get; set; }
        public short Irs_Isyeri { get; set; }
    }
}
