//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class FATR_Odeme_Detay
    {
        public short Isyeri_Kodu { get; set; }
        public short Fis_Tipi { get; set; }
        public int Fis_No { get; set; }
        public short Fis_Sira { get; set; }
        public Nullable<byte> OdeTipi { get; set; }
        public string OdeKodu { get; set; }
        public Nullable<double> OdeTutari { get; set; }
        public Nullable<System.DateTime> OdeVadesi { get; set; }
        public Nullable<int> Fis_Portfoy { get; set; }
        public string CS_No { get; set; }
        public Nullable<byte> KendiCiro { get; set; }
        public string Banka_Adi { get; set; }
        public string Aciklama { get; set; }
    }
}
