//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class FATR_GeriDonusler
    {
        public short Isyeri_Kodu { get; set; }
        public short Fis_Tipi { get; set; }
        public int Fis_No { get; set; }
        public short Fis_Sira { get; set; }
        public short Tip { get; set; }
        public Nullable<int> Cari_No { get; set; }
        public Nullable<double> Tutari { get; set; }
        public Nullable<short> IIsyeri_Kodu { get; set; }
        public Nullable<short> IFis_Tipi { get; set; }
        public Nullable<int> IFis_No { get; set; }
        public Nullable<byte> Secim { get; set; }
        public Nullable<byte> DonemTipi { get; set; }
        public Nullable<byte> DonemAyi { get; set; }
        public Nullable<double> Ciro { get; set; }
        public string Aciklama { get; set; }
    }
}
