//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class FATR_FFarki_Detay
    {
        public short Isyeri_Kodu { get; set; }
        public short Fis_Tipi { get; set; }
        public int Fis_No { get; set; }
        public short Fis_Sira { get; set; }
        public string FFHizKodu { get; set; }
        public Nullable<double> FFKdvOrn { get; set; }
        public Nullable<double> FFMiktari { get; set; }
        public Nullable<double> FFFiyati { get; set; }
        public Nullable<double> FFTutari { get; set; }
        public Nullable<double> FFKdvDeg { get; set; }
        public string FFAciklama { get; set; }
        public Nullable<int> Stok_No { get; set; }
    }
}
