//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fis_Tipleri
    {
        public int FisTipiNo { get; set; }
        public string FisTipiAdi { get; set; }
        public string FisTipiKAdi { get; set; }
    }
}
