//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class FIYT_Fis_Kalem
    {
        public short Fis_Durum { get; set; }
        public short Isyeri_Kodu { get; set; }
        public byte Fis_Tipi { get; set; }
        public int Fis_No { get; set; }
        public int Fis_Sira { get; set; }
        public Nullable<int> Stok_No { get; set; }
        public string Fiyat_Tipi { get; set; }
        public Nullable<double> E_Fiyati { get; set; }
        public Nullable<double> Y_Fiyati { get; set; }
        public string Para_Birimi { get; set; }
        public Nullable<double> A_Fiyati { get; set; }
        public Nullable<float> KarOrn { get; set; }
        public Nullable<float> KdvT { get; set; }
        public Nullable<float> KdvP { get; set; }
        public Nullable<double> P_Fiyati { get; set; }
        public Nullable<double> Isk1 { get; set; }
        public Nullable<int> GD_Cari_No { get; set; }
        public Nullable<double> GD_Tutari { get; set; }
        public Nullable<double> E_TPFiyati { get; set; }
        public Nullable<double> Y_TPFiyati { get; set; }
        public Nullable<double> E_TVFiyati { get; set; }
        public Nullable<double> Y_TVFiyati { get; set; }
        public Nullable<double> E_B2Fiyati { get; set; }
        public Nullable<double> Y_B2Fiyati { get; set; }
        public Nullable<double> E_B3Fiyati { get; set; }
        public Nullable<double> Y_B3Fiyati { get; set; }
    }
}
