//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class HIZM_Referans1
    {
        public string RefKodu1 { get; set; }
        public byte IptDrm { get; set; }
        public string Ref1Aciklama1 { get; set; }
        public string Ref1Aciklama2 { get; set; }
    }
}
