//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class HIZM_Referans2
    {
        public string RefKodu1 { get; set; }
        public string RefKodu2 { get; set; }
        public byte IptDrm { get; set; }
        public string Ref2Aciklama1 { get; set; }
        public string Ref2Aciklama2 { get; set; }
        public string Ref2Ilgili { get; set; }
        public Nullable<double> Ref2Miktar { get; set; }
        public string Ref2IslKodu { get; set; }
        public Nullable<System.DateTime> Ref2Tarih1 { get; set; }
        public Nullable<System.DateTime> Ref2Tarih2 { get; set; }
    }
}
