//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class IRSL_Baslik
    {
        public short Fis_Durum { get; set; }
        public short Fis_Tipi { get; set; }
        public int Fis_No { get; set; }
        public short Isyeri_Kodu { get; set; }
        public Nullable<byte> Kilit { get; set; }
        public Nullable<byte> Secim { get; set; }
        public Nullable<System.DateTime> Fis_Tarihi { get; set; }
        public Nullable<short> Depo_Kodu { get; set; }
        public string Kasa_Kodu { get; set; }
        public Nullable<int> Cari_No { get; set; }
        public string Belge_No { get; set; }
        public Nullable<System.DateTime> Belge_Tarihi { get; set; }
        public string Fat_No { get; set; }
        public Nullable<byte> Cari_Kayit { get; set; }
        public Nullable<byte> Kasa_Kayit { get; set; }
        public Nullable<short> Islem_Tipi1 { get; set; }
        public Nullable<short> Islem_Tipi2 { get; set; }
        public Nullable<int> Kdv_Tipi1 { get; set; }
        public Nullable<int> Kdv_Tipi2 { get; set; }
        public Nullable<short> EkV_Tipi { get; set; }
        public Nullable<short> EkV_Orani { get; set; }
        public string Fiyat_Tipi { get; set; }
        public Nullable<short> Maliyet_Tipi { get; set; }
        public Nullable<short> Odeme_Tipi { get; set; }
        public string Odeme_Kodu { get; set; }
        public Nullable<short> Odeme_Sekli { get; set; }
        public Nullable<System.DateTime> Odeme_Vadesi { get; set; }
        public Nullable<short> Isk_Hesap_Sekli { get; set; }
        public Nullable<short> Isk_Hesap_Tipi { get; set; }
        public Nullable<short> Isk_Kademe_Tipi { get; set; }
        public string Para_Birimi { get; set; }
        public Nullable<double> Kur_Degeri { get; set; }
        public Nullable<double> TopDeger1 { get; set; }
        public Nullable<double> TopDeger2 { get; set; }
        public Nullable<double> TopIskonto1 { get; set; }
        public Nullable<double> TopIskonto2 { get; set; }
        public Nullable<double> TopMasraf1 { get; set; }
        public Nullable<double> TopMasraf2 { get; set; }
        public Nullable<double> ToplamKdv { get; set; }
        public Nullable<double> ToplamEkV { get; set; }
        public Nullable<double> NetTutar1 { get; set; }
        public Nullable<double> NetTutar2 { get; set; }
        public string Ilgili_Kisi { get; set; }
        public string Aciklama { get; set; }
        public string Yetki_Kodu { get; set; }
        public string Ozel_Kodu { get; set; }
        public string Odeme_Plani { get; set; }
        public string Satici_Kodu1 { get; set; }
        public string Satici_Kodu2 { get; set; }
        public string Ent_Kodu1 { get; set; }
        public Nullable<short> Ent_Fis_Tipi1 { get; set; }
        public Nullable<int> Ent_Fis_No1 { get; set; }
        public string Ent_Kodu2 { get; set; }
        public Nullable<short> Ent_Fis_Tipi2 { get; set; }
        public Nullable<int> Ent_Fis_No2 { get; set; }
        public string Acilis_User { get; set; }
        public string Update_User { get; set; }
        public string Iptal_User { get; set; }
        public Nullable<System.DateTime> Acilis_Zaman { get; set; }
        public Nullable<System.DateTime> Update_Zaman { get; set; }
        public Nullable<System.DateTime> Iptal_Zaman { get; set; }
        public Nullable<System.DateTime> Vade_Tarihi { get; set; }
        public Nullable<int> Alan_Depo { get; set; }
        public Nullable<int> Sirkuler_No { get; set; }
        public string OzelParaBirimi { get; set; }
        public Nullable<double> OzelIslem_Kuru { get; set; }
        public Nullable<short> Iade_FisTipi { get; set; }
        public Nullable<int> Iade_FisNo { get; set; }
        public Nullable<int> K_Sip_No { get; set; }
        public Nullable<int> Sip_No { get; set; }
        public Nullable<int> Paket_Sayisi { get; set; }
        public string Paket_Aciklama { get; set; }
        public Nullable<double> GIskOrn1 { get; set; }
        public Nullable<double> GIskOrn2 { get; set; }
        public Nullable<double> GIskOrn3 { get; set; }
        public Nullable<double> GIskTut1 { get; set; }
        public Nullable<double> GIskTut2 { get; set; }
        public Nullable<double> GIskTut3 { get; set; }
        public Nullable<double> GIskTop { get; set; }
        public string Belge_Tipi { get; set; }
        public string Masraf_Yeri { get; set; }
        public Nullable<byte> Adres_SiraNo { get; set; }
        public string Sirku_Nolar { get; set; }
        public string OzelParaBirimi2 { get; set; }
        public Nullable<double> OzelIslem_Kuru2 { get; set; }
        public Nullable<double> OzelCapraz_Kur { get; set; }
        public Nullable<byte> Kontrol_Kodu { get; set; }
        public Nullable<byte> Alindi_Onayi { get; set; }
        public Nullable<int> Iade_Nedeni { get; set; }
        public string KK_Degerlendirme { get; set; }
        public string Onay_User { get; set; }
        public Nullable<System.DateTime> Onay_Zaman { get; set; }
        public string E_Irsaliye_Guid { get; set; }
        public string E_Irsaliye_Zarf_Guid { get; set; }
        public Nullable<byte> E_Irsaliye_Onay { get; set; }
        public string E_Irsaliye_Tipi { get; set; }
        public string Arac_Plaka_No { get; set; }
        public string Sofor_Adi { get; set; }
        public string Sofor_SoyAdi { get; set; }
        public string Sofor_Tc_Kimlik_No { get; set; }
        public Nullable<int> Nak_Cari_No { get; set; }
        public Nullable<long> E_Irsaliye_FisNo { get; set; }
        public string E_Irsaliye_Dosya { get; set; }
    }
}
