//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITH_Sozlesme
    {
        public byte IptDrm { get; set; }
        public int Sozlesme_No { get; set; }
        public int Cari_No { get; set; }
        public string Sozlesme_Kodu { get; set; }
        public Nullable<System.DateTime> Soz_Tarihi { get; set; }
        public Nullable<byte> Odeme_Sekli { get; set; }
        public Nullable<byte> Teslim_Sekli { get; set; }
        public string Odeme_Detayi { get; set; }
        public Nullable<System.DateTime> Yukleme_Tarihi { get; set; }
        public string Yuklendigi_Yer { get; set; }
        public string Teslim_Yeri { get; set; }
        public string Para_Birimi { get; set; }
        public Nullable<double> Toplam_Tutar { get; set; }
    }
}
