//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITH_Sevkiyat
    {
        public byte IptDrm { get; set; }
        public int Sozlesme_No { get; set; }
        public short Sevk_No { get; set; }
        public Nullable<int> Nakliye_No { get; set; }
        public string Sevk_Yeri { get; set; }
        public Nullable<System.DateTime> Sevk_Tarihi { get; set; }
        public Nullable<double> Sevk_Miktari { get; set; }
        public Nullable<double> Sevk_KontSayisi { get; set; }
        public string Sevk_KontTipi { get; set; }
        public string Aciklama { get; set; }
        public string Konteyner_No { get; set; }
        public string Tasit_Adi { get; set; }
        public string Tasit_Sefer_No { get; set; }
        public string Tir_Plaka { get; set; }
        public Nullable<System.DateTime> Yukleme_Tarihi { get; set; }
        public Nullable<System.DateTime> Tahmini_Varis_Tarihi { get; set; }
        public string Sigorta_Sirketi { get; set; }
        public string Police_No { get; set; }
        public Nullable<System.DateTime> Sigorta_Tarihi { get; set; }
        public string Para_Birimi { get; set; }
        public Nullable<double> Tutari { get; set; }
        public Nullable<double> Navlun_Tutari { get; set; }
        public Nullable<int> Onay { get; set; }
        public Nullable<System.DateTime> Fiili_Varis_Tarihi { get; set; }
        public Nullable<int> Etap_Sayisi { get; set; }
    }
}
