//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITH_Sozlesme_Kalem_Sevk
    {
        public byte IptDrm { get; set; }
        public int Sozlesme_No { get; set; }
        public short Sira_No { get; set; }
        public short Sevk_No { get; set; }
        public Nullable<double> Miktari { get; set; }
        public Nullable<double> Tutar { get; set; }
    }
}
