//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class KAMP_Fis_Baslik
    {
        public short Fis_Tipi { get; set; }
        public short Isyeri_Kodu { get; set; }
        public int Fis_No { get; set; }
        public Nullable<System.DateTime> Fis_Tarihi { get; set; }
        public string Referans { get; set; }
        public Nullable<System.DateTime> Baslangic_Zaman { get; set; }
        public Nullable<System.DateTime> Bitis_Zaman { get; set; }
    }
}
