//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class KAMP_Fis_Kalem
    {
        public short Fis_Tipi { get; set; }
        public short Isyeri_Kodu { get; set; }
        public int Fis_No { get; set; }
        public short Sira { get; set; }
        public Nullable<int> Stok_No { get; set; }
        public Nullable<double> Onceki_Fiyati { get; set; }
        public Nullable<double> Kamp_Fiyati { get; set; }
        public Nullable<double> Onceki_Iskonto_Orani { get; set; }
        public Nullable<double> Kamp_Iskonto_Orani { get; set; }
        public Nullable<double> Satis_Adedi { get; set; }
        public Nullable<double> Kamp_Iskonto_Adedi { get; set; }
    }
}
