//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class KASA_Fis_Baslik
    {
        public short Fis_Durum { get; set; }
        public short Fis_Tipi { get; set; }
        public int Fis_No { get; set; }
        public short Isyeri_Kodu { get; set; }
        public Nullable<System.DateTime> Fis_Tarihi { get; set; }
        public Nullable<byte> Kilit { get; set; }
        public string Kasa_Kodu { get; set; }
        public Nullable<byte> Cari_Kayit { get; set; }
        public Nullable<byte> Kasa_Kayit { get; set; }
        public string Aciklama { get; set; }
        public string Para_Birimi { get; set; }
        public Nullable<double> Kur_Degeri { get; set; }
        public Nullable<double> TopBorc1 { get; set; }
        public Nullable<double> TopBorc2 { get; set; }
        public Nullable<double> TopAlck1 { get; set; }
        public Nullable<double> TopAlck2 { get; set; }
        public string Yetki_Kodu { get; set; }
        public string Ozel_Kodu { get; set; }
        public string Acilis_User { get; set; }
        public string Update_User { get; set; }
        public string Iptal_User { get; set; }
        public Nullable<System.DateTime> Acilis_Zaman { get; set; }
        public Nullable<System.DateTime> Update_Zaman { get; set; }
        public Nullable<System.DateTime> Iptal_Zaman { get; set; }
        public string Ent_Kodu1 { get; set; }
        public Nullable<short> Ent_Fis_Tipi1 { get; set; }
        public Nullable<int> Ent_Fis_No1 { get; set; }
        public string Ent_Kodu2 { get; set; }
        public Nullable<short> Ent_Fis_Tipi2 { get; set; }
        public Nullable<int> Ent_Fis_No2 { get; set; }
        public string OzelParaBirimi { get; set; }
        public Nullable<double> OzelIslem_Kuru { get; set; }
        public string Ilgili1 { get; set; }
        public string Ilgili2 { get; set; }
        public string Belge_Tipi { get; set; }
        public string Belge_No { get; set; }
        public Nullable<System.DateTime> Belge_Tarihi { get; set; }
        public string Masraf_Yeri { get; set; }
        public Nullable<byte> MuhEnt_Acik { get; set; }
        public string OzelParaBirimi2 { get; set; }
        public Nullable<double> OzelIslem_Kuru2 { get; set; }
        public Nullable<double> OzelCapraz_Kur { get; set; }
        public Nullable<byte> Kontrol_Kodu { get; set; }
        public string Onay_User { get; set; }
        public Nullable<System.DateTime> Onay_Zaman { get; set; }
    }
}
