//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class KASA_Karti
    {
        public string Kasa_Kodu { get; set; }
        public string Kasa_Adi { get; set; }
        public string Yetkilisi { get; set; }
        public Nullable<short> Isyeri_Kodu { get; set; }
        public string Para_Birimi { get; set; }
        public string Muh_Kodu1 { get; set; }
        public string Muh_Kodu2 { get; set; }
        public string Ozel_Kodu { get; set; }
        public string Yetki_Kodu { get; set; }
        public string Acilis_User { get; set; }
        public string Update_User { get; set; }
        public Nullable<System.DateTime> Acilis_Zaman { get; set; }
        public Nullable<System.DateTime> Update_Zaman { get; set; }
    }
}
