//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kdv_Oranlar
    {
        public byte Kdv_Oran { get; set; }
        public string Muh_Kodu_Alis { get; set; }
        public string Muh_Kodu_Satis { get; set; }
        public string Muh_Kodu_AIade { get; set; }
        public string Muh_Kodu_SIade { get; set; }
        public string Muh_Kodu_Diger { get; set; }
        public string FF_Hizmet_Kodu { get; set; }
    }
}
