//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class KKART_Fis_Detay
    {
        public short Isyeri_Kodu { get; set; }
        public short Fis_Tipi { get; set; }
        public int Fis_No { get; set; }
        public int Fis_Sira { get; set; }
        public int Sira { get; set; }
        public Nullable<short> Fis_Durum { get; set; }
        public string KK_Kodu { get; set; }
        public Nullable<double> BorcTutari { get; set; }
        public Nullable<System.DateTime> Vade_Tarihi { get; set; }
        public Nullable<System.DateTime> Hesap_Kesim_Tarihi { get; set; }
    }
}
