//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class KKART_Fis_Kalem
    {
        public short Isyeri_Kodu { get; set; }
        public short Fis_Tipi { get; set; }
        public int Fis_No { get; set; }
        public int Fis_Sira { get; set; }
        public Nullable<short> Fis_Durum { get; set; }
        public Nullable<System.DateTime> Fis_Tarihi { get; set; }
        public string KK_Kodu { get; set; }
        public Nullable<int> Cari_No { get; set; }
        public string Cari_Kodu { get; set; }
        public string Belge_Tipi { get; set; }
        public Nullable<int> Belge_FisNo { get; set; }
        public string Belge_No { get; set; }
        public Nullable<short> Islem_Tipi { get; set; }
        public string Aciklama { get; set; }
        public string Para_Birimi { get; set; }
        public Nullable<double> Kur_Degeri1 { get; set; }
        public Nullable<double> Kur_Degeri2 { get; set; }
        public Nullable<double> Kur_DegeriP { get; set; }
        public Nullable<double> BorcTutari { get; set; }
        public Nullable<double> BorcTutari1 { get; set; }
        public Nullable<double> BorcTutari2 { get; set; }
        public Nullable<double> BorcTutariP { get; set; }
        public Nullable<double> BorcPPuan { get; set; }
        public Nullable<double> AlckTutari { get; set; }
        public Nullable<double> AlckTutari1 { get; set; }
        public Nullable<double> AlckTutari2 { get; set; }
        public Nullable<double> AlckTutariP { get; set; }
        public Nullable<double> AlckPPuan { get; set; }
        public Nullable<System.DateTime> Vade_Tarihi { get; set; }
        public string Ent_Kodu1 { get; set; }
        public string Mas_Kodu1 { get; set; }
        public string Hiz_Kodu1 { get; set; }
        public string Kasa_Kodu { get; set; }
        public string Masraf_Yeri { get; set; }
        public Nullable<byte> Ode_Yeri { get; set; }
        public string Ode_Kodu { get; set; }
        public Nullable<short> Ode_Fis_Isy { get; set; }
        public Nullable<short> Ode_Fis_Tipi { get; set; }
        public Nullable<int> Ode_Fis_No { get; set; }
        public Nullable<int> Taksit_Sayisi { get; set; }
        public Nullable<double> Taksit_Tutari { get; set; }
        public Nullable<int> Hesap_Kesim_Tarihi { get; set; }
    }
}
