//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class KKART_Karti
    {
        public string KK_Kodu { get; set; }
        public string KK_KartNo { get; set; }
        public string KK_Tanimi { get; set; }
        public string KK_Gec_AyYil { get; set; }
        public string KK_ParaBirimi { get; set; }
        public string KK_Banka_Kodu { get; set; }
        public string KK_Sahibi { get; set; }
        public Nullable<short> KK_Odeme_Gunu { get; set; }
        public Nullable<short> KK_Kesim_Gunu { get; set; }
        public Nullable<double> KK_Kredi_Limiti { get; set; }
        public string KK_Muh_Kodu1 { get; set; }
        public string KK_Muh_Kodu2 { get; set; }
    }
}
