//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class KPOS_Fatura
    {
        public short Isyeri_Kodu { get; set; }
        public byte Fis_Tipi { get; set; }
        public int Fis_No { get; set; }
        public System.DateTime Fis_Tarihi { get; set; }
        public int Fatura_No { get; set; }
        public Nullable<int> CARI_No { get; set; }
        public Nullable<double> Fatura_Tutari { get; set; }
    }
}
