//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class KPOS_KASA_Fis_Baslik
    {
        public byte Fis_Durum { get; set; }
        public short Fis_Tipi { get; set; }
        public short Fis_No { get; set; }
        public short Isyeri_Kodu { get; set; }
        public Nullable<System.DateTime> Fis_Tarihi { get; set; }
        public string Kasa_Kodu { get; set; }
        public string Aciklama { get; set; }
        public string Para_Birimi { get; set; }
        public Nullable<double> TopBorc1 { get; set; }
        public Nullable<double> TopBorc2 { get; set; }
        public Nullable<double> TopBorc3 { get; set; }
        public Nullable<double> TopAlck1 { get; set; }
        public Nullable<double> Topalck2 { get; set; }
        public Nullable<double> TopAlck3 { get; set; }
        public string Teslim_Alan { get; set; }
        public string Acilis_User { get; set; }
        public string Update_User { get; set; }
        public string Iptal_User { get; set; }
        public Nullable<System.DateTime> Acilis_Zaman { get; set; }
        public Nullable<System.DateTime> Iptal_Zaman { get; set; }
        public Nullable<System.DateTime> Update_Zaman { get; set; }
    }
}
