//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class KPOS_Kasa_Odemeleri
    {
        public short Isyeri_Kodu { get; set; }
        public byte Fis_Tipi { get; set; }
        public int Fis_No { get; set; }
        public byte Odm_Tipi { get; set; }
        public Nullable<double> Odm_Tutar { get; set; }
        public Nullable<double> Odm_Tutar2 { get; set; }
        public Nullable<byte> Kayit_Yeri { get; set; }
        public string Kayit_Kodu { get; set; }
    }
}
