//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class KPOS_Kasa_Odeme_Param
    {
        public short Isyeri_Kodu { get; set; }
        public string Kasa_Kodu { get; set; }
        public byte Odm_Tipi { get; set; }
        public byte Tus_No { get; set; }
        public Nullable<byte> Kayit_Yeri { get; set; }
        public string Kayit_Kodu { get; set; }
    }
}
