//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class KPOS_Kasa_Plu
    {
        public short Isyeri_Kodu { get; set; }
        public short Kasa_No { get; set; }
        public short Kasa_PluNo { get; set; }
        public Nullable<int> Stok_No { get; set; }
        public string Barkod { get; set; }
        public string Resim { get; set; }
        public Nullable<int> Grup_No { get; set; }
    }
}
