//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class KPOS_Kasa_Karti
    {
        public short Isyeri_Kodu { get; set; }
        public string Kasa_Kodu { get; set; }
        public string Adi { get; set; }
        public Nullable<byte> Ust_Urun_Kodu { get; set; }
        public Nullable<byte> Pos_Satis_Tipi { get; set; }
        public Nullable<byte> Yzc_Prog_Kodu1 { get; set; }
        public string Yzc_Prog_Kodu2 { get; set; }
        public Nullable<byte> Cek_Prog_Kodu { get; set; }
        public Nullable<byte> Gos_Prog_Kodu { get; set; }
        public Nullable<byte> Mali_Bellek_Kodu { get; set; }
        public Nullable<byte> Pos_Mesaj_Kodu { get; set; }
        public string Odeme_Param1 { get; set; }
        public string Odeme_Param2 { get; set; }
        public string Odeme_Param3 { get; set; }
        public string Odeme_Param4 { get; set; }
        public string Odeme_Param5 { get; set; }
        public string Odeme_Param6 { get; set; }
        public string Odeme_Param7 { get; set; }
        public string Odeme_Param8 { get; set; }
        public Nullable<byte> Kasa_Tipi { get; set; }
        public string Kasa_SeriNo { get; set; }
        public string Kasa_IPNo { get; set; }
    }
}
