//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class KPOS_Kasa_ZDetay
    {
        public short Isyeri_Kodu { get; set; }
        public byte Fis_Tipi { get; set; }
        public int Fis_No { get; set; }
        public byte Dep_No { get; set; }
        public Nullable<double> Dep_Tut { get; set; }
        public Nullable<double> Kdv_Orn { get; set; }
        public Nullable<double> Kdv_Tut { get; set; }
        public Nullable<double> Dep_Tut2 { get; set; }
        public Nullable<double> Kdv_Tut2 { get; set; }
    }
}
