//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class KPOS_KASA_Fis_Kalem
    {
        public byte Fis_Durum { get; set; }
        public short Fis_Tipi { get; set; }
        public short Fis_No { get; set; }
        public short Fis_Sira { get; set; }
        public short Isyeri_Kodu { get; set; }
        public Nullable<System.DateTime> Fis_Tarihi { get; set; }
        public string Kasa_Kodu { get; set; }
        public string Kasiyer_Kodu { get; set; }
        public string Kasiyer_Adi { get; set; }
        public string Odeme_Tipi { get; set; }
        public string Para_Birimi { get; set; }
        public string Aciklama { get; set; }
        public Nullable<double> BorcTutari { get; set; }
        public Nullable<double> BorcTutari1 { get; set; }
        public Nullable<double> BorcTutari2 { get; set; }
        public Nullable<double> AlckTutari { get; set; }
        public Nullable<double> AlckTutari1 { get; set; }
        public Nullable<double> AlckTutari2 { get; set; }
    }
}
