//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class KPOS_Departman
    {
        public short Isyeri_Kodu { get; set; }
        public byte Fis_Tipi { get; set; }
        public int Fis_No { get; set; }
        public byte Dep_No { get; set; }
        public Nullable<byte> Fis_Durum { get; set; }
        public Nullable<double> KDV_Matrah { get; set; }
        public Nullable<double> KDV_Tutar { get; set; }
    }
}
