//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class KPOS_Kasa_Islem
    {
        public short Isyeri_Kodu { get; set; }
        public byte Fis_Tipi { get; set; }
        public int Fis_No { get; set; }
        public Nullable<byte> Fis_Durum { get; set; }
        public Nullable<System.DateTime> Fis_Tarihi { get; set; }
        public Nullable<short> PKasa_Kodu { get; set; }
        public Nullable<short> Kasiyer_Kodu { get; set; }
        public string Kasa_Kodu { get; set; }
        public string Belge_No { get; set; }
        public string Aciklama { get; set; }
        public Nullable<double> FisNakit { get; set; }
        public Nullable<double> FisKredi { get; set; }
        public Nullable<double> FatNakit { get; set; }
        public Nullable<double> FatKredi { get; set; }
        public Nullable<double> SatToplam { get; set; }
        public Nullable<double> GunNakitTeslim { get; set; }
        public Nullable<double> SonNakitTeslim { get; set; }
        public Nullable<double> TeslimFarki { get; set; }
        public string Kasa_Kodu2 { get; set; }
        public Nullable<int> ZNo { get; set; }
        public Nullable<double> KasaDigerTahsilat { get; set; }
        public Nullable<double> FMatikTahsilat { get; set; }
        public Nullable<double> KasaDigerOdeme { get; set; }
        public Nullable<double> KasaDevir { get; set; }
        public Nullable<double> KasaDevreden { get; set; }
    }
}
