//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class KPOS_Kasiyer_Karti
    {
        public short Isyeri_kodu { get; set; }
        public string Kasiyer_Kodu { get; set; }
        public string Adi { get; set; }
        public string Sifresi { get; set; }
        public string Adresi { get; set; }
        public string Telefonu { get; set; }
        public Nullable<byte> Ust_Urun_Kodu { get; set; }
        public Nullable<byte> Data_Kodu { get; set; }
        public string Grup_Kodu { get; set; }
        public string Ozel_Kodu { get; set; }
        public Nullable<byte> Islem_Yetki { get; set; }
        public Nullable<byte> Iskonto_Yetki { get; set; }
        public string Path_Alani { get; set; }
        public Nullable<short> Dosya_Sirasi { get; set; }
        public string Yetkiler { get; set; }
        public Nullable<double> Iskonto_Oran { get; set; }
        public Nullable<int> Must_No { get; set; }
    }
}
