//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class KREDI_Taksit
    {
        public string Kredi_Kodu { get; set; }
        public int Taksit_No { get; set; }
        public Nullable<short> Fis_Durum { get; set; }
        public Nullable<System.DateTime> Fis_Tarihi { get; set; }
        public Nullable<System.DateTime> Vade_Tarihi { get; set; }
        public Nullable<double> Taksit_Tutari { get; set; }
        public Nullable<double> Ana_Para { get; set; }
        public Nullable<double> Faiz_Tutari { get; set; }
        public Nullable<double> Vergi_Tutari { get; set; }
        public Nullable<double> Kdv_Tutari { get; set; }
        public Nullable<double> Bakiye { get; set; }
        public Nullable<double> KKDF_Tutari { get; set; }
    }
}
