//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class KREDI_Fis_Kalem
    {
        public short Isyeri_Kodu { get; set; }
        public short Fis_Tipi { get; set; }
        public int Fis_No { get; set; }
        public string Kredi_Kodu { get; set; }
        public int Taksit_No { get; set; }
        public Nullable<short> Fis_Durum { get; set; }
        public Nullable<System.DateTime> Fis_Tarihi { get; set; }
        public Nullable<System.DateTime> Vade_Tarihi { get; set; }
        public string Banka_Kodu { get; set; }
        public string Kasa_Kodu { get; set; }
        public string Para_Birimi { get; set; }
        public Nullable<double> ATutari { get; set; }
        public Nullable<double> ATutari1 { get; set; }
        public Nullable<double> ATutari2 { get; set; }
        public Nullable<double> OTutari { get; set; }
        public Nullable<double> OTutari1 { get; set; }
        public Nullable<double> OTutari2 { get; set; }
        public Nullable<double> Ana_Para { get; set; }
        public Nullable<double> Faiz_Tutari { get; set; }
        public Nullable<double> Vergi_Tutari { get; set; }
        public Nullable<double> Kdv_Tutari { get; set; }
        public string Mevduat_Banka_Kodu { get; set; }
        public string Cari_Kodu { get; set; }
    }
}
