//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class KREDI_Karti
    {
        public string Kredi_Kodu { get; set; }
        public Nullable<short> IptDrm { get; set; }
        public string Kredi_Tanimi { get; set; }
        public Nullable<short> Kredi_Tipi { get; set; }
        public Nullable<short> Kredi_Hesap_Tipi { get; set; }
        public Nullable<double> Kredi_Tutari { get; set; }
        public string Para_Birimi { get; set; }
        public Nullable<System.DateTime> Ilk_Taksit { get; set; }
        public Nullable<double> Vergi_Orani { get; set; }
        public Nullable<double> Faiz_Orani { get; set; }
        public Nullable<double> Kdv_Orani { get; set; }
        public string Acilis_User { get; set; }
        public string Update_User { get; set; }
        public string Iptal_User { get; set; }
        public Nullable<System.DateTime> Acilis_Zaman { get; set; }
        public Nullable<System.DateTime> Update_Zaman { get; set; }
        public Nullable<System.DateTime> Iptal_Zaman { get; set; }
        public Nullable<int> Taksit_Sayisi { get; set; }
        public Nullable<int> Taksit_Araligi { get; set; }
        public Nullable<System.DateTime> Kredi_Alim_Tarihi { get; set; }
        public Nullable<double> Odenecek_Kredi_Tutari { get; set; }
        public string Banka_Kodu { get; set; }
        public string Mevduat_Banka_Kodu { get; set; }
        public string Masraf_Kodu { get; set; }
        public Nullable<double> KKDF_Orani { get; set; }
    }
}
