//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class MASR_Karti
    {
        public string Masraf_Kodu { get; set; }
        public Nullable<byte> IptDrm { get; set; }
        public string Masraf_Adi { get; set; }
        public Nullable<byte> Masraf_Tipi { get; set; }
        public Nullable<byte> Isyeri_Kodu { get; set; }
        public string PBirimi { get; set; }
        public Nullable<double> BFiyati { get; set; }
        public Nullable<double> Kdv_Orn { get; set; }
        public Nullable<double> OTV_Orn { get; set; }
        public string Muh_Kodu1 { get; set; }
        public string Muh_Kodu2 { get; set; }
        public string Grup_Kodu { get; set; }
        public Nullable<double> Periyodik_Deger { get; set; }
        public Nullable<int> Periyodik_Gun { get; set; }
    }
}
