//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class MASR_Fis_Kalem
    {
        public short Isyeri_Kodu { get; set; }
        public short Fis_Tipi { get; set; }
        public int Fis_No { get; set; }
        public int Fis_Sira { get; set; }
        public Nullable<short> Fis_Durum { get; set; }
        public Nullable<System.DateTime> Fis_Tarihi { get; set; }
        public string Masraf_Kodu { get; set; }
        public string Muh_Kodu { get; set; }
        public Nullable<byte> Masraf_Tipi { get; set; }
        public string Para_Birimi { get; set; }
        public Nullable<double> Kur_Degeri1 { get; set; }
        public Nullable<double> Kur_Degeri2 { get; set; }
        public Nullable<short> KDV_Tipi { get; set; }
        public Nullable<double> KDV_Orani { get; set; }
        public Nullable<double> OTV_Orani { get; set; }
        public Nullable<double> OncSayac { get; set; }
        public Nullable<double> SonSayac { get; set; }
        public Nullable<double> Miktari { get; set; }
        public Nullable<double> BFiyati { get; set; }
        public Nullable<double> Tutari { get; set; }
        public Nullable<double> EkTutar1 { get; set; }
        public Nullable<double> EkTutar2 { get; set; }
        public Nullable<double> EkTutar3 { get; set; }
        public Nullable<double> KdvTutari { get; set; }
        public Nullable<double> OtvTutari { get; set; }
        public Nullable<double> DigVergi { get; set; }
        public string Aciklama { get; set; }
        public Nullable<System.DateTime> Vade_Tarihi { get; set; }
        public Nullable<double> TTutar { get; set; }
        public Nullable<double> TTutar1 { get; set; }
        public Nullable<double> TTutar2 { get; set; }
        public Nullable<double> OAy_Devir { get; set; }
        public Nullable<double> GAy_Devir { get; set; }
        public Nullable<double> OTutar { get; set; }
        public string Masraf_Yeri { get; set; }
        public Nullable<double> Yakit_Turu { get; set; }
        public Nullable<double> Isk1 { get; set; }
        public Nullable<double> Isk2 { get; set; }
        public Nullable<double> Isk3 { get; set; }
        public Nullable<double> IskTut1 { get; set; }
        public Nullable<double> IskTut2 { get; set; }
        public Nullable<double> IskTut3 { get; set; }
        public Nullable<double> IskTut { get; set; }
    }
}
