//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mesai_Karti
    {
        public System.DateTime Mesai_Tarih { get; set; }
        public Nullable<byte> Mesai_HGunu { get; set; }
        public Nullable<byte> Mesai_Tipi { get; set; }
    }
}
