//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class MUH_Fis_Baslik_Kutugu
    {
        public byte Ay { get; set; }
        public byte Tip { get; set; }
        public short FisNo { get; set; }
        public Nullable<byte> IptTip { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public Nullable<short> YevNo { get; set; }
        public Nullable<double> Borc { get; set; }
        public Nullable<double> Alacak { get; set; }
        public string Aciklama { get; set; }
        public string Firma { get; set; }
        public string Ref_Hesap { get; set; }
        public string EntVar { get; set; }
        public Nullable<System.DateTime> Acilis_Tarih { get; set; }
        public Nullable<System.DateTime> Update_Tarih { get; set; }
        public Nullable<System.DateTime> Iptal_Tarih { get; set; }
        public string Acilis_User { get; set; }
        public string Update_User { get; set; }
        public string Iptal_User { get; set; }
        public string Kaydir { get; set; }
        public Nullable<short> Ent_Fis_Tipi { get; set; }
        public Nullable<short> Ent_Fis_No { get; set; }
        public string Ent_Fis_Adi { get; set; }
    }
}
