//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class MUH_Sablon_Hareket_Kutugu
    {
        public short FisNo { get; set; }
        public byte Sira { get; set; }
        public string Kod { get; set; }
        public Nullable<short> Referans { get; set; }
        public string Aciklama { get; set; }
        public string Ba_Tip { get; set; }
        public Nullable<double> Borc { get; set; }
        public Nullable<double> Alacak { get; set; }
        public string Dh_Kdv { get; set; }
        public string Kdv_Kodu { get; set; }
        public Nullable<double> Kdv_Orani { get; set; }
        public string DovTip { get; set; }
        public Nullable<double> DovKur { get; set; }
        public Nullable<double> DovFiyat { get; set; }
        public Nullable<float> StkMik { get; set; }
        public Nullable<double> StkFyt { get; set; }
    }
}
