//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class MUH_Kasa_Parametreleri
    {
        public string KasaKodu { get; set; }
        public Nullable<System.DateTime> KasaTarihi { get; set; }
        public Nullable<short> KasaSayfa { get; set; }
        public Nullable<double> KasaBorc { get; set; }
        public Nullable<double> KasaAlck { get; set; }
    }
}
