//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class MUH_Hesap_Toplam_Kutugu
    {
        public string Kod { get; set; }
        public string Yil { get; set; }
        public byte Ay { get; set; }
        public Nullable<double> AyBorc { get; set; }
        public Nullable<double> AyAlck { get; set; }
        public Nullable<double> Ak_AyBorc { get; set; }
        public Nullable<double> Ak_AyAlck { get; set; }
        public Nullable<double> KmBorc { get; set; }
        public Nullable<double> KmAlck { get; set; }
        public Nullable<double> AyBorc_Dv { get; set; }
        public Nullable<double> AyAlck_Dv { get; set; }
        public Nullable<double> Ak_AyBorc_Dv { get; set; }
        public Nullable<double> Ak_AyAlck_Dv { get; set; }
        public Nullable<double> KmBorc_Dv { get; set; }
        public Nullable<double> KmAlck_Dv { get; set; }
        public Nullable<double> AyBorc_Bt { get; set; }
        public Nullable<double> AyAlck_Bt { get; set; }
        public Nullable<double> KmBorc_Bt { get; set; }
        public Nullable<double> KmAlck_Bt { get; set; }
        public Nullable<double> StkGiren { get; set; }
        public Nullable<double> StkCikan { get; set; }
    }
}
