//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class MUH_Sicil_Bilgi_Girisi
    {
        public byte Kod { get; set; }
        public string Yili { get; set; }
        public string VerGid { get; set; }
        public string Il_Ilce { get; set; }
        public Nullable<double> BasTarih { get; set; }
        public Nullable<double> BitTarih { get; set; }
        public string SicilN1 { get; set; }
        public string Soyadi { get; set; }
        public string Adi { get; set; }
        public string MahKoy1 { get; set; }
        public string CadSok1 { get; set; }
        public string KapiNo1 { get; set; }
        public string DareNo1 { get; set; }
        public string IlIlce1 { get; set; }
        public string PttKod1 { get; set; }
        public string TelefN1 { get; set; }
        public string MahKoy2 { get; set; }
        public string CadSok2 { get; set; }
        public string KapiNo2 { get; set; }
        public string DareNo2 { get; set; }
        public string IlIlce2 { get; set; }
        public string PttKod2 { get; set; }
        public string TelefN2 { get; set; }
        public string BabaAdi { get; set; }
        public string DogYeri { get; set; }
        public string DogTar { get; set; }
        public string Faliyet { get; set; }
        public string Sirket { get; set; }
        public Nullable<short> C62 { get; set; }
        public Nullable<short> C63 { get; set; }
        public Nullable<short> C64 { get; set; }
        public Nullable<short> Devir { get; set; }
        public string Unvani { get; set; }
    }
}
