//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class MUH_GecmisDonem_Kutugu
    {
        public string Kod { get; set; }
        public string Yil { get; set; }
        public byte Ay { get; set; }
        public Nullable<double> AyBorc { get; set; }
        public Nullable<double> AyAlck { get; set; }
    }
}
