//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class MUH_KDV_Hesap_Tanitimi
    {
        public string Kod { get; set; }
        public string Ad1 { get; set; }
        public Nullable<byte> Kdv_Orn { get; set; }
        public Nullable<byte> Tvk_Tipi { get; set; }
        public string Muh_Kodu { get; set; }
    }
}
