//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class MUH_HesKodu_GiderYer_Tab
    {
        public string Tip { get; set; }
        public string HesKodu { get; set; }
        public string AltKodu { get; set; }
        public string Adi { get; set; }
    }
}
