//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class MUH_Fis_Hareket_Kutugu
    {
        public byte Ay { get; set; }
        public byte Tip { get; set; }
        public short FisNo { get; set; }
        public string Kod { get; set; }
        public short Sira { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public Nullable<short> Referans { get; set; }
        public string Aciklama { get; set; }
        public string Ba_Tip { get; set; }
        public Nullable<double> Borc { get; set; }
        public Nullable<double> Alacak { get; set; }
        public string Dh_Kdv { get; set; }
        public string Kdv_Kodu { get; set; }
        public Nullable<double> Kdv_Orani { get; set; }
        public string DovTip { get; set; }
        public Nullable<double> DovKur { get; set; }
        public Nullable<double> DovFiyat { get; set; }
        public Nullable<double> StkMik { get; set; }
        public Nullable<double> StkFyt { get; set; }
        public Nullable<byte> Ent_Fis_Tipi { get; set; }
        public Nullable<int> Ent_Fis_No { get; set; }
    }
}
