//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class MUH_Hesap_Plan_Tanitimi
    {
        public string Kod { get; set; }
        public Nullable<byte> IptTip { get; set; }
        public string Adi { get; set; }
        public string YAdi { get; set; }
        public Nullable<byte> Durum { get; set; }
        public Nullable<byte> HTipi { get; set; }
        public Nullable<byte> GKodu { get; set; }
        public string Masraf { get; set; }
        public string DovKod { get; set; }
        public string StkBrm { get; set; }
        public Nullable<byte> HTuru { get; set; }
        public string ButTip { get; set; }
        public Nullable<short> MvsNo { get; set; }
        public Nullable<byte> MvAyi { get; set; }
        public Nullable<short> DksNo { get; set; }
        public Nullable<byte> KdvHes { get; set; }
        public string GCesKod { get; set; }
        public string GYerKod { get; set; }
        public Nullable<double> Acilis_Tarihi { get; set; }
        public Nullable<double> Update_Tarih { get; set; }
        public Nullable<double> Iptal_Tarih { get; set; }
        public string Acilis_User { get; set; }
        public string Update_User { get; set; }
        public string Iptal_User { get; set; }
        public Nullable<int> ParasalDegerTipi { get; set; }
    }
}
