//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class MUH_Yansitma_Tablosu
    {
        public short Kod { get; set; }
        public short Sira { get; set; }
        public string Hes1 { get; set; }
        public string Hes2 { get; set; }
        public string Aciklama { get; set; }
        public Nullable<int> Tip { get; set; }
        public string Formul { get; set; }
    }
}
