//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class MUH_Donem_Parametreleri
    {
        public byte Sira { get; set; }
        public string Ay { get; set; }
        public string Yil { get; set; }
        public Nullable<int> YF1_Fisno { get; set; }
    }
}
