//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class MUH_Genel_Parametreler
    {
        public byte Kod { get; set; }
        public Nullable<byte> Uzunluk1 { get; set; }
        public Nullable<byte> Uzunluk2 { get; set; }
        public Nullable<byte> Uzunluk3 { get; set; }
        public Nullable<byte> Uzunluk4 { get; set; }
        public Nullable<byte> Uzunluk5 { get; set; }
        public Nullable<byte> Uzunluk6 { get; set; }
        public string DonemAy { get; set; }
        public string DonemYil { get; set; }
        public Nullable<byte> KrSayisi { get; set; }
        public Nullable<byte> UzunTop { get; set; }
        public Nullable<byte> KurusTipi { get; set; }
        public Nullable<byte> MuhFisTipi { get; set; }
        public Nullable<byte> KasaTipi { get; set; }
        public Nullable<byte> YevTipi { get; set; }
        public Nullable<byte> Deftipi { get; set; }
        public Nullable<byte> MahTipi { get; set; }
        public Nullable<byte> FisTipi { get; set; }
        public Nullable<byte> FisUzrTipi { get; set; }
        public Nullable<byte> BilancoTipi { get; set; }
        public Nullable<byte> IsletmeTipi { get; set; }
        public Nullable<byte> YazimTipi { get; set; }
        public Nullable<byte> IptalTipi { get; set; }
        public Nullable<byte> KdvTipi { get; set; }
        public Nullable<byte> KayitTipi { get; set; }
        public Nullable<byte> Entegrasyon { get; set; }
        public string KayTip { get; set; }
        public string IptTip { get; set; }
        public string CikTip { get; set; }
        public string IsknKodu { get; set; }
        public Nullable<double> IslemTarih { get; set; }
        public Nullable<double> YevDefter { get; set; }
        public Nullable<double> YevTutar { get; set; }
        public Nullable<short> YevSayfa { get; set; }
        public Nullable<int> YevmiyeNo { get; set; }
        public Nullable<System.DateTime> YevmiyeTarihi { get; set; }
        public string MuvAy { get; set; }
        public string KebAy { get; set; }
        public string Kapatma { get; set; }
        public string DefteriKebir_Donem { get; set; }
        public Nullable<double> DefteriKebir_Sayfa { get; set; }
        public Nullable<bool> Mahsup_Girisi { get; set; }
        public Nullable<bool> Tahsil_Girisi { get; set; }
        public Nullable<bool> Tediye_Girisi { get; set; }
        public string Para_Birimi { get; set; }
        public string E_Defter_Kullanici { get; set; }
        public string E_Defter_Sifre { get; set; }
        public string Vergi_No { get; set; }
        public string E_Defter_Tip { get; set; }
    }
}
