//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class MUH_KDV_Aylik
    {
        public short Yil { get; set; }
        public byte Ay { get; set; }
        public byte Kodu { get; set; }
        public Nullable<double> Deger { get; set; }
        public Nullable<byte> Kdv_Orn { get; set; }
        public Nullable<byte> Tevk_Tip { get; set; }
        public Nullable<short> Turu { get; set; }
    }
}
