//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class MUH_DOVZ_Kurlari
    {
        public string Kodu { get; set; }
        public System.DateTime Tarihi { get; set; }
        public short Tipi { get; set; }
        public Nullable<double> Kur_Degeri_D_Alis { get; set; }
        public Nullable<double> Kur_Degeri_D_Satis { get; set; }
        public Nullable<double> Kur_Degeri_E_Alis { get; set; }
        public Nullable<double> Kur_Degeri_E_Satis { get; set; }
    }
}
