//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class MUH_Tablo_Tanitimi_Detay
    {
        public string Knt { get; set; }
        public string Durum { get; set; }
        public string Tipi { get; set; }
        public short Sira { get; set; }
        public string Grp1 { get; set; }
        public string Grp2 { get; set; }
        public string Grp3 { get; set; }
        public string Hesap { get; set; }
        public string Hesap1 { get; set; }
        public string Isaret { get; set; }
        public Nullable<short> Bakiye { get; set; }
    }
}
