//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class MUH_Onceki_Donem_Tablo
    {
        public string Yil { get; set; }
        public string Ay { get; set; }
        public string Tipi { get; set; }
        public int Sira { get; set; }
        public string Adi { get; set; }
        public Nullable<double> OncekiDonemBorc { get; set; }
        public Nullable<double> OncekiDonemAlacak { get; set; }
        public Nullable<double> CariDonemBorc { get; set; }
        public Nullable<double> CariDonemAlacak { get; set; }
        public byte Underline { get; set; }
        public byte Bold { get; set; }
        public string Sign { get; set; }
        public Nullable<double> OncekiToplam { get; set; }
        public Nullable<double> CariToplam { get; set; }
        public string TabloBasligi { get; set; }
        public string Firma { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
    }
}
