//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class MUH_Fis_Kalem
    {
        public byte Fis_Ayi { get; set; }
        public byte Fis_Tipi { get; set; }
        public int Fis_No { get; set; }
        public short Fis_Sira { get; set; }
        public string Muh_Kodu { get; set; }
        public Nullable<System.DateTime> Fis_Tarihi { get; set; }
        public Nullable<short> Referans { get; set; }
        public string Aciklama { get; set; }
        public string Ba_Tip { get; set; }
        public Nullable<double> Borc { get; set; }
        public Nullable<double> Alacak { get; set; }
        public string Dh_Kdv { get; set; }
        public string Kdv_Kodu { get; set; }
        public Nullable<double> Kdv_Orani { get; set; }
        public string DovTip { get; set; }
        public Nullable<double> DovKur { get; set; }
        public Nullable<double> DovFiyat { get; set; }
        public Nullable<double> StkMik { get; set; }
        public Nullable<double> StkFyt { get; set; }
        public Nullable<short> Ent_Fis_Isy { get; set; }
        public Nullable<short> Ent_Fis_Tipi { get; set; }
        public Nullable<int> Ent_Fis_No { get; set; }
        public Nullable<double> DovBorc { get; set; }
        public Nullable<double> DovAlacak { get; set; }
        public Nullable<double> StkGirMik { get; set; }
        public Nullable<double> StkCikMik { get; set; }
        public Nullable<byte> BA { get; set; }
        public Nullable<byte> BS { get; set; }
        public string Muh_Kodu2 { get; set; }
        public Nullable<double> Fis_Durum { get; set; }
        public string Masraf_Yeri { get; set; }
        public string Belge_No { get; set; }
        public Nullable<System.DateTime> Belge_Tarihi { get; set; }
        public Nullable<byte> Fis_IslemTipi { get; set; }
        public Nullable<byte> Akt_Tipi { get; set; }
        public Nullable<int> Akt_FisNo { get; set; }
        public string Belge_Tipi { get; set; }
    }
}
