//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class MUH_Fis_Baslik
    {
        public byte Fis_Ayi { get; set; }
        public byte Fis_Tipi { get; set; }
        public int Fis_No { get; set; }
        public Nullable<byte> Fis_Durum { get; set; }
        public Nullable<System.DateTime> Fis_Tarihi { get; set; }
        public Nullable<int> YevNo { get; set; }
        public Nullable<double> Borc { get; set; }
        public Nullable<double> Alacak { get; set; }
        public string Aciklama { get; set; }
        public string Firma { get; set; }
        public string Ref_Hesap { get; set; }
        public string EntVar { get; set; }
        public Nullable<System.DateTime> Acilis_Zaman { get; set; }
        public Nullable<System.DateTime> Update_Zaman { get; set; }
        public Nullable<System.DateTime> Iptal_Zaman { get; set; }
        public string Acilis_User { get; set; }
        public string Update_User { get; set; }
        public string Iptal_User { get; set; }
        public Nullable<byte> Kaydir { get; set; }
        public Nullable<short> Ent_Fis_Isy { get; set; }
        public Nullable<short> Ent_Fis_Tipi { get; set; }
        public Nullable<int> Ent_Fis_No { get; set; }
        public string Ent_Fis_Adi { get; set; }
        public Nullable<byte> Kontrol_Kodu { get; set; }
        public Nullable<byte> Fis_IslemTipi { get; set; }
        public Nullable<byte> Akt_Tipi { get; set; }
        public Nullable<int> Akt_FisNo { get; set; }
    }
}
