//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class MUH_Bilanco_Kayit
    {
        public string Yil { get; set; }
        public string Ay { get; set; }
        public int Sira { get; set; }
        public string AktifAdi { get; set; }
        public Nullable<double> AktifOncekiDonemBorc { get; set; }
        public Nullable<double> AktifOncekiDonemAlacak { get; set; }
        public Nullable<double> AktifCariDonemBorc { get; set; }
        public Nullable<double> AktifCariDonemAlacak { get; set; }
        public string PasifAdi { get; set; }
        public Nullable<double> PasifOncekiDonemBorc { get; set; }
        public Nullable<double> PasifOncekiDonemAlacak { get; set; }
        public Nullable<double> PasifCariDonemBorc { get; set; }
        public Nullable<double> PasifCariDonemAlacak { get; set; }
        public byte AktifUnderline { get; set; }
        public byte AktifBold { get; set; }
        public string AktifSign { get; set; }
        public byte PasifUnderline { get; set; }
        public byte PasifBold { get; set; }
        public string PasifSign { get; set; }
        public Nullable<double> AktifOncekiToplam { get; set; }
        public Nullable<double> AktifCariToplam { get; set; }
        public Nullable<double> PasifOncekiToplam { get; set; }
        public Nullable<double> PasifCariToplam { get; set; }
        public string TabloBasligi { get; set; }
        public string Firma { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
    }
}
