//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class MUST_IADE_Taksit
    {
        public short IptDrm { get; set; }
        public short Fis_Tipi { get; set; }
        public int Fis_No { get; set; }
        public short SiraNo { get; set; }
        public short Isyeri_Kodu { get; set; }
        public Nullable<int> Odm_Fis_No { get; set; }
        public Nullable<short> Odm_SiraNo { get; set; }
        public Nullable<System.DateTime> VadeTar { get; set; }
        public Nullable<int> Must_No { get; set; }
        public string Kodu { get; set; }
        public Nullable<double> Tutar { get; set; }
        public string Depo { get; set; }
    }
}
