//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class MUST_Saticilar
    {
        public string Kodu { get; set; }
        public string AdSoyad { get; set; }
        public string Adres1 { get; set; }
        public string Adres2 { get; set; }
        public string Telefon { get; set; }
        public double Iskonto { get; set; }
    }
}
