//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class MUST_Tahsilat
    {
        public short IptDrm { get; set; }
        public short Fis_tipi { get; set; }
        public int FisNo { get; set; }
        public short Isyeri_Kodu { get; set; }
        public Nullable<int> Must_No { get; set; }
        public string Kodu { get; set; }
        public Nullable<System.DateTime> IslemTar { get; set; }
        public string Kasiyer { get; set; }
        public Nullable<double> Tutar { get; set; }
        public Nullable<double> Faiz { get; set; }
        public Nullable<double> VadeFrk { get; set; }
        public string Acik1 { get; set; }
        public string Acik2 { get; set; }
        public string Depo { get; set; }
        public string Ent_Kodu1 { get; set; }
        public Nullable<short> Ent_Fis_Tipi1 { get; set; }
        public Nullable<int> Ent_Fis_No1 { get; set; }
        public string Ent_Kodu2 { get; set; }
        public Nullable<short> Ent_Fis_Tipi2 { get; set; }
        public Nullable<int> Ent_Fis_No2 { get; set; }
        public Nullable<System.DateTime> AclTrh { get; set; }
        public Nullable<System.DateTime> IptTrh { get; set; }
        public string AclUser { get; set; }
        public string IptUser { get; set; }
        public string Kasa_Kodu { get; set; }
        public string Kayit_Kodu { get; set; }
        public Nullable<byte> Kayit_Yeri { get; set; }
    }
}
