//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class MUST_K_Kartlari
    {
        public byte IptDrm { get; set; }
        public string KKart_No { get; set; }
        public int Must_No { get; set; }
        public Nullable<byte> KKart_Tipi { get; set; }
        public Nullable<byte> KKart_Asil { get; set; }
        public string KKart_Org { get; set; }
        public string Adi { get; set; }
        public string Soyadi { get; set; }
        public string DogYeri { get; set; }
        public Nullable<System.DateTime> DogTar { get; set; }
        public Nullable<byte> Yak_Derecesi { get; set; }
        public string Meslegi { get; set; }
        public string Adresi { get; set; }
        public string Telefon { get; set; }
        public Nullable<System.DateTime> Gec_Tarihi { get; set; }
        public Nullable<double> Kredi_Limiti { get; set; }
    }
}
