//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class MUST_OnOdeme
    {
        public short IslemTipi { get; set; }
        public int IslemNo { get; set; }
        public short IslemSira { get; set; }
        public string Kodu { get; set; }
        public short KdvOr { get; set; }
        public double CikisMiktari { get; set; }
        public double GirisMiktari { get; set; }
        public double BFiyati { get; set; }
        public double CikisTutari { get; set; }
        public double GirisTutari { get; set; }
        public short IskOran { get; set; }
        public double IskTutari { get; set; }
        public double BMaliyet { get; set; }
        public double Maliyeti { get; set; }
        public int KayIslemNo { get; set; }
        public string KaynakTipi { get; set; }
        public System.DateTime Islem_Tarihi { get; set; }
        public string BlgTipi { get; set; }
        public double AmbalajMiktari { get; set; }
        public short Isk_Tipi { get; set; }
        public string Kdv_Tipi { get; set; }
        public double Kdv_Tutari { get; set; }
        public double SIskonto { get; set; }
        public double GIskonto { get; set; }
        public short UpdateMi { get; set; }
        public double Isk_TutariD { get; set; }
        public double Teslim_Tar { get; set; }
        public string Teslim_Drm { get; set; }
        public string Cari_Kodu { get; set; }
    }
}
