//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class MUST_Karti
    {
        public byte IptDrm { get; set; }
        public int Must_No { get; set; }
        public string Kodu { get; set; }
        public string Adi { get; set; }
        public string Soyadi { get; set; }
        public Nullable<byte> MGrubu { get; set; }
        public string IkazKodu { get; set; }
        public string DogYeri { get; set; }
        public Nullable<System.DateTime> DogTar { get; set; }
        public string Meslegi { get; set; }
        public Nullable<short> KrediNotu { get; set; }
        public Nullable<byte> Durum { get; set; }
        public Nullable<byte> Kur_Hesaplama { get; set; }
        public string ParaBirimi { get; set; }
        public Nullable<double> Teminat_Tutari { get; set; }
        public Nullable<double> KrediTut { get; set; }
        public Nullable<System.DateTime> KrediDuzTar { get; set; }
        public Nullable<System.DateTime> KrediTar { get; set; }
        public Nullable<int> KrediAySayisi { get; set; }
        public Nullable<double> RiskTut { get; set; }
        public Nullable<double> VFrkOrn { get; set; }
        public string GrpKodu { get; set; }
        public string OzlKodu { get; set; }
        public string Vdaire { get; set; }
        public string Vno { get; set; }
        public string OzelNot { get; set; }
        public Nullable<short> OdmGun { get; set; }
        public Nullable<short> Opsiyon { get; set; }
        public string Banka { get; set; }
        public string Sube { get; set; }
        public string BnkHesNo { get; set; }
        public Nullable<double> IskOrn { get; set; }
        public string Gecikme { get; set; }
        public Nullable<short> VadeSay { get; set; }
        public Nullable<byte> FytOnc { get; set; }
        public Nullable<byte> KdvMuaf { get; set; }
        public Nullable<System.DateTime> SozTarihi { get; set; }
        public Nullable<short> SozSuresi { get; set; }
        public string IsAdresi { get; set; }
        public string IsTlf { get; set; }
        public string EvAdresi { get; set; }
        public string EvTlf { get; set; }
        public Nullable<byte> Hesap_Kesim_Tipi { get; set; }
        public Nullable<byte> Hesap_Kesim_Gunu { get; set; }
        public Nullable<System.DateTime> Son_Hesap_Kesim_Tarihi { get; set; }
        public Nullable<System.DateTime> AclTrh { get; set; }
        public Nullable<System.DateTime> UptTrh { get; set; }
        public Nullable<System.DateTime> IptTrh { get; set; }
        public string AclUser { get; set; }
        public string UptUser { get; set; }
        public string IptUser { get; set; }
        public string Muh_Kodu1 { get; set; }
        public string Muh_Kodu2 { get; set; }
        public string CepTlf { get; set; }
        public Nullable<int> Cari_No { get; set; }
        public Nullable<byte> Cinsiyeti { get; set; }
        public Nullable<byte> Medeni_Hali { get; set; }
        public Nullable<System.DateTime> Evlilik_YilDonumu { get; set; }
        public Nullable<byte> Cocuk_Sayisi { get; set; }
        public string eMail_1 { get; set; }
        public string eMail_2 { get; set; }
        public string Kan_Grubu { get; set; }
        public Nullable<byte> Sube_Kodu { get; set; }
        public string Es_Adi { get; set; }
        public Nullable<byte> Ogr_Durumu { get; set; }
        public string Cal_Isyeri_Adi { get; set; }
        public Nullable<double> Geliri { get; set; }
        public Nullable<byte> Aile_Fert_Sayisi { get; set; }
        public string Tuttugu_Takim { get; set; }
        public string Hobiler { get; set; }
        public Nullable<byte> Veresiye_Verilemez { get; set; }
        public Nullable<System.DateTime> Veresiye_Engel_Tarihi { get; set; }
        public string Pers_Kodu { get; set; }
        public string Masraf_Kodu { get; set; }
        public string Ilcesi { get; set; }
        public string Ili { get; set; }
    }
}
