//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class MUST_Satis
    {
        public short IptDrm { get; set; }
        public short Fis_tipi { get; set; }
        public int FisNo { get; set; }
        public short Isyeri_Kodu { get; set; }
        public Nullable<int> Must_No { get; set; }
        public string Kodu { get; set; }
        public Nullable<short> Tipi { get; set; }
        public Nullable<System.DateTime> IslemTar { get; set; }
        public string Kasiyer { get; set; }
        public Nullable<double> SatTutar { get; set; }
        public Nullable<double> VadeFrk { get; set; }
        public Nullable<double> TopTutar { get; set; }
        public Nullable<double> Pesinat { get; set; }
        public Nullable<double> KalTutar { get; set; }
        public Nullable<short> VadeSys { get; set; }
        public Nullable<double> VadeTut { get; set; }
        public Nullable<System.DateTime> IlkVadTar { get; set; }
        public Nullable<double> AcikHes { get; set; }
        public Nullable<System.DateTime> ValorTar { get; set; }
        public string Aciklama1 { get; set; }
        public string Aciklama2 { get; set; }
        public string Sat_Kodu { get; set; }
        public Nullable<short> Depo_Kodu { get; set; }
        public Nullable<double> Yuv_Deger { get; set; }
        public Nullable<short> Yuv_Tipi { get; set; }
        public string Satis_Tipi { get; set; }
        public string Tes_Sekli { get; set; }
        public Nullable<System.DateTime> Teslim_Tarihi { get; set; }
        public Nullable<double> IskTutar { get; set; }
        public Nullable<int> StokFisno { get; set; }
        public string Ent_Kodu1 { get; set; }
        public Nullable<short> Ent_Fis_Tipi1 { get; set; }
        public Nullable<int> Ent_Fis_No1 { get; set; }
        public string Ent_Kodu2 { get; set; }
        public Nullable<short> Ent_Fis_Tipi2 { get; set; }
        public Nullable<int> Ent_Fis_No2 { get; set; }
        public Nullable<System.DateTime> AclTrh { get; set; }
        public Nullable<System.DateTime> UptTrh { get; set; }
        public Nullable<System.DateTime> IptTrh { get; set; }
        public string AclUser { get; set; }
        public string UptUser { get; set; }
        public string IptUser { get; set; }
        public string Kasa_Kodu { get; set; }
        public Nullable<byte> Kayit_Yeri { get; set; }
        public Nullable<short> PKasa_No { get; set; }
        public string Kayit_Kodu { get; set; }
        public Nullable<double> IskOran { get; set; }
        public string Ozel_Kodu { get; set; }
    }
}
