//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class MUST_Puan
    {
        public short Isyeri_Kodu { get; set; }
        public short Fis_Tipi { get; set; }
        public int Fis_No { get; set; }
        public short Fis_Durum { get; set; }
        public int Must_No { get; set; }
        public Nullable<double> Satis_Tutari { get; set; }
        public Nullable<double> Satis_Puani { get; set; }
        public Nullable<double> Ode_Tutari { get; set; }
        public Nullable<double> Ode_Puani { get; set; }
        public Nullable<System.DateTime> Fis_Tarihi { get; set; }
    }
}
