//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class MUST_Cocuklar
    {
        public int Must_No { get; set; }
        public byte Sira { get; set; }
        public Nullable<byte> IptDrm { get; set; }
        public string Cocuk_Adi { get; set; }
        public Nullable<System.DateTime> DogTarihi { get; set; }
        public Nullable<byte> Cinsiyeti { get; set; }
    }
}
