//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class MYERI_Karti
    {
        public string MYeri_Kodu { get; set; }
        public Nullable<byte> IptDrm { get; set; }
        public string MYeri_Adi { get; set; }
        public Nullable<byte> Isyeri_Kodu { get; set; }
        public string Muh_Kodu1 { get; set; }
        public string Muh_Kodu2 { get; set; }
    }
}
