//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class NAKT_Plan_Kalem
    {
        public short Fis_Durum { get; set; }
        public short Fis_Tipi { get; set; }
        public int Fis_No { get; set; }
        public int Fis_Sira { get; set; }
        public short Isyeri_Kodu { get; set; }
        public Nullable<System.DateTime> Fis_Tarihi { get; set; }
        public Nullable<System.DateTime> Vade_Tarihi { get; set; }
        public string Emri_Veren { get; set; }
        public Nullable<byte> Islem_Tipi { get; set; }
        public Nullable<short> Masraf_Yeri { get; set; }
        public Nullable<byte> Kynk_Hes_Tipi { get; set; }
        public string Kynk_Hes_Kodu { get; set; }
        public Nullable<byte> Hdf_Hes_Tipi { get; set; }
        public string Hdf_Hes_Kodu { get; set; }
        public Nullable<byte> Odm_Sekli { get; set; }
        public Nullable<double> Islm_Tutari { get; set; }
        public string Aciklama { get; set; }
        public string Para_Birimi { get; set; }
        public Nullable<double> Kur_Degeri1 { get; set; }
        public Nullable<double> Kur_Degeri2 { get; set; }
        public Nullable<double> Kur_DegeriP { get; set; }
    }
}
