//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARAMETRELER
    {
        public string prmGrubu { get; set; }
        public string prmKodu { get; set; }
        public string prmDegeri { get; set; }
        public string Aciklama { get; set; }
    }
}
