//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDA_Islemler
    {
        public byte Fis_Isyeri { get; set; }
        public byte Fis_Tipi { get; set; }
        public int Fis_No { get; set; }
        public int Fis_Sira { get; set; }
        public Nullable<byte> Fis_Drm { get; set; }
        public Nullable<System.DateTime> Fis_Tar { get; set; }
        public Nullable<byte> Fis_Depo { get; set; }
        public Nullable<int> Fis_Cari_No { get; set; }
        public string Fis_Belge_No { get; set; }
        public string Fis_Aciklama { get; set; }
        public Nullable<double> Fis_Tutar { get; set; }
        public Nullable<double> Fis_KdvTutar { get; set; }
        public Nullable<double> Fis_IskTutar { get; set; }
        public Nullable<double> Fis_NetTutar { get; set; }
        public Nullable<int> Cari_No { get; set; }
        public string Belge_No { get; set; }
        public Nullable<int> Stok_No { get; set; }
        public string Birim { get; set; }
        public Nullable<double> BrmOrn { get; set; }
        public Nullable<byte> IslemTipi { get; set; }
        public Nullable<double> Miktar { get; set; }
        public Nullable<double> Fiyat { get; set; }
        public Nullable<double> Tutar { get; set; }
        public Nullable<double> IskOrn1 { get; set; }
        public Nullable<double> IskOrn2 { get; set; }
        public Nullable<double> IskOrn3 { get; set; }
        public Nullable<double> IskTutar { get; set; }
        public Nullable<double> KdvOrn { get; set; }
        public Nullable<double> KdvTutar { get; set; }
        public Nullable<byte> Depo2 { get; set; }
    }
}
