//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERS_Degerleme_Karti
    {
        public int Deger_Tip { get; set; }
        public int Deger_No { get; set; }
        public string Deger_Aciklama { get; set; }
    }
}
