//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pers_Gunluk_Puantaj
    {
        public short Isyeri_Kodu { get; set; }
        public string Pers_Kodu { get; set; }
        public System.DateTime Tarih { get; set; }
        public string Giris_Saat { get; set; }
        public string Cikis_Saat { get; set; }
        public string GunIci_Izin { get; set; }
        public string Eksik_Mesai { get; set; }
        public string Fazla_Mesai { get; set; }
        public Nullable<double> Calisma { get; set; }
        public Nullable<double> Gun_Hesap { get; set; }
    }
}
