//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERS_Degerleme_Kalem
    {
        public short Fis_Durum { get; set; }
        public short Fis_Tipi { get; set; }
        public int Fis_No { get; set; }
        public int Fis_Sira { get; set; }
        public short Isyeri_Kodu { get; set; }
        public Nullable<System.DateTime> Fis_Tarihi { get; set; }
        public string Personel_Kodu { get; set; }
        public Nullable<byte> Soru1 { get; set; }
        public Nullable<byte> Soru2 { get; set; }
        public Nullable<byte> Soru3 { get; set; }
        public Nullable<byte> Soru4 { get; set; }
        public Nullable<byte> Soru5 { get; set; }
        public Nullable<byte> Soru6 { get; set; }
        public Nullable<byte> Soru7 { get; set; }
        public Nullable<byte> Soru8 { get; set; }
        public Nullable<byte> Soru9 { get; set; }
        public Nullable<byte> Soru10 { get; set; }
        public string Aciklama { get; set; }
    }
}
