//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pers_Mesai_Gruplari
    {
        public string Mesai_Grup { get; set; }
        public string Mesai_Tanimi { get; set; }
        public string Mesai1g { get; set; }
        public string Mesai1c { get; set; }
        public string Mesai2g { get; set; }
        public string mesai2c { get; set; }
        public string Mesai3g { get; set; }
        public string Mesai3c { get; set; }
        public string OpsiyonGR { get; set; }
        public string OpsiyonCK { get; set; }
        public string OpsiyonFM { get; set; }
    }
}
