//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pers_Fis_Baslik
    {
        public short Fis_Durum { get; set; }
        public short Fis_Tipi { get; set; }
        public int Fis_No { get; set; }
        public short Isyeri_Kodu { get; set; }
        public Nullable<System.DateTime> Fis_Tarihi { get; set; }
        public string Pers_Kodu { get; set; }
        public string Aciklama { get; set; }
        public Nullable<double> TopBorc { get; set; }
        public Nullable<double> TopAlck { get; set; }
        public string Acilis_User { get; set; }
        public string Update_User { get; set; }
        public string Iptal_User { get; set; }
        public Nullable<System.DateTime> Acilis_Zaman { get; set; }
        public Nullable<System.DateTime> Update_Zaman { get; set; }
        public Nullable<System.DateTime> Iptal_Zaman { get; set; }
        public Nullable<byte> Kontrol_Kodu { get; set; }
        public string Ent_Kodu1 { get; set; }
        public Nullable<byte> Ent_Fis_Tipi1 { get; set; }
        public Nullable<int> Ent_Fis_No1 { get; set; }
        public string Ent_Kodu2 { get; set; }
        public Nullable<byte> Ent_Fis_Tipi2 { get; set; }
        public Nullable<int> Ent_Fis_No2 { get; set; }
        public string Ozel_Kodu { get; set; }
    }
}
