//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pers_Hesaplar
    {
        public short PTipi { get; set; }
        public short Isyeri_Kodu { get; set; }
        public short Yil { get; set; }
        public short Ay { get; set; }
        public string Pers_Kodu { get; set; }
        public Nullable<double> Cal_Gun { get; set; }
        public Nullable<double> Izin_Gun { get; set; }
        public Nullable<double> Dev_Izin { get; set; }
        public Nullable<double> Yil_Izin { get; set; }
        public Nullable<double> SDisi_Gun { get; set; }
        public Nullable<double> Dvr_Izin { get; set; }
        public Nullable<double> Hes_Gun { get; set; }
        public Nullable<double> Gun_Ucret { get; set; }
        public Nullable<double> Ek_Ucret { get; set; }
        public Nullable<double> Bayram_Ikm { get; set; }
        public Nullable<double> AySonu_Maas { get; set; }
        public Nullable<double> Aysonu_Muh_Brd { get; set; }
        public Nullable<double> Rap_Gun { get; set; }
        public Nullable<double> Ucr_Izin_Gun { get; set; }
        public Nullable<double> Avans1 { get; set; }
        public Nullable<double> Avans2 { get; set; }
        public Nullable<double> Bayram_IkOdeme { get; set; }
        public Nullable<double> Kesinti_Icra { get; set; }
        public Nullable<double> EOdeme1 { get; set; }
        public Nullable<double> EOdeme2 { get; set; }
        public Nullable<double> YemekAsim { get; set; }
        public Nullable<double> Kesinti_Diger { get; set; }
        public Nullable<double> Imzalanan_Tutar { get; set; }
        public Nullable<double> Bankadan_Odenecek { get; set; }
        public Nullable<double> Elden_Odenecek { get; set; }
        public string Aciklama { get; set; }
        public string Kullanici { get; set; }
        public Nullable<System.DateTime> UpdateZaman { get; set; }
        public Nullable<double> Kesinti_BES { get; set; }
        public Nullable<double> Yeni_YIzin { get; set; }
        public Nullable<double> Dev_YIzin { get; set; }
        public Nullable<double> Dvrdn_YIzin { get; set; }
        public Nullable<double> Iade_Ucret { get; set; }
        public string Aciklama2 { get; set; }
        public Nullable<double> Aysonu_Muh_Brd2 { get; set; }
        public Nullable<double> Cal_Gun2 { get; set; }
        public Nullable<double> Izin_Gun2 { get; set; }
        public Nullable<double> Iade_Edilen { get; set; }
        public Nullable<double> Avans3 { get; set; }
        public Nullable<double> EOdeme3 { get; set; }
        public Nullable<double> Bankadan_Odenen { get; set; }
        public Nullable<double> Elden_Odenen { get; set; }
        public Nullable<byte> AciklamaAktar { get; set; }
    }
}
