//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pers_Fis_Kalem
    {
        public short Fis_Durum { get; set; }
        public short Fis_Tipi { get; set; }
        public int Fis_No { get; set; }
        public short Fis_Sira { get; set; }
        public short Isyeri_Kodu { get; set; }
        public Nullable<System.DateTime> Fis_Tarihi { get; set; }
        public string Pers_Kodu { get; set; }
        public Nullable<int> Yil { get; set; }
        public Nullable<int> Ay { get; set; }
        public string Aciklama { get; set; }
        public Nullable<double> BorcTutari { get; set; }
        public Nullable<double> AlckTutari { get; set; }
        public Nullable<System.DateTime> Fis_Tarih { get; set; }
        public Nullable<System.DateTime> Isl_Tarih { get; set; }
        public Nullable<double> Gun1 { get; set; }
        public Nullable<double> Gun2 { get; set; }
        public Nullable<double> Gun3 { get; set; }
        public Nullable<double> FMS1 { get; set; }
        public Nullable<double> FMS2 { get; set; }
        public Nullable<double> FMS3 { get; set; }
        public string Masraf_Yeri { get; set; }
    }
}
