//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pers_Kartli_Girisler
    {
        public short Isyeri_Kodu { get; set; }
        public string Pers_Kodu { get; set; }
        public System.DateTime Okuma_Zaman { get; set; }
        public string Aciklama { get; set; }
        public Nullable<byte> GC_Tipi { get; set; }
    }
}
