//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLAN_Satis_Fis
    {
        public short Isyeri_Kodu { get; set; }
        public short Plan_No { get; set; }
        public short Fis_Tipi { get; set; }
        public Nullable<System.DateTime> Plan_Tarihi { get; set; }
    }
}
