//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLAN_Satis_Kalem
    {
        public short Isyeri_Kodu { get; set; }
        public short Plan_No { get; set; }
        public int Stok_No { get; set; }
        public short Plan_Ay { get; set; }
        public short Fis_Tipi { get; set; }
        public string Satis_Birim { get; set; }
        public Nullable<double> Satis_Adet { get; set; }
        public Nullable<double> Satis_Kg { get; set; }
    }
}
