//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pos_Promosyon_Gunluk
    {
        public byte Tip { get; set; }
        public string Kodu { get; set; }
        public Nullable<System.DateTime> IlkTarih { get; set; }
        public Nullable<System.DateTime> SonTarih { get; set; }
        public Nullable<byte> GunKodu { get; set; }
        public Nullable<double> Oran { get; set; }
    }
}
