//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pos_Promosyon_Baslik
    {
        public short Isyeri_Kodu { get; set; }
        public byte Fis_Tipi { get; set; }
        public int Fis_No { get; set; }
        public Nullable<byte> Fis_Durum { get; set; }
        public string PTipi { get; set; }
        public Nullable<byte> TumIsyerleri { get; set; }
        public string Isyerleri { get; set; }
        public Nullable<System.DateTime> Fis_Tarihi { get; set; }
        public string Aciklama { get; set; }
        public Nullable<System.DateTime> Bsl_Zaman { get; set; }
        public Nullable<System.DateTime> Bts_Zaman { get; set; }
        public string Acilis_User { get; set; }
        public string Update_User { get; set; }
        public string Iptal_User { get; set; }
        public Nullable<System.DateTime> Acilis_Zaman { get; set; }
        public Nullable<System.DateTime> Update_Zaman { get; set; }
        public Nullable<System.DateTime> Iptal_Zaman { get; set; }
        public Nullable<byte> Kilit { get; set; }
    }
}
