//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pos_Promosyon_Bilgileri
    {
        public string PTipi { get; set; }
        public string MTipi { get; set; }
        public string RKodu { get; set; }
        public string GKodu { get; set; }
        public Nullable<int> PluNo1 { get; set; }
        public Nullable<double> LimitTutar { get; set; }
        public Nullable<double> LimitAdet { get; set; }
        public Nullable<double> AlimLimiti { get; set; }
        public Nullable<int> IndOran { get; set; }
        public Nullable<double> IndTutar { get; set; }
        public Nullable<int> PluNo2 { get; set; }
        public Nullable<double> Fiyati { get; set; }
        public Nullable<double> PromAdet { get; set; }
        public string MustSec { get; set; }
        public string SatTipi { get; set; }
        public string SecTipi { get; set; }
        public string IndTipi1 { get; set; }
        public string IndTipi2 { get; set; }
        public Nullable<System.DateTime> Bsl_Zaman { get; set; }
        public Nullable<System.DateTime> Bts_Zaman { get; set; }
        public string OKodu { get; set; }
        public Nullable<int> PromNo { get; set; }
        public string Aciklama { get; set; }
        public string OKodu2 { get; set; }
        public string Aciklama2 { get; set; }
        public string Carpim { get; set; }
    }
}
