//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prog_Log_Detay
    {
        public string Log_Program { get; set; }
        public string Log_Kullanici { get; set; }
        public string Log_Islem_Kodu { get; set; }
        public System.DateTime Log_Zaman { get; set; }
        public Nullable<short> Isyeri_Kodu { get; set; }
        public Nullable<short> Fis_Tipi { get; set; }
        public Nullable<int> Fis_No { get; set; }
        public string Log_Bilgi { get; set; }
    }
}
