//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROG_Tipler
    {
        public byte Kodu { get; set; }
        public string Kisa_Adi { get; set; }
        public string Uzun_Adi { get; set; }
        public Nullable<byte> Muh_Ent { get; set; }
        public Nullable<byte> MFis_Tipi { get; set; }
        public Nullable<byte> KFis_Tipi { get; set; }
        public Nullable<byte> BA_Tipi { get; set; }
        public Nullable<byte> Data_No { get; set; }
    }
}
