//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROM_Iskontolar
    {
        public short Fis_Durum { get; set; }
        public int Fis_Tipi { get; set; }
        public int Fis_No { get; set; }
        public int Fis_Sira { get; set; }
        public short Isyeri_Kodu { get; set; }
        public Nullable<System.DateTime> Fis_Tarihi { get; set; }
        public Nullable<double> IskOrani1 { get; set; }
        public Nullable<double> IskOrani2 { get; set; }
        public Nullable<double> IskOrani3 { get; set; }
        public string Para_Birimi { get; set; }
        public Nullable<double> Deger_Tutari { get; set; }
        public Nullable<double> Tutari { get; set; }
        public Nullable<double> Tutari1 { get; set; }
        public Nullable<double> Tutari2 { get; set; }
        public string Aciklama { get; set; }
        public string Ent_Kodu1 { get; set; }
        public string Iskonto_Kodu { get; set; }
        public Nullable<double> IskOrani4 { get; set; }
        public Nullable<double> IskOrani5 { get; set; }
        public Nullable<double> IskOrani6 { get; set; }
    }
}
