//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSAT_Fis_Odeme
    {
        public short Fis_Durum { get; set; }
        public short Fis_Tipi { get; set; }
        public int Fis_No { get; set; }
        public short Isyeri_Kodu { get; set; }
        public int Fis_Sira { get; set; }
        public string Adi { get; set; }
        public string Tipi { get; set; }
        public string Kodu { get; set; }
        public Nullable<double> Tutari { get; set; }
        public Nullable<double> Tutari1 { get; set; }
        public Nullable<double> Tutari2 { get; set; }
        public string Para_Birimi { get; set; }
    }
}
