//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class SATC_Karti
    {
        public int IptDrm { get; set; }
        public string Satc_Kodu { get; set; }
        public string AdiSoyadi { get; set; }
        public string Grup_Kodu { get; set; }
        public string Departman { get; set; }
        public Nullable<double> KomOrani { get; set; }
        public string Mudur_Kodu { get; set; }
        public string Bolge_Kodu { get; set; }
        public string Adresi { get; set; }
        public string IlceIl { get; set; }
        public string Telefon { get; set; }
        public string CepTelefon { get; set; }
    }
}
