//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class Satis_Tutar_Hedef
    {
        public byte Fis_Durum { get; set; }
        public string Satc_Kodu { get; set; }
        public int Hedef_Yili { get; set; }
        public int Hedef_Ay { get; set; }
        public Nullable<double> Hafta_1 { get; set; }
        public Nullable<double> Hafta_2 { get; set; }
        public Nullable<double> Hafta_3 { get; set; }
        public Nullable<double> Hafta_4 { get; set; }
    }
}
