//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class Satici_Ziyaret
    {
        public string Satici_Kodu { get; set; }
        public int Tipi { get; set; }
        public int Zaman { get; set; }
        public System.DateTime Tarih { get; set; }
        public int Cari_No { get; set; }
        public Nullable<int> Ziyaret { get; set; }
        public Nullable<int> IptDrm { get; set; }
    }
}
