//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class Satici_Root
    {
        public string Root_Kodu { get; set; }
        public string Root_Adi { get; set; }
        public int Root_Sirasi { get; set; }
        public int Cari_No { get; set; }
        public int Tipi { get; set; }
        public int Zaman { get; set; }
        public int IptDrm { get; set; }
    }
}
