//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class Satis_Hedef
    {
        public byte Fis_Durum { get; set; }
        public int Hedef_Yili { get; set; }
        public string Satici_Kodu { get; set; }
        public string Satici_Adi { get; set; }
        public string Mudur_Kodu { get; set; }
        public string Bolge_Kodu { get; set; }
        public Nullable<double> Ocak { get; set; }
        public Nullable<double> Subat { get; set; }
        public Nullable<double> Mart { get; set; }
        public Nullable<double> Nisan { get; set; }
        public Nullable<double> Mayis { get; set; }
        public Nullable<double> Haziran { get; set; }
        public Nullable<double> Temmuz { get; set; }
        public Nullable<double> Agustos { get; set; }
        public Nullable<double> Eylul { get; set; }
        public Nullable<double> Ekim { get; set; }
        public Nullable<double> Kasim { get; set; }
        public Nullable<double> Aralik { get; set; }
    }
}
