//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAYM_BIRLESIK_Fis_Kalem
    {
        public short Fis_Durum { get; set; }
        public int Fis_No { get; set; }
        public short Isyeri_Kodu { get; set; }
        public int Fis_Sira { get; set; }
        public Nullable<System.DateTime> Fis_Tarihi { get; set; }
        public Nullable<int> Stok_No { get; set; }
        public string Stok_Kodu { get; set; }
        public string Barkodu { get; set; }
        public Nullable<short> Depo_Kodu { get; set; }
        public string Birim_Tipi { get; set; }
        public Nullable<double> Birim_Orani { get; set; }
        public Nullable<double> Miktari { get; set; }
        public Nullable<double> Fiyati { get; set; }
        public Nullable<double> Tutari { get; set; }
        public Nullable<double> Tutari1 { get; set; }
        public Nullable<double> Tutari2 { get; set; }
        public string Aciklama { get; set; }
        public string Para_Birimi { get; set; }
    }
}
