//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIPR_Fis_Baslik
    {
        public short Fis_Durum { get; set; }
        public short Fis_Tipi { get; set; }
        public int Fis_No { get; set; }
        public short Isyeri_Kodu { get; set; }
        public Nullable<System.DateTime> Fis_Tarihi { get; set; }
        public Nullable<byte> Kilit { get; set; }
        public Nullable<byte> Secim { get; set; }
        public Nullable<short> Depo_Kodu { get; set; }
        public Nullable<int> Cari_No { get; set; }
        public string Belge_No { get; set; }
        public Nullable<System.DateTime> Belge_Tarihi { get; set; }
        public string Belge_Tipi { get; set; }
        public Nullable<int> Belge_FisNo { get; set; }
        public Nullable<short> Sirkuler_Tipi { get; set; }
        public Nullable<int> Sirkuler_No { get; set; }
        public Nullable<System.DateTime> Teslim_Tarihi { get; set; }
        public Nullable<int> Kdv_Tipi1 { get; set; }
        public Nullable<int> Kdv_Tipi2 { get; set; }
        public string Para_Birimi { get; set; }
        public string Fiyat_Tipi { get; set; }
        public Nullable<double> Kur_Degeri { get; set; }
        public Nullable<double> TopDeger1 { get; set; }
        public Nullable<double> TopDeger2 { get; set; }
        public Nullable<double> TopIskonto1 { get; set; }
        public Nullable<double> TopIskonto2 { get; set; }
        public Nullable<double> TopMasraf1 { get; set; }
        public Nullable<double> TopMasraf2 { get; set; }
        public Nullable<double> ToplamKdv { get; set; }
        public Nullable<double> NetTutar1 { get; set; }
        public Nullable<double> NetTutar2 { get; set; }
        public string Aciklama { get; set; }
        public string Yetki_Kodu { get; set; }
        public string Ozel_Kodu { get; set; }
        public string Odeme_Plani { get; set; }
        public string Satici_Kodu1 { get; set; }
        public string Satici_Kodu2 { get; set; }
        public string Acilis_User { get; set; }
        public string Update_User { get; set; }
        public string Iptal_User { get; set; }
        public Nullable<System.DateTime> Acilis_Zaman { get; set; }
        public Nullable<System.DateTime> Update_Zaman { get; set; }
        public Nullable<System.DateTime> Iptal_Zaman { get; set; }
        public string Satici_Kodu { get; set; }
        public Nullable<int> Cari_No1 { get; set; }
        public Nullable<int> K_Sip_No { get; set; }
        public string Olcu { get; set; }
        public string Icerik { get; set; }
        public string Islemler { get; set; }
        public string EkAciklama1 { get; set; }
        public string EkAciklama2 { get; set; }
        public Nullable<byte> Kapali { get; set; }
        public Nullable<byte> Siparis_Tipi { get; set; }
        public string Masraf_Yeri { get; set; }
        public Nullable<int> Sip_Depo { get; set; }
        public Nullable<byte> Kontrol_Kodu { get; set; }
        public string OzelParaBirimi { get; set; }
        public Nullable<double> OzelIslem_Kuru { get; set; }
        public Nullable<int> Vade_Gun { get; set; }
        public Nullable<System.DateTime> Montaj_Tarihi { get; set; }
        public Nullable<byte> Adres_SiraNo { get; set; }
        public Nullable<int> Yazici { get; set; }
        public string Onay_User { get; set; }
        public Nullable<System.DateTime> Onay_Zaman { get; set; }
        public string Sevk_Adi { get; set; }
        public string Sevk_Soyadi { get; set; }
        public string Sevk_Unvani { get; set; }
        public string Sevk_Adresi { get; set; }
        public string Sevk_Ilce { get; set; }
        public string Sevk_Sehir { get; set; }
        public string Sevk_Telefon { get; set; }
        public string Fat_Adi { get; set; }
        public string Fat_Soyadi { get; set; }
        public string Fat_Unvani { get; set; }
        public string Fat_Adresi { get; set; }
        public string Fat_Ilce { get; set; }
        public string Fat_Sehir { get; set; }
        public string Fat_Telefon { get; set; }
        public string VDaire { get; set; }
        public string VergiNo { get; set; }
    }
}
