//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIPR_Fis_Kalem
    {
        public short Fis_Durum { get; set; }
        public short Fis_Tipi { get; set; }
        public int Fis_No { get; set; }
        public int Fis_Sira { get; set; }
        public short Isyeri_Kodu { get; set; }
        public Nullable<System.DateTime> Fis_Tarihi { get; set; }
        public Nullable<short> Kalem_Tipi { get; set; }
        public Nullable<int> Stok_No { get; set; }
        public string Stok_Kodu { get; set; }
        public string BarKodu { get; set; }
        public Nullable<short> Islem_Tipi { get; set; }
        public Nullable<short> Islem_Depo { get; set; }
        public string Birim_Tipi { get; set; }
        public Nullable<double> Birim_Orani { get; set; }
        public Nullable<double> Boyut1 { get; set; }
        public Nullable<double> Boyut2 { get; set; }
        public Nullable<double> Boyut3 { get; set; }
        public Nullable<double> Adedi { get; set; }
        public Nullable<double> Brut_agirlik { get; set; }
        public Nullable<double> Net_agirlik { get; set; }
        public Nullable<double> Miktari { get; set; }
        public Nullable<double> Tes_Miktari { get; set; }
        public string Fiyat_tipi { get; set; }
        public string Para_Birimi { get; set; }
        public Nullable<double> Kur_Degeri1 { get; set; }
        public Nullable<double> Kur_Degeri2 { get; set; }
        public Nullable<double> Birim_Fiyati { get; set; }
        public Nullable<short> KDV_Tipi { get; set; }
        public Nullable<short> KDV_Orani { get; set; }
        public Nullable<short> Mal_Fazlasi_Tipi { get; set; }
        public Nullable<double> IskOrani1 { get; set; }
        public Nullable<double> IskOrani2 { get; set; }
        public Nullable<double> IskOrani3 { get; set; }
        public Nullable<double> IskOrani4 { get; set; }
        public Nullable<double> Isk_Tutari { get; set; }
        public Nullable<double> Masraf_Tutari { get; set; }
        public string Odeme_Kodu { get; set; }
        public Nullable<double> Tutari { get; set; }
        public Nullable<double> Tutari1 { get; set; }
        public Nullable<double> Tutari2 { get; set; }
        public Nullable<double> IskTutari1 { get; set; }
        public Nullable<double> IskTutari2 { get; set; }
        public Nullable<double> IskTutari3 { get; set; }
        public Nullable<double> KdvTutari { get; set; }
        public Nullable<double> Maliyet1 { get; set; }
        public Nullable<double> Maliyet2 { get; set; }
        public Nullable<double> Maliyet3 { get; set; }
        public Nullable<int> Vade { get; set; }
        public Nullable<byte> Secim { get; set; }
        public Nullable<System.DateTime> TesTarihi { get; set; }
        public string Aciklama { get; set; }
        public Nullable<double> NetB_Fiyati { get; set; }
        public Nullable<int> Stok_No_V { get; set; }
        public string Stok_Kodu_V { get; set; }
        public Nullable<double> Iskonto_GD { get; set; }
        public Nullable<double> Tutar_GD { get; set; }
        public string Seri_No { get; set; }
        public Nullable<double> Kur_DegeriP { get; set; }
        public Nullable<double> TutariP { get; set; }
        public Nullable<double> IskOrani5 { get; set; }
        public Nullable<double> IskOrani6 { get; set; }
        public Nullable<double> IskTutari4 { get; set; }
        public Nullable<double> IskTutari5 { get; set; }
        public Nullable<double> IskTutari6 { get; set; }
        public Nullable<double> BMaliyet { get; set; }
        public Nullable<double> Mfz1 { get; set; }
        public Nullable<double> Mfz2 { get; set; }
        public Nullable<double> Istenen_Miktar { get; set; }
    }
}
