//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIPR_Fis_Teslim
    {
        public short Fis_Durum { get; set; }
        public short Isyeri_Kodu { get; set; }
        public short Fis_Tipi { get; set; }
        public int Fis_No { get; set; }
        public int Fis_Sira { get; set; }
        public short Kul_Isyeri_Kodu { get; set; }
        public short Kul_Fis_Tipi { get; set; }
        public int Kul_Fis_No { get; set; }
        public int Kul_Fis_Sira { get; set; }
        public Nullable<double> Kul_Miktar { get; set; }
        public Nullable<int> Stok_No { get; set; }
        public Nullable<System.DateTime> Fis_Tarihi { get; set; }
        public Nullable<byte> Islem { get; set; }
    }
}
