//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIRK_Sozlesmeler
    {
        public byte Sirku_Tipi { get; set; }
        public int Cari_No { get; set; }
        public byte Sira_No { get; set; }
        public Nullable<byte> IptDrm { get; set; }
        public Nullable<int> Belge_No { get; set; }
        public Nullable<System.DateTime> Belge_Tarihi { get; set; }
        public Nullable<short> Mal_Alma_Suresi { get; set; }
        public Nullable<short> Mal_Teslim_Suresi { get; set; }
        public string Sozlesme_Yapan_Kisi { get; set; }
        public Nullable<byte> OSek_Nakit { get; set; }
        public Nullable<byte> OSek_Havale { get; set; }
        public Nullable<byte> OSek_Cek { get; set; }
        public Nullable<byte> Degisim_Durum { get; set; }
        public string Aciklama { get; set; }
        public Nullable<double> KA_Katilim { get; set; }
        public Nullable<double> KA_Stand { get; set; }
        public Nullable<double> KA_Poset { get; set; }
        public Nullable<double> KA_Raf { get; set; }
        public Nullable<double> KA_Reklam { get; set; }
        public Nullable<double> KA_Kasa_Onu { get; set; }
        public Nullable<double> KA_Acilis { get; set; }
        public Nullable<double> KA_Anons { get; set; }
        public Nullable<double> KA_Kasa_Onu_Srs { get; set; }
        public Nullable<double> KA_Acilis_Isk_Srs { get; set; }
        public Nullable<double> KA_Insert { get; set; }
        public Nullable<double> KA_Kule { get; set; }
        public Nullable<double> KA_Gondol { get; set; }
        public Nullable<double> KA_Palet { get; set; }
        public Nullable<double> KA_Sepet { get; set; }
        public Nullable<double> OG_Ramazan { get; set; }
        public Nullable<double> OG_Kurban { get; set; }
        public Nullable<double> OG_Sevgili { get; set; }
        public Nullable<double> OG_Anne { get; set; }
        public Nullable<double> OG_Baba { get; set; }
        public Nullable<double> OG_Yilbasi { get; set; }
        public Nullable<double> OG_YilDonumu { get; set; }
        public string Acilis_User { get; set; }
        public string Update_User { get; set; }
        public string Iptal_User { get; set; }
        public Nullable<System.DateTime> Acilis_Zaman { get; set; }
        public Nullable<System.DateTime> Update_Zaman { get; set; }
        public Nullable<System.DateTime> Iptal_Zaman { get; set; }
        public Nullable<double> Acilis_Isk_Oran1 { get; set; }
        public Nullable<double> Acilis_Isk_Oran2 { get; set; }
        public Nullable<double> Acilis_Isk_Oran3 { get; set; }
        public Nullable<double> Acilis_OVadeGun { get; set; }
        public Nullable<double> Diger_1 { get; set; }
        public Nullable<double> Diger_2 { get; set; }
        public Nullable<double> Oran_Ramazan { get; set; }
        public Nullable<double> Oran_Kurban { get; set; }
        public Nullable<double> Oran_Sevgili { get; set; }
        public Nullable<double> Oran_Anne { get; set; }
        public Nullable<double> Oran_Baba { get; set; }
        public Nullable<double> Oran_Yilbasi { get; set; }
        public Nullable<double> Oran_YilDonum { get; set; }
        public Nullable<double> Oran_Diger1 { get; set; }
        public Nullable<double> Oran_Diger2 { get; set; }
        public Nullable<double> Gun_Ramazan { get; set; }
        public Nullable<double> Gun_Kurban { get; set; }
        public Nullable<double> Gun_Sevgili { get; set; }
        public Nullable<double> Gun_Anne { get; set; }
        public Nullable<double> Gun_Baba { get; set; }
        public Nullable<double> Gun_Yilbasi { get; set; }
        public Nullable<double> Gun_YilDonum { get; set; }
        public Nullable<double> Gun_Diger1 { get; set; }
        public Nullable<double> Gun_Diger2 { get; set; }
        public Nullable<double> Fat_Alti_IskOrn1 { get; set; }
        public Nullable<double> Fat_Alti_IskOrn2 { get; set; }
        public Nullable<double> Fat_Alti_IskOrn3 { get; set; }
    }
}
