//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIRK_Iskontolar
    {
        public byte Sirku_Tipi { get; set; }
        public int Cari_No { get; set; }
        public byte Sira_No { get; set; }
        public System.DateTime Tarih { get; set; }
        public byte Tip { get; set; }
        public Nullable<byte> IptDrm { get; set; }
        public Nullable<short> Gun { get; set; }
        public Nullable<double> Isk1 { get; set; }
        public Nullable<double> Isk2 { get; set; }
        public Nullable<double> Isk3 { get; set; }
        public Nullable<System.DateTime> Bas_Tarihi { get; set; }
    }
}
