//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIRK_Aktivite
    {
        public byte Sirku_Tipi { get; set; }
        public int Cari_No { get; set; }
        public byte Sira_No { get; set; }
        public string Islem_Adi { get; set; }
        public Nullable<byte> IptDrm { get; set; }
        public Nullable<double> Ocak { get; set; }
        public Nullable<double> Subat { get; set; }
        public Nullable<double> Mart { get; set; }
        public Nullable<double> Nisan { get; set; }
        public Nullable<double> Mayis { get; set; }
        public Nullable<double> Haziran { get; set; }
        public Nullable<double> Temmuz { get; set; }
        public Nullable<double> Agustos { get; set; }
        public Nullable<double> Eylul { get; set; }
        public Nullable<double> Ekim { get; set; }
        public Nullable<double> Kasim { get; set; }
        public Nullable<double> Aralik { get; set; }
    }
}
