//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class SKYM_VUK_Listesi
    {
        public string VUK_Liste_No { get; set; }
        public string VUK_Liste_Adi { get; set; }
        public Nullable<byte> Ekonomik_Omur { get; set; }
        public Nullable<double> Amort_Orani { get; set; }
    }
}
