//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class SKYM_Islemler
    {
        public int SKym_No { get; set; }
        public System.DateTime Isl_Tarihi { get; set; }
        public short Isl_Tipi { get; set; }
        public Nullable<double> SKym_Borc { get; set; }
        public Nullable<double> SKym_Alck { get; set; }
        public Nullable<double> SKym_Degeri { get; set; }
        public Nullable<double> Ayr_Amortisman { get; set; }
        public Nullable<double> Brk_Amortisman { get; set; }
        public string Aciklama { get; set; }
        public short IIsy_Kodu { get; set; }
        public short IFis_Tipi { get; set; }
        public int IFis_No { get; set; }
    }
}
