//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class SKYM_Karti
    {
        public short IptDrm { get; set; }
        public int SKYM_No { get; set; }
        public string SKYM_Kodu { get; set; }
        public string SKYM_Adi { get; set; }
        public string Ozel_Kodu { get; set; }
        public string Yetki_Kodu { get; set; }
        public string Grup_Kodu { get; set; }
        public string Uretici_Kodu { get; set; }
        public string Brm_Kodu { get; set; }
        public Nullable<double> KdvOrn_Alis { get; set; }
        public Nullable<double> KdvOrn_Satis { get; set; }
        public string GTIP_Kodu { get; set; }
        public string Odeme_sekli { get; set; }
        public Nullable<byte> Durum { get; set; }
        public Nullable<byte> Amort_Turu { get; set; }
        public Nullable<double> Amort_Orani { get; set; }
        public Nullable<double> Amortisman { get; set; }
        public Nullable<double> Hurda_Deg { get; set; }
        public string SKYM_Tipi { get; set; }
        public Nullable<byte> MuhTip1 { get; set; }
        public string MuhKodu1 { get; set; }
        public Nullable<byte> MuhTip2 { get; set; }
        public string MuhKodu2 { get; set; }
        public Nullable<byte> MuhTip3 { get; set; }
        public string MuhKodu3 { get; set; }
        public Nullable<byte> MuhTip4 { get; set; }
        public string MuhKodu4 { get; set; }
        public Nullable<byte> MuhTip5 { get; set; }
        public string MuhKodu5 { get; set; }
        public Nullable<byte> MuhTip6 { get; set; }
        public string MuhKodu6 { get; set; }
        public Nullable<byte> MuhTip7 { get; set; }
        public string MuhKodu7 { get; set; }
        public Nullable<System.DateTime> Amrt_Bas_Tar { get; set; }
        public Nullable<double> Degeri { get; set; }
        public string VUK_Liste_No { get; set; }
        public Nullable<byte> Ekonomik_Omur { get; set; }
        public Nullable<System.DateTime> Virman_Tar { get; set; }
        public Nullable<System.DateTime> Iade_Tar { get; set; }
        public string ParaBirimi { get; set; }
        public Nullable<double> DegeriP { get; set; }
        public string Acilis_User { get; set; }
        public string Update_User { get; set; }
        public string Iptal_User { get; set; }
        public Nullable<System.DateTime> Acilis_Zaman { get; set; }
        public Nullable<System.DateTime> Update_Zaman { get; set; }
        public Nullable<System.DateTime> Iptal_Zaman { get; set; }
        public Nullable<byte> MuhTip8 { get; set; }
        public string MuhKodu8 { get; set; }
    }
}
