//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class SKYM_Gruplar
    {
        public string Kodu { get; set; }
        public string Adi { get; set; }
        public string Aciklama { get; set; }
        public Nullable<int> Grup_No { get; set; }
        public string Ana_Grup_Kodu { get; set; }
        public Nullable<int> Ana_Grup_No { get; set; }
    }
}
