//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class SKYM_Amortismanlar
    {
        public int SKYM_No { get; set; }
        public System.DateTime Donem { get; set; }
        public Nullable<double> SKYM_Degeri { get; set; }
        public Nullable<double> Ayr_Amortisman { get; set; }
        public Nullable<double> Brk_Amortisman { get; set; }
        public System.DateTime Virman_Tar { get; set; }
        public System.DateTime Iade_Tar { get; set; }
    }
}
