//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class STOK_Toplam
    {
        public short IptDrm { get; set; }
        public int Stok_No { get; set; }
        public short Depo { get; set; }
        public short Yil { get; set; }
        public byte Ay { get; set; }
        public Nullable<double> Giris_Miktari { get; set; }
        public Nullable<double> Cikis_Miktari { get; set; }
        public Nullable<double> Iade_Giris_Miktari { get; set; }
        public Nullable<double> Iade_Cikis_Miktari { get; set; }
        public Nullable<double> G_Siparis_Miktari { get; set; }
        public Nullable<double> C_Siparis_Miktari { get; set; }
        public Nullable<double> G_Proforma_Miktari { get; set; }
        public Nullable<double> C_Proforma_Miktari { get; set; }
        public Nullable<double> Satis_Miktari { get; set; }
        public Nullable<double> Iade_Satis_Miktari { get; set; }
        public Nullable<double> Giris_Tutari { get; set; }
        public Nullable<double> Cikis_Tutari { get; set; }
        public Nullable<double> Cikis_Maliyet1 { get; set; }
        public Nullable<double> Cikis_Maliyet2 { get; set; }
        public Nullable<double> Cikis_Maliyet3 { get; set; }
        public Nullable<double> Iade_Giris_Tutari { get; set; }
        public Nullable<double> Iade_Cikis_Tutari { get; set; }
        public Nullable<double> Iade_Cikis_Maliyet1 { get; set; }
        public Nullable<double> Iade_Cikis_Maliyet2 { get; set; }
        public Nullable<double> Iade_Cikis_Maliyet3 { get; set; }
        public Nullable<double> G_Siparis_Tutari { get; set; }
        public Nullable<double> C_Siparis_Tutari { get; set; }
        public Nullable<double> G_Proforma_Tutari { get; set; }
        public Nullable<double> C_Proforma_Tutari { get; set; }
        public Nullable<double> Satis_Tutari { get; set; }
        public Nullable<double> Iade_Satis_Tutari { get; set; }
    }
}
