//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class STOK_Fiyat
    {
        public byte IptDrm { get; set; }
        public int Stok_No { get; set; }
        public string Tip { get; set; }
        public byte Sira_No { get; set; }
        public string PBirimi { get; set; }
        public Nullable<double> Deger { get; set; }
        public Nullable<double> Iskonto { get; set; }
        public string OPlani { get; set; }
        public short Isyeri_Kodu { get; set; }
        public Nullable<double> Iskonto1 { get; set; }
        public Nullable<double> Iskonto2 { get; set; }
        public Nullable<double> Iskonto3 { get; set; }
        public Nullable<double> IskontoG { get; set; }
        public Nullable<byte> Kdv_DH { get; set; }
        public Nullable<byte> Durum { get; set; }
        public Nullable<byte> Kilitli { get; set; }
        public Nullable<byte> Bagli { get; set; }
    }
}
