//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class STOK_Karti_D
    {
        public int Stok_No { get; set; }
        public short Depo_Kodu { get; set; }
        public short IptDrm { get; set; }
        public string Reyon_Kodu { get; set; }
        public Nullable<double> Kar_Orani { get; set; }
        public Nullable<double> Max_Miktar { get; set; }
        public Nullable<double> Min_Miktar { get; set; }
        public Nullable<short> Raf_Omru { get; set; }
        public Nullable<byte> Satinalma { get; set; }
        public Nullable<byte> Satis { get; set; }
    }
}
