//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class STOK_Etiket_Basim
    {
        public int Stok_No { get; set; }
        public string Fiyat_Tipi { get; set; }
        public short Isyeri_Kodu { get; set; }
        public System.DateTime Zaman { get; set; }
        public double Deger { get; set; }
    }
}
