//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class STOK_Sirkuler_Baslik
    {
        public short Fis_Durum { get; set; }
        public short Fis_Tipi { get; set; }
        public int Cari_No { get; set; }
        public int Fis_No { get; set; }
        public short Isyeri_Kodu { get; set; }
        public Nullable<System.DateTime> Fis_Tarihi { get; set; }
        public Nullable<byte> Kilit { get; set; }
        public Nullable<byte> Kdv { get; set; }
        public string Odeme_Plani { get; set; }
        public Nullable<System.DateTime> Bsl_Tarih { get; set; }
        public Nullable<System.DateTime> Bts_Tarih { get; set; }
        public string Para_Birimi { get; set; }
        public string Fiyat_Tipi { get; set; }
        public string Aciklama { get; set; }
        public string Firma_SirkuNo { get; set; }
        public Nullable<double> GIskOrn1 { get; set; }
        public Nullable<double> GIskOrn2 { get; set; }
        public Nullable<double> GIskOrn3 { get; set; }
        public Nullable<byte> Kontrol_Kodu { get; set; }
        public Nullable<int> Soz_SiraNo { get; set; }
        public Nullable<byte> Sirku_Tipi { get; set; }
        public string Isyerleri { get; set; }
    }
}
