//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class STOK_Fis_Kalem
    {
        public short Fis_Durum { get; set; }
        public short Fis_Tipi { get; set; }
        public int Fis_No { get; set; }
        public int Fis_Sira { get; set; }
        public short Islem_Depo { get; set; }
        public short Isyeri_Kodu { get; set; }
        public Nullable<System.DateTime> Fis_Tarihi { get; set; }
        public Nullable<short> Kalem_Tipi { get; set; }
        public Nullable<short> Grup_Tipi { get; set; }
        public Nullable<int> Stok_No { get; set; }
        public string Stok_Kodu { get; set; }
        public string BarKodu { get; set; }
        public string Stok_Seri_No { get; set; }
        public string Stok_Lot_No { get; set; }
        public Nullable<short> Islem_Tipi { get; set; }
        public string Birim_Tipi { get; set; }
        public Nullable<double> Birim_Orani { get; set; }
        public Nullable<double> Boyut1 { get; set; }
        public Nullable<double> Boyut2 { get; set; }
        public Nullable<double> Boyut3 { get; set; }
        public Nullable<double> Adedi { get; set; }
        public Nullable<double> Katsayi { get; set; }
        public Nullable<double> Brut_agirlik { get; set; }
        public Nullable<double> Net_agirlik { get; set; }
        public Nullable<double> GMiktari { get; set; }
        public Nullable<double> CMiktari { get; set; }
        public Nullable<short> Mal_Fazlasi_Tipi { get; set; }
        public Nullable<short> Vade_Gunu { get; set; }
        public string Fiyat_tipi { get; set; }
        public string Para_Birimi { get; set; }
        public Nullable<double> Kur_Degeri1 { get; set; }
        public Nullable<double> Kur_Degeri2 { get; set; }
        public Nullable<double> Birim_Fiyati { get; set; }
        public Nullable<short> KDV_Tipi { get; set; }
        public Nullable<short> KDV_Orani { get; set; }
        public Nullable<short> EkV_Orani { get; set; }
        public Nullable<double> IskOrani1 { get; set; }
        public Nullable<double> IskOrani2 { get; set; }
        public Nullable<double> IskOrani3 { get; set; }
        public Nullable<double> Isk_Tutari { get; set; }
        public Nullable<double> Masraf_Tutari { get; set; }
        public string Odeme_Kodu { get; set; }
        public Nullable<double> GTutari { get; set; }
        public Nullable<double> GTutari1 { get; set; }
        public Nullable<double> GTutari2 { get; set; }
        public Nullable<double> CTutari { get; set; }
        public Nullable<double> CTutari1 { get; set; }
        public Nullable<double> CTutari2 { get; set; }
        public Nullable<double> IskTutari1 { get; set; }
        public Nullable<double> IskTutari2 { get; set; }
        public Nullable<double> IskTutari3 { get; set; }
        public Nullable<double> KdvTutari { get; set; }
        public Nullable<double> EkVTutari { get; set; }
        public Nullable<double> Maliyet1 { get; set; }
        public Nullable<double> Maliyet2 { get; set; }
        public Nullable<double> Maliyet3 { get; set; }
        public string Satici_Kodu { get; set; }
        public Nullable<double> Kom_Oran { get; set; }
        public string Siparis_Fis_No { get; set; }
        public string Referans_No { get; set; }
        public string Teslim_Sekli_Kodu { get; set; }
        public string Aciklama { get; set; }
        public Nullable<double> En { get; set; }
        public Nullable<double> Boy { get; set; }
        public Nullable<double> Dara { get; set; }
        public Nullable<double> Yukseklik { get; set; }
        public Nullable<System.DateTime> Vade_Tarihi { get; set; }
        public string Ent_Kodu1 { get; set; }
        public Nullable<System.DateTime> Uretim_Tarihi { get; set; }
        public Nullable<System.DateTime> Son_Kul_Tarihi { get; set; }
        public Nullable<short> GFis_Tipi { get; set; }
        public Nullable<int> GFis_No { get; set; }
        public Nullable<short> MlytDuz { get; set; }
        public Nullable<int> Sipr_Fis_No { get; set; }
        public Nullable<short> Sipr_Fis_Sira { get; set; }
        public Nullable<short> Iade_FisTipi { get; set; }
        public Nullable<int> Iade_FisNo { get; set; }
        public Nullable<byte> MlytIslemSira { get; set; }
        public Nullable<double> Ozel_Maliyet { get; set; }
        public Nullable<double> FMaliyet { get; set; }
        public Nullable<double> FTutari { get; set; }
        public Nullable<double> FTutari1 { get; set; }
        public Nullable<double> FTutari2 { get; set; }
        public Nullable<int> Kul_StokNo { get; set; }
        public Nullable<double> Kul_Miktari { get; set; }
        public Nullable<double> AlsKdvMly { get; set; }
        public Nullable<double> AlsFinMly { get; set; }
        public Nullable<double> AlsMasMly { get; set; }
        public Nullable<double> Isk_Payi { get; set; }
        public Nullable<double> Mas_Payi { get; set; }
        public Nullable<double> IskOrani4 { get; set; }
        public Nullable<double> IskOrani5 { get; set; }
        public Nullable<double> IskOrani6 { get; set; }
        public Nullable<double> IskTutari4 { get; set; }
        public Nullable<double> IskTutari5 { get; set; }
        public Nullable<double> IskTutari6 { get; set; }
        public Nullable<double> Isk_TutMly { get; set; }
        public string Isk_MTipi { get; set; }
        public Nullable<double> Mfz_Mik { get; set; }
        public Nullable<double> Mfz_Tut { get; set; }
        public Nullable<double> GD_IskOrn { get; set; }
        public Nullable<double> GD_IskTut { get; set; }
        public Nullable<double> Yn_IskTut { get; set; }
        public Nullable<double> Yn_MfzTut { get; set; }
        public Nullable<double> Net_BMaliyet { get; set; }
        public string Masraf_Yeri { get; set; }
        public string K_FisBilgi { get; set; }
        public Nullable<double> IMiktari { get; set; }
        public Nullable<double> NetB_Fiyati { get; set; }
        public Nullable<System.DateTime> MlytKulTar { get; set; }
        public Nullable<double> Maliyet4 { get; set; }
        public Nullable<byte> MlytDuz2 { get; set; }
        public Nullable<byte> MlytDuz3 { get; set; }
        public Nullable<byte> MlytDuz4 { get; set; }
        public Nullable<byte> Hes_Metod { get; set; }
        public Nullable<short> Sipr_Isyeri_Kodu { get; set; }
        public Nullable<double> Fire_Orani { get; set; }
        public string KK_Degerlendirme { get; set; }
        public Nullable<double> Nem_Orani { get; set; }
        public Nullable<double> Sicakligi { get; set; }
        public Nullable<int> Sipr_Isyeri { get; set; }
        public Nullable<double> Net_BMaliyet2 { get; set; }
        public string Teslim_Sekli { get; set; }
        public string GTIP_No { get; set; }
        public Nullable<byte> Gonderim_Sekli { get; set; }
        public string Kab_No { get; set; }
        public Nullable<double> Kab_Adedi { get; set; }
        public string Kab_Cinsi { get; set; }
        public string Belge_No { get; set; }
        public Nullable<System.DateTime> Belge_Tarihi { get; set; }
    }
}
