//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stok_Fis_Kalem_Tarim
    {
        public short Fis_Durum { get; set; }
        public short Fis_Tipi { get; set; }
        public int Fis_No { get; set; }
        public int Fis_Sira { get; set; }
        public short Islem_Depo { get; set; }
        public short Isyeri_Kodu { get; set; }
        public Nullable<int> GCari_No { get; set; }
        public string GFat_No { get; set; }
        public Nullable<System.DateTime> GFat_Tarihi { get; set; }
        public string KulUrun_Kodu { get; set; }
        public Nullable<double> KulYeri_Alani1 { get; set; }
        public Nullable<double> KulYeri_Alani2 { get; set; }
        public Nullable<double> KulYeri_Alani3 { get; set; }
        public string KulHastalik_Tanim { get; set; }
        public string KulYabanciOt_Tanim { get; set; }
        public string KulZararli_Tanim { get; set; }
        public string KulAciklama { get; set; }
    }
}
