//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class STOK_Fis_Kalem_Seri
    {
        public short Fis_Durum { get; set; }
        public short Fis_Tipi { get; set; }
        public short Isyeri_Kodu { get; set; }
        public int Fis_No { get; set; }
        public int Stok_No { get; set; }
        public string Stok_Seri_No { get; set; }
        public Nullable<short> Islem_Tipi { get; set; }
        public string IMEI_No { get; set; }
        public Nullable<long> GSM_No { get; set; }
        public string Banka { get; set; }
        public Nullable<byte> Soz_Turu { get; set; }
        public Nullable<byte> K1 { get; set; }
        public Nullable<byte> K2 { get; set; }
        public Nullable<byte> K3 { get; set; }
        public Nullable<byte> K4 { get; set; }
        public Nullable<byte> K5 { get; set; }
        public Nullable<System.DateTime> Tes_Tarihi { get; set; }
        public string Aciklama { get; set; }
        public int Fis_Sira { get; set; }
    }
}
