//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class STOK_Depozito_Kalem
    {
        public short Fis_Durum { get; set; }
        public short Fis_Tipi { get; set; }
        public int Fis_No { get; set; }
        public int Fis_Sira { get; set; }
        public short Isyeri_Kodu { get; set; }
        public Nullable<System.DateTime> Fis_Tarihi { get; set; }
        public string Depozito_Kodu { get; set; }
        public string Para_Birimi { get; set; }
        public Nullable<double> GMiktari { get; set; }
        public Nullable<double> CMiktari { get; set; }
        public Nullable<double> BFiyati { get; set; }
        public Nullable<double> Kur_Degeri1 { get; set; }
        public Nullable<double> Kur_Degeri2 { get; set; }
        public Nullable<short> KDV_Tipi { get; set; }
        public Nullable<short> KDV_Orani { get; set; }
        public Nullable<double> GTutari { get; set; }
        public Nullable<double> GTutari1 { get; set; }
        public Nullable<double> GTutari2 { get; set; }
        public Nullable<double> CTutari { get; set; }
        public Nullable<double> CTutari1 { get; set; }
        public Nullable<double> CTutari2 { get; set; }
        public Nullable<double> KdvTutari { get; set; }
        public string Aciklama { get; set; }
        public Nullable<System.DateTime> Vade_Tarihi { get; set; }
        public string Muh_Kodu { get; set; }
    }
}
