//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class STOK_Sirkuler_Kalem
    {
        public short Fis_Durum { get; set; }
        public short Fis_Tipi { get; set; }
        public int Cari_No { get; set; }
        public int Fis_No { get; set; }
        public int Sira_No { get; set; }
        public int Stok_No { get; set; }
        public short Isyeri_Kodu { get; set; }
        public string Stok_Kodu { get; set; }
        public string BarKodu { get; set; }
        public string PBirimi { get; set; }
        public string Odeme_Kodu { get; set; }
        public string Brm { get; set; }
        public string Aciklama { get; set; }
        public Nullable<double> Fiyat { get; set; }
        public Nullable<double> Fran_Yeni { get; set; }
        public Nullable<double> Iskonto_O4 { get; set; }
        public Nullable<double> Degisim { get; set; }
        public Nullable<double> F_Kar { get; set; }
        public Nullable<double> Iskonto_O1 { get; set; }
        public Nullable<double> Iskonto_O2 { get; set; }
        public Nullable<double> Iskonto_O3 { get; set; }
        public Nullable<double> KDV { get; set; }
        public Nullable<double> Kar { get; set; }
        public Nullable<double> Mlfz1 { get; set; }
        public Nullable<double> Mlfz2 { get; set; }
        public Nullable<double> Eski { get; set; }
        public Nullable<double> Yeni { get; set; }
        public Nullable<double> Vade { get; set; }
        public Nullable<double> Iskonto_O5 { get; set; }
        public Nullable<double> Iskonto_O6 { get; set; }
        public Nullable<double> Iskonto_GD { get; set; }
        public Nullable<double> AKdv { get; set; }
        public Nullable<double> Maliyet { get; set; }
        public Nullable<double> NetB_Fiyati { get; set; }
        public Nullable<double> Tutar_GD { get; set; }
        public Nullable<double> Masraf_Orani { get; set; }
        public Nullable<double> CPA_Isk { get; set; }
        public Nullable<double> CP3_Isk { get; set; }
        public Nullable<double> CP6_Isk { get; set; }
        public Nullable<double> CPY_Isk { get; set; }
        public Nullable<double> Brm_Orani { get; set; }
        public string Seri_No { get; set; }
        public Nullable<double> MaliyetN { get; set; }
    }
}
