//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class STOK_Maliyet
    {
        public short Isyeri_Kodu { get; set; }
        public short Depo_Kodu { get; set; }
        public int Stok_No { get; set; }
        public System.DateTime Tarih { get; set; }
        public Nullable<double> GMikTop { get; set; }
        public Nullable<double> CMikTop { get; set; }
        public Nullable<double> GTutTop { get; set; }
        public Nullable<double> CTutTop { get; set; }
        public Nullable<double> BMaliyet { get; set; }
        public Nullable<double> CMikTop2 { get; set; }
        public Nullable<double> CTutTop2 { get; set; }
    }
}
