//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class STOK_Birim_Fiyat
    {
        public int Stok_No { get; set; }
        public string Stok_Birim { get; set; }
        public string Fiyat_Tipi { get; set; }
        public short Isyeri_Kodu { get; set; }
        public Nullable<byte> Iptdrm { get; set; }
        public Nullable<double> Fiyati { get; set; }
    }
}
