//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class STOK_Aylik_Maliyet
    {
        public int Stok_No { get; set; }
        public short Isyeri_Kodu { get; set; }
        public short Depo_Kodu { get; set; }
        public System.DateTime Tarih { get; set; }
        public Nullable<double> GMiktari { get; set; }
        public Nullable<double> CMiktari { get; set; }
        public Nullable<double> GOrtMlyt { get; set; }
        public Nullable<double> COrtMlyt { get; set; }
        public Nullable<double> GMaliyet { get; set; }
        public Nullable<double> CMaliyet { get; set; }
        public Nullable<double> GMikTop { get; set; }
        public Nullable<double> CMikTop { get; set; }
        public Nullable<double> GMlytTop { get; set; }
        public Nullable<double> CMlytTop { get; set; }
    }
}
