//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class STOK_FirmaStokKodlari
    {
        public int Cari_No { get; set; }
        public int Stok_No { get; set; }
        public string FirmaStokKodu { get; set; }
        public Nullable<short> IptDrm { get; set; }
        public Nullable<double> Katsayi { get; set; }
        public Nullable<byte> Tip { get; set; }
    }
}
