//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class STOK_Promosyon_Karti
    {
        public byte IptDrm { get; set; }
        public string Kodu { get; set; }
        public string Adi { get; set; }
        public string PBirimi { get; set; }
        public Nullable<double> Kdv_Oran { get; set; }
        public string Muh_Kodu { get; set; }
    }
}
