//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class STOK_Deg_Fiyat
    {
        public int Stok_No { get; set; }
        public string Fiyat_Tipi { get; set; }
        public System.DateTime Deg_Tarihi { get; set; }
        public Nullable<double> Fiyat { get; set; }
        public Nullable<double> Eski_Fiyat { get; set; }
        public short Isyeri_Kodu { get; set; }
        public byte IptDrm { get; set; }
    }
}
