//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class STOK_Karti_R
    {
        public int Stok_No { get; set; }
        public int Isyeri_Kodu { get; set; }
        public byte IptDrm { get; set; }
        public string Fiyat_Tipi1 { get; set; }
        public string Fiyat_Tipi2 { get; set; }
        public string Fiyat_Tipi3 { get; set; }
        public Nullable<short> Yazici_Grubu { get; set; }
        public Nullable<short> Yazdirma_Yeri { get; set; }
        public Nullable<short> Tus_No { get; set; }
        public Nullable<byte> PDA { get; set; }
        public Nullable<byte> AktifPasif { get; set; }
    }
}
