//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class STOK_Departman
    {
        public byte Dep_No { get; set; }
        public string Dep_Adi { get; set; }
        public Nullable<byte> Kdv_Alis { get; set; }
        public Nullable<byte> Kdv_Satis { get; set; }
        public Nullable<byte> Muh_Tipi1 { get; set; }
        public string Muh_Kodu1 { get; set; }
        public Nullable<byte> Muh_Tipi2 { get; set; }
        public string Muh_Kodu2 { get; set; }
        public Nullable<byte> Muh_Tipi3 { get; set; }
        public string Muh_Kodu3 { get; set; }
        public Nullable<byte> Muh_Tipi4 { get; set; }
        public string Muh_Kodu4 { get; set; }
        public Nullable<byte> Muh_Tipi5 { get; set; }
        public string Muh_Kodu5 { get; set; }
        public Nullable<byte> Muh_Tipi6 { get; set; }
        public string Muh_Kodu6 { get; set; }
        public Nullable<byte> Muh_Tipi7 { get; set; }
        public string Muh_Kodu7 { get; set; }
        public Nullable<byte> Muh_Tipi8 { get; set; }
        public string Muh_Kodu8 { get; set; }
    }
}
