//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class STOK_Birim
    {
        public byte IptDrm { get; set; }
        public int Stok_No { get; set; }
        public string Kodu { get; set; }
        public byte Sira_No { get; set; }
        public Nullable<byte> Birim_Onceligi { get; set; }
        public Nullable<double> Katsayi { get; set; }
        public Nullable<byte> Agirlik_Birim { get; set; }
        public Nullable<double> Net { get; set; }
        public Nullable<double> Dara { get; set; }
        public Nullable<byte> Uzunluk_Birim { get; set; }
        public Nullable<double> En { get; set; }
        public Nullable<double> Boy { get; set; }
        public Nullable<double> Yukseklik { get; set; }
    }
}
