//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class STOK_Fiyat_Hareket
    {
        public short IptDrm { get; set; }
        public int Stok_No { get; set; }
        public string Tip { get; set; }
        public System.DateTime Tarih { get; set; }
        public string PBirimi { get; set; }
        public Nullable<double> Deger { get; set; }
        public Nullable<double> Iskonto { get; set; }
        public string OPlani { get; set; }
    }
}
