//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class STOK_BagliStoklar
    {
        public int Stok_No { get; set; }
        public int Bagli_Stok_No { get; set; }
        public Nullable<double> Miktari { get; set; }
    }
}
