//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class STOK_Barkod
    {
        public short IptDrm { get; set; }
        public int Stok_No { get; set; }
        public string Barkod { get; set; }
        public string Tip { get; set; }
        public string Birim { get; set; }
        public string Icerik { get; set; }
        public Nullable<int> Ana_No { get; set; }
        public string Seri_No { get; set; }
        public string Aciklama { get; set; }
    }
}
