//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Cari_GunlukToplam
    {
        public int Cari_No { get; set; }
        public System.DateTime Tarih { get; set; }
        public short Isyeri_Kodu { get; set; }
        public short Fis_Tipi { get; set; }
        public Nullable<double> BorcTutari { get; set; }
        public Nullable<double> BorcTutari1 { get; set; }
        public Nullable<double> BorcTutari2 { get; set; }
        public Nullable<double> BorcTutariP { get; set; }
        public Nullable<double> AlckTutari { get; set; }
        public Nullable<double> AlckTutari1 { get; set; }
        public Nullable<double> AlckTutari2 { get; set; }
        public Nullable<double> AlckTutariP { get; set; }
    }
}
