//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Stok_GunlukToplam
    {
        public int Stok_No { get; set; }
        public System.DateTime Tarih { get; set; }
        public short Islem_Depo { get; set; }
        public short Fis_Tipi { get; set; }
        public Nullable<double> GMiktari { get; set; }
        public Nullable<double> CMiktari { get; set; }
        public Nullable<double> GTutari { get; set; }
        public Nullable<double> GTutari1 { get; set; }
        public Nullable<double> GTutari2 { get; set; }
        public Nullable<double> CTutari { get; set; }
        public Nullable<double> CTutari1 { get; set; }
        public Nullable<double> CTutari2 { get; set; }
        public Nullable<double> Isk_Tutari { get; set; }
        public Nullable<double> KdvTutari { get; set; }
        public Nullable<double> Net_BMaliyet { get; set; }
        public Nullable<double> Maliyet1 { get; set; }
        public Nullable<double> Maliyet2 { get; set; }
        public Nullable<double> Maliyet3 { get; set; }
    }
}
