//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class TKLF_Fis_Kalem
    {
        public short Fis_Durum { get; set; }
        public short Fis_Tipi { get; set; }
        public int Fis_No { get; set; }
        public int Fis_Sira { get; set; }
        public short Isyeri_Kodu { get; set; }
        public Nullable<System.DateTime> Fis_Tarihi { get; set; }
        public Nullable<int> Stok_No { get; set; }
        public string Stok_Kodu { get; set; }
        public string BarKodu { get; set; }
        public string Birim_Tipi { get; set; }
        public Nullable<double> Birim_Orani { get; set; }
        public Nullable<double> Miktari { get; set; }
        public string Para_Birimi { get; set; }
        public Nullable<double> Kur_Degeri1 { get; set; }
        public Nullable<double> Kur_Degeri2 { get; set; }
        public Nullable<double> Birim_Fiyati { get; set; }
        public Nullable<short> KDV_Tipi { get; set; }
        public Nullable<short> KDV_Orani { get; set; }
        public Nullable<double> Tutari { get; set; }
        public Nullable<double> Tutari1 { get; set; }
        public Nullable<double> Tutari2 { get; set; }
        public Nullable<double> KdvTutari { get; set; }
        public Nullable<double> TklfFiyati1 { get; set; }
        public Nullable<double> TklfFiyati2 { get; set; }
        public Nullable<double> TklfFiyati3 { get; set; }
        public Nullable<double> TklfFiyati4 { get; set; }
        public Nullable<double> TklfFiyati5 { get; set; }
        public Nullable<double> TklfFiyati6 { get; set; }
        public Nullable<double> TklfFiyati7 { get; set; }
        public Nullable<double> TklfFiyati8 { get; set; }
        public Nullable<double> YFiyat { get; set; }
        public Nullable<byte> Secim { get; set; }
        public Nullable<System.DateTime> TesTarihi { get; set; }
        public string Aciklama { get; set; }
        public Nullable<double> RFiyat { get; set; }
        public Nullable<double> YFiyat2 { get; set; }
        public Nullable<double> YFiyatPK { get; set; }
        public Nullable<double> YFiyatKL { get; set; }
    }
}
