//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class TKLF_Fis_Baslik
    {
        public short Fis_Durum { get; set; }
        public short Fis_Tipi { get; set; }
        public int Fis_No { get; set; }
        public short Isyeri_Kodu { get; set; }
        public Nullable<System.DateTime> Fis_Tarihi { get; set; }
        public Nullable<byte> Kilit { get; set; }
        public Nullable<byte> Secim { get; set; }
        public Nullable<short> Depo_Kodu { get; set; }
        public string Belge_No { get; set; }
        public Nullable<System.DateTime> Belge_Tarihi { get; set; }
        public string Belge_Tipi { get; set; }
        public Nullable<int> Belge_FisNo { get; set; }
        public Nullable<System.DateTime> Teslim_Tarihi { get; set; }
        public Nullable<int> Kdv_Tipi1 { get; set; }
        public Nullable<int> Kdv_Tipi2 { get; set; }
        public string Para_Birimi { get; set; }
        public string Fiyat_Tipi { get; set; }
        public Nullable<double> Kur_Degeri { get; set; }
        public Nullable<double> TopDeger1 { get; set; }
        public Nullable<double> TopDeger2 { get; set; }
        public string Aciklama { get; set; }
        public string Yetki_Kodu { get; set; }
        public string Ozel_Kodu { get; set; }
        public string Odeme_Plani { get; set; }
        public string Satici_Kodu1 { get; set; }
        public string Satici_Kodu2 { get; set; }
        public string Acilis_User { get; set; }
        public string Update_User { get; set; }
        public string Iptal_User { get; set; }
        public Nullable<System.DateTime> Acilis_Zaman { get; set; }
        public Nullable<System.DateTime> Update_Zaman { get; set; }
        public Nullable<System.DateTime> Iptal_Zaman { get; set; }
        public string Satici_Kodu { get; set; }
        public Nullable<int> Cari_No1 { get; set; }
        public Nullable<int> Cari_No2 { get; set; }
        public Nullable<int> Cari_No3 { get; set; }
        public Nullable<int> Cari_No4 { get; set; }
        public Nullable<int> Cari_No5 { get; set; }
        public Nullable<int> Cari_No6 { get; set; }
        public Nullable<int> Cari_No7 { get; set; }
        public Nullable<int> Cari_No8 { get; set; }
        public Nullable<byte> Kapali { get; set; }
        public Nullable<byte> Kontrol_Kodu { get; set; }
        public string OzelParaBirimi { get; set; }
        public Nullable<double> OzelIslem_Kuru { get; set; }
        public string Onay_User { get; set; }
        public Nullable<System.DateTime> Onay_Zaman { get; set; }
    }
}
