//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class URET_Recete_Detay
    {
        public string Recete_Kodu { get; set; }
        public short Fis_Tipi { get; set; }
        public int Sira { get; set; }
        public Nullable<byte> Kalem_Tipi { get; set; }
        public Nullable<int> Stok_No { get; set; }
        public string Masraf_Kodu { get; set; }
        public string Birimi { get; set; }
        public Nullable<double> Miktar { get; set; }
        public string Degisken { get; set; }
        public Nullable<double> Degisken_Degeri { get; set; }
        public Nullable<double> Birim_Maliyet { get; set; }
        public Nullable<double> Toplam_Maliyet { get; set; }
        public Nullable<double> Uret_Miktari { get; set; }
        public Nullable<double> Birim_Orani { get; set; }
    }
}
