//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class URET_Mamul_Fisi
    {
        public byte Fis_Durum { get; set; }
        public short IsYeri_Kodu { get; set; }
        public short Fis_Tipi { get; set; }
        public int Fis_No { get; set; }
        public short Fis_Sira { get; set; }
        public Nullable<int> IsEmri_No { get; set; }
        public Nullable<System.DateTime> Fis_Tarihi { get; set; }
        public Nullable<short> Depo_Kodu { get; set; }
        public Nullable<int> Stok_No { get; set; }
        public string Birimi { get; set; }
        public Nullable<double> Miktar { get; set; }
        public string PBirimi { get; set; }
        public Nullable<double> Birim_Maliyet { get; set; }
        public Nullable<double> Toplam_Maliyet { get; set; }
        public Nullable<int> IsEmri_FisNo { get; set; }
        public string Parti_No { get; set; }
        public string Seri_No { get; set; }
        public Nullable<int> Sipr_Isyeri { get; set; }
        public Nullable<int> Sipr_FisTipi { get; set; }
        public Nullable<int> Sipr_FisNo { get; set; }
        public Nullable<short> Kontrol { get; set; }
    }
}
