//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class URET_Recete
    {
        public string Recete_Kodu { get; set; }
        public short Fis_Tipi { get; set; }
        public int Stok_No { get; set; }
        public string Tanimi { get; set; }
        public Nullable<double> Miktari { get; set; }
        public string Birimi { get; set; }
        public string Acilis_User { get; set; }
        public string Update_User { get; set; }
        public string Iptal_User { get; set; }
        public Nullable<System.DateTime> Acilis_Zaman { get; set; }
        public Nullable<System.DateTime> Update_Zaman { get; set; }
        public Nullable<System.DateTime> Iptal_Zaman { get; set; }
        public Nullable<byte> Pasif { get; set; }
        public Nullable<byte> Bagli_Uretme { get; set; }
        public string Referans { get; set; }
        public Nullable<double> Mamul_Ham_Agirligi { get; set; }
        public Nullable<double> Mamul_Son_Agirligi { get; set; }
        public Nullable<double> Mamul_Son_Agirligi2 { get; set; }
        public string Referans2 { get; set; }
        public string Bekleme_Suresi { get; set; }
        public string Hazirlanma_Suresi { get; set; }
        public Nullable<double> Alt_Birim_Agirligi { get; set; }
        public string Uretim_Sicakligi { get; set; }
        public string Mamul_Aciklama { get; set; }
        public Nullable<double> Birim_Orani { get; set; }
    }
}
