//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class URET_IsEmri_Plan_Detay
    {
        public short IsYeri_Kodu { get; set; }
        public short Fis_Tipi { get; set; }
        public int Fis_No { get; set; }
        public int Fis_Sira { get; set; }
        public string Recete_Kodu { get; set; }
        public Nullable<byte> Fis_Durum { get; set; }
        public Nullable<double> Miktari { get; set; }
        public Nullable<double> Adedi { get; set; }
        public string Parti_No { get; set; }
        public string Eleman_Kodu { get; set; }
        public Nullable<System.DateTime> Bas_Tarihi { get; set; }
        public Nullable<System.DateTime> Bit_Tarihi { get; set; }
    }
}
