//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class URET_Is_Emri
    {
        public byte Fis_Durum { get; set; }
        public short IsYeri_Kodu { get; set; }
        public short Fis_Tipi { get; set; }
        public int Fis_No { get; set; }
        public Nullable<System.DateTime> Fis_Tarihi { get; set; }
        public string Recete_Kodu { get; set; }
        public string Urun_Kodu { get; set; }
        public Nullable<int> Stok_No { get; set; }
        public Nullable<int> Depo_Kodu { get; set; }
        public Nullable<double> Rec_Ici_Miktar { get; set; }
        public Nullable<double> Uretim_Miktari { get; set; }
        public string Birimi { get; set; }
        public string Para_Birimi { get; set; }
        public Nullable<System.DateTime> Bas_Tarihi { get; set; }
        public Nullable<System.DateTime> Bit_Tarihi { get; set; }
        public Nullable<System.DateTime> Son_Tarihi { get; set; }
        public Nullable<double> Stok_Maliyeti { get; set; }
        public Nullable<double> Masraf { get; set; }
        public Nullable<double> Uretim_Maliyeti { get; set; }
        public Nullable<short> Ent_Kodu1 { get; set; }
        public Nullable<byte> Ent_Fis_Tipi1 { get; set; }
        public Nullable<int> Ent_Fis_No1 { get; set; }
        public Nullable<short> Ent_Kodu2 { get; set; }
        public Nullable<byte> Ent_Fis_Tipi2 { get; set; }
        public Nullable<int> Ent_Fis_No2 { get; set; }
        public Nullable<double> Miktari { get; set; }
        public Nullable<double> Birim_Maliyet { get; set; }
        public Nullable<byte> Kilit { get; set; }
        public string Parti_No { get; set; }
        public Nullable<int> Plan_FisNo { get; set; }
        public string Seri_No { get; set; }
        public Nullable<int> Satis_Ent_FisNo { get; set; }
        public Nullable<int> Ana_IsEmri_No { get; set; }
        public Nullable<byte> Maliyet_Tipi { get; set; }
        public string Acilis_User { get; set; }
        public string Update_User { get; set; }
        public string Iptal_User { get; set; }
        public Nullable<System.DateTime> Acilis_Zaman { get; set; }
        public Nullable<System.DateTime> Update_Zaman { get; set; }
        public Nullable<System.DateTime> Iptal_Zaman { get; set; }
        public Nullable<int> Satis_Ent_FisTipi { get; set; }
        public Nullable<int> Uretim_Tipi { get; set; }
        public string Eleman_Kodu { get; set; }
        public string Belge_Tipi { get; set; }
        public string Belge_No { get; set; }
        public Nullable<System.DateTime> Belge_Tarihi { get; set; }
    }
}
