//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class URET_Mamul
    {
        public short IptDrm { get; set; }
        public int Stok_No { get; set; }
        public string Stok_Adi { get; set; }
        public byte Tipi { get; set; }
        public Nullable<double> Min_Fire { get; set; }
        public Nullable<double> Max_Fire { get; set; }
        public Nullable<double> Carpan1 { get; set; }
        public Nullable<double> Carpan2 { get; set; }
        public Nullable<double> Carpan3 { get; set; }
        public Nullable<double> Carpan4 { get; set; }
        public Nullable<double> Carpan5 { get; set; }
        public Nullable<double> Fason_Maliyet { get; set; }
        public string Fason_ParaBirimi { get; set; }
    }
}
