//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class URET_Parti
    {
        public string Parti_No { get; set; }
        public string Parti_Tanimi { get; set; }
        public Nullable<System.DateTime> Parti_Tarihi { get; set; }
        public string Parti_Ozellik1 { get; set; }
        public string Parti_Ozellik2 { get; set; }
    }
}
