//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class URET_IsEmri_Plan
    {
        public short IsYeri_Kodu { get; set; }
        public short Fis_Tipi { get; set; }
        public int Fis_No { get; set; }
        public byte Fis_Durum { get; set; }
        public Nullable<System.DateTime> Fis_Tarihi { get; set; }
        public Nullable<int> Depo_Kodu { get; set; }
        public Nullable<System.DateTime> Bas_Tarihi { get; set; }
        public Nullable<System.DateTime> Bit_Tarihi { get; set; }
        public Nullable<byte> Kapali_Plan { get; set; }
        public string Acilis_User { get; set; }
        public string Update_User { get; set; }
        public string Iptal_User { get; set; }
        public Nullable<System.DateTime> Acilis_Zaman { get; set; }
        public Nullable<System.DateTime> Update_Zaman { get; set; }
        public Nullable<System.DateTime> Iptal_Zaman { get; set; }
        public Nullable<int> Sarf_Depo_Kodu { get; set; }
    }
}
