//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class URET_Gun_Parametreleri
    {
        public System.DateTime Gun_Tarih { get; set; }
        public Nullable<double> Gun_Masraf { get; set; }
        public Nullable<double> Gun_Miktar { get; set; }
    }
}
