//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class VERG_KDVler
    {
        public short Isyeri_Kodu { get; set; }
        public short Fis_Tipi { get; set; }
        public short Fis_Durum { get; set; }
        public int Fis_No { get; set; }
        public short Fis_KdvOr { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public string BelgeNo { get; set; }
        public Nullable<double> Kdv_Matrah { get; set; }
        public Nullable<double> Kdv_Tutar { get; set; }
        public Nullable<double> Kdv_Matrah2 { get; set; }
        public Nullable<double> Kdv_Tutar2 { get; set; }
    }
}
